/**
 * Brand favicon + theme-color metadata, shared across Next apps.
 *
 * The actual color values are baked into the per-app SVG / PNG / ICO files
 * served at these URLs (regenerated by `scripts/build-favicons.py` from
 * `--brand-*` tokens in `globals.css`). This module only declares the
 * shape of the `<head>` declarations — each app serves its own colorway
 * at the same paths from its own `public/` and `app/` dirs.
 *
 * Structural typing keeps `@workspace/ui` Next-free: the consts here
 * satisfy Next's `Metadata["icons"]` and `Viewport["themeColor"]` shapes
 * without importing from "next".
 */

const PNG_SIZES = [16, 32, 48]

const pngIcons = PNG_SIZES.flatMap((size) => [
  {
    url: `/favicon-${size}-light.png`,
    sizes: `${size}x${size}`,
    type: "image/png",
    media: "(prefers-color-scheme: light)",
  },
  {
    url: `/favicon-${size}-dark.png`,
    sizes: `${size}x${size}`,
    type: "image/png",
    media: "(prefers-color-scheme: dark)",
  },
])

export const BRAND_ICONS = {
  icon: [{ url: "/icon.svg", type: "image/svg+xml" }, ...pngIcons],
  apple: [{ url: "/apple-icon.png", sizes: "180x180", type: "image/png" }],
}

/**
 * Adaptive browser-chrome tint. Values mirror `--brand-mono-light` /
 * `--brand-mono-dark` in `globals.css`. Kept in sync by convention —
 * regenerating favicons is not enough; if the brand-mono token changes
 * the literal here must change too.
 */
export const BRAND_THEME_COLOR = [
  { media: "(prefers-color-scheme: light)", color: "#FFFFFF" },
  { media: "(prefers-color-scheme: dark)", color: "#0A1F1A" },
]
