type SourceType = "vanilla" | "import" | "custom"

type ComponentMeta = {
  source: string
  sourceType: SourceType
  upstream?: string
  description: string
  categories: string[]
  dependencies?: string[]
  packages?: string[]
}

export const registry: Record<string, ComponentMeta> = {
  accordion: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/accordion",
    description: "Vertically stacked expandable sections",
    categories: ["disclosure"],
  },
  "action-bar": {
    source: "diceui",
    sourceType: "import",
    upstream: "https://www.diceui.com/docs/components/radix/action-bar",
    description:
      "Floating toolbar with keyboard navigation, appearing on selection",
    categories: ["actions", "overlay"],
    dependencies: ["button"],
  },
  alert: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/alert",
    description:
      "Semantic alert container with default and destructive variants",
    categories: ["feedback"],
  },
  "alert-dialog": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/alert-dialog",
    description:
      "Modal dialog for confirmations with cancel and continue actions",
    categories: ["overlay"],
    dependencies: ["button"],
  },
  "aspect-ratio": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/aspect-ratio",
    description: "Container enforcing a fixed aspect ratio",
    categories: ["layout"],
  },
  avatar: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/avatar",
    description: "User avatar with image, fallback text, and group support",
    categories: ["display"],
  },
  badge: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/badge",
    description:
      "Small label with default, secondary, outline, and destructive variants",
    categories: ["display"],
  },
  breadcrumb: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/breadcrumb",
    description: "Navigation breadcrumb trail with separators",
    categories: ["navigation"],
  },
  button: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/button",
    description: "Core button with variants, sizes, and icon support",
    categories: ["actions"],
  },
  "button-group": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/button-group",
    description: "Container for visually grouped buttons",
    categories: ["actions", "layout"],
    dependencies: ["separator"],
  },
  calendar: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/calendar",
    description: "Date picker calendar with day selection",
    categories: ["forms"],
    dependencies: ["button"],
    packages: ["react-day-picker"],
  },
  card: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/card",
    description:
      "Container for grouped content with header, content, and footer",
    categories: ["layout"],
  },
  carousel: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/carousel",
    description: "Scrollable content carousel with navigation controls",
    categories: ["display"],
    dependencies: ["button"],
    packages: ["embla-carousel-react"],
  },
  chart: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/chart",
    description: "Data visualization wrapper for recharts",
    categories: ["data"],
    packages: ["recharts"],
  },
  checkbox: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/checkbox",
    description: "Toggle checkbox input with checked and indeterminate states",
    categories: ["forms"],
  },
  collapsible: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/collapsible",
    description: "Expandable and collapsible content section",
    categories: ["disclosure"],
  },
  combobox: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/combobox",
    description: "Searchable dropdown with autocomplete",
    categories: ["forms"],
    dependencies: ["button", "input-group"],
    packages: ["@base-ui/react"],
  },
  command: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/command",
    description: "Command palette with keyboard navigation and search",
    categories: ["overlay", "navigation"],
    dependencies: ["dialog", "input-group"],
    packages: ["cmdk"],
  },
  "context-menu": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/context-menu",
    description: "Right-click context menu with items and submenus",
    categories: ["overlay"],
  },
  dialog: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/dialog",
    description: "Modal dialog overlay with title, description, and actions",
    categories: ["overlay"],
    dependencies: ["button"],
  },
  direction: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/direction",
    description: "RTL/LTR direction provider wrapper",
    categories: ["layout"],
  },
  "download-trigger": {
    source: "ark-ui",
    sourceType: "import",
    upstream: "https://ark-ui.com/react/docs/utilities/download-trigger",
    description:
      "Programmatic file download utility supporting string, Blob, File, and async data",
    categories: ["utility"],
    packages: ["@ark-ui/react"],
  },
  drawer: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/drawer",
    description: "Slide-out drawer panel from screen edge",
    categories: ["overlay"],
    packages: ["vaul"],
  },
  "dropdown-menu": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/dropdown-menu",
    description: "Dropdown menu with items, separators, and keyboard shortcuts",
    categories: ["overlay"],
  },
  empty: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/empty",
    description: "Empty state display with icon, title, and description",
    categories: ["feedback"],
  },
  field: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/field",
    description:
      "Form field wrapper with label, description, and error message",
    categories: ["forms"],
    dependencies: ["label", "separator"],
  },
  "hover-card": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/hover-card",
    description: "Popup card appearing on hover",
    categories: ["overlay"],
  },
  input: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/input",
    description: "Text input field with focus and disabled states",
    categories: ["forms"],
  },
  "input-group": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/input-group",
    description: "Composite input with addon elements and buttons",
    categories: ["forms"],
    dependencies: ["button", "input", "textarea"],
  },
  "input-otp": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/input-otp",
    description: "One-time password input with segmented fields",
    categories: ["forms"],
    packages: ["input-otp"],
  },
  item: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/item",
    description: "List item with media, content, description, and actions",
    categories: ["display", "layout"],
    dependencies: ["separator"],
  },
  kbd: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/kbd",
    description: "Keyboard key display for shortcuts",
    categories: ["display"],
  },
  label: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/label",
    description: "Form label element",
    categories: ["forms"],
  },
  menubar: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/menubar",
    description: "Horizontal menu bar with dropdown submenus",
    categories: ["navigation"],
  },
  "native-select": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/native-select",
    description: "Native HTML select with custom styling",
    categories: ["forms"],
  },
  "navigation-menu": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/navigation-menu",
    description: "Horizontal navigation with dropdown content panels",
    categories: ["navigation"],
  },
  pagination: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/pagination",
    description: "Page navigation with previous, next, and numbered links",
    categories: ["navigation"],
    dependencies: ["button"],
  },
  popover: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/popover",
    description: "Positioned popover triggered by a button or element",
    categories: ["overlay"],
  },
  progress: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/progress",
    description: "Linear progress bar indicator",
    categories: ["feedback"],
  },
  "radio-group": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/radio-group",
    description: "Radio button group for single selection",
    categories: ["forms"],
  },
  resizable: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/resizable",
    description: "Resizable panel layout with drag handles",
    categories: ["layout"],
    packages: ["react-resizable-panels"],
  },
  "scroll-area": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/scroll-area",
    description: "Custom scrollbar wrapper with smooth scrolling",
    categories: ["layout"],
  },
  select: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/select",
    description: "Styled dropdown select with search and keyboard support",
    categories: ["forms"],
  },
  separator: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/separator",
    description: "Visual divider line, horizontal or vertical",
    categories: ["layout"],
  },
  sheet: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/sheet",
    description: "Side panel sliding in from any screen edge",
    categories: ["overlay"],
    dependencies: ["button"],
  },
  sidebar: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/sidebar",
    description: "Collapsible layout sidebar with mobile support",
    categories: ["navigation", "layout"],
    dependencies: [
      "button",
      "input",
      "separator",
      "sheet",
      "skeleton",
      "tooltip",
    ],
    packages: ["next-themes"],
  },
  skeleton: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/skeleton",
    description: "Animated placeholder for loading content",
    categories: ["feedback"],
  },
  slider: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/slider",
    description: "Range slider with draggable thumb",
    categories: ["forms"],
  },
  sonner: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/sonner",
    description: "Toast notification system",
    categories: ["feedback"],
    packages: ["sonner", "next-themes"],
  },
  spinner: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/spinner",
    description: "Animated loading spinner",
    categories: ["feedback"],
  },
  swap: {
    source: "diceui",
    sourceType: "import",
    upstream: "https://www.diceui.com/docs/components/radix/swap",
    description:
      "Animated toggle between two content states with fade, rotate, flip, and scale transitions",
    categories: ["actions", "effects"],
  },
  switch: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/switch",
    description: "Toggle switch for on/off states",
    categories: ["forms"],
  },
  table: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/table",
    description: "Data table with header, body, footer, and caption",
    categories: ["data"],
  },
  tabs: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/tabs",
    description: "Tabbed interface with content panels",
    categories: ["navigation"],
  },
  textarea: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/textarea",
    description: "Multi-line text input field",
    categories: ["forms"],
  },
  toggle: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/toggle",
    description: "Stateful toggle button with pressed/unpressed state",
    categories: ["actions"],
  },
  "toggle-group": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/toggle-group",
    description: "Group of mutually exclusive toggle buttons",
    categories: ["actions"],
    dependencies: ["toggle"],
  },
  tooltip: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/tooltip",
    description: "Hover tooltip with text content",
    categories: ["overlay"],
  },
}

export type { ComponentMeta, SourceType }
