type SourceType = "vanilla" | "import" | "custom"

type ComponentMeta = {
  source: string
  sourceType: SourceType
  upstream?: string
  description: string
  categories: string[]
  dependencies?: string[]
  packages?: string[]
}

export const registry: Record<string, ComponentMeta> = {
  accordion: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/accordion",
    description: "Vertically stacked expandable sections",
    categories: ["disclosure"],
  },
  "action-bar": {
    source: "diceui",
    sourceType: "import",
    upstream: "https://www.diceui.com/docs/components/radix/action-bar",
    description:
      "Floating toolbar with keyboard navigation, appearing on selection",
    categories: ["actions", "overlay"],
    dependencies: ["button"],
  },
  alert: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/alert",
    description:
      "Semantic alert container with default and destructive variants",
    categories: ["feedback"],
  },
  "api-response-viewer": {
    source: "tryelements",
    sourceType: "import",
    upstream: "https://www.tryelements.dev/docs/devtools/api-response-viewer",
    description:
      "Tabbed HTTP response inspector with semantic status badge, JSON body, headers table, and timing waterfall",
    categories: ["data", "display"],
    dependencies: ["button", "json-viewer", "tabs"],
  },
  "alert-dialog": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/alert-dialog",
    description:
      "Modal dialog for confirmations with cancel and continue actions",
    categories: ["overlay"],
    dependencies: ["button"],
  },
  "aspect-ratio": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/aspect-ratio",
    description: "Container enforcing a fixed aspect ratio",
    categories: ["layout"],
  },
  avatar: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/avatar",
    description: "User avatar with image, fallback text, and group support",
    categories: ["display"],
  },
  badge: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/badge",
    description:
      "Small label with default, secondary, outline, and destructive variants",
    categories: ["display"],
  },
  banner: {
    source: "diceui",
    sourceType: "import",
    upstream: "https://www.diceui.com/docs/components/radix/banner",
    description:
      "Dismissible notification banner with info/success/warning/destructive variants and optional queue manager",
    categories: ["feedback"],
    dependencies: ["button"],
  },
  breadcrumb: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/breadcrumb",
    description: "Navigation breadcrumb trail with separators",
    categories: ["navigation"],
  },
  browser: {
    source: "eldoraui",
    sourceType: "import",
    upstream: "https://www.eldoraui.site/docs/components/browser",
    description:
      "Browser simulator chrome with address bar, tabs, bookmarks, history, downloads, and settings",
    categories: ["display"],
    dependencies: ["badge", "button", "card", "input", "separator"],
  },
  "button-border-beam": {
    source: "cult-ui",
    sourceType: "import",
    upstream: "https://www.cult-ui.com/docs/components/border-beam-button",
    description: "Button wrapped with animated beam border effect",
    categories: ["actions", "effects"],
    dependencies: ["button"],
    packages: ["border-beam"],
  },
  button: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/button",
    description: "Core button with variants, sizes, and icon support",
    categories: ["actions"],
  },
  "button-group": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/button-group",
    description: "Container for visually grouped buttons",
    categories: ["actions", "layout"],
    dependencies: ["separator"],
  },
  "button-liquid-metal": {
    source: "jolyui",
    sourceType: "import",
    upstream:
      "https://www.jolyui.dev/docs/components/buttons/liquid-metal-button",
    description:
      "WebGL shader-powered button with 3D metallic liquid animation and ripple effects",
    categories: ["actions", "effects"],
    packages: ["@paper-design/shaders"],
  },
  calendar: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/calendar",
    description: "Date picker calendar with day selection",
    categories: ["forms"],
    dependencies: ["button"],
    packages: ["react-day-picker"],
  },
  card: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/card",
    description:
      "Container for grouped content with header, content, and footer",
    categories: ["layout"],
  },
  "card-extended": {
    source: "cardcn",
    sourceType: "import",
    upstream: "https://cardcn.dev/cards/basic-cards/",
    description:
      "Card with decorative variants: shadow, lines, hatched, aurora, tilted, stacked",
    categories: ["display", "layout"],
    dependencies: ["card"],
  },
  carousel: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/carousel",
    description: "Scrollable content carousel with navigation controls",
    categories: ["display"],
    dependencies: ["button"],
    packages: ["embla-carousel-react"],
  },
  "circular-progress": {
    source: "diceui",
    sourceType: "import",
    upstream: "https://www.diceui.com/docs/components/radix/circular-progress",
    description:
      "SVG circular progress indicator with track + range, indeterminate state, configurable size and thickness",
    categories: ["feedback", "display"],
  },
  chart: {
    source: "shadcn+evilcharts",
    sourceType: "custom",
    upstream: "https://ui.shadcn.com/docs/components/chart",
    description:
      "Unified chart component with area, bar/column, line, composed, pie, donut, and radar types. ChartContainer/Tooltip/Legend exported for custom recharts compositions.",
    categories: ["data"],
    packages: ["recharts"],
  },
  checkbox: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/checkbox",
    description: "Toggle checkbox input with checked and indeterminate states",
    categories: ["forms"],
  },
  collapsible: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/collapsible",
    description: "Expandable and collapsible content section",
    categories: ["disclosure"],
  },
  "color-swatch": {
    source: "diceui",
    sourceType: "import",
    upstream: "https://www.diceui.com/docs/components/radix/color-swatch",
    description:
      "Color preview swatch with sm/default/lg sizes, transparency checker, and asChild support",
    categories: ["display"],
  },
  "commit-graph": {
    source: "justinlevine",
    sourceType: "import",
    upstream: "https://ui.justinlevine.me/docs/components/commit-graph",
    description:
      "Topological git graph with SVG rail lines, branch forks, merges, and commit popovers",
    categories: ["display", "data"],
  },
  combobox: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/combobox",
    description: "Searchable dropdown with autocomplete",
    categories: ["forms"],
    dependencies: ["button", "input-group"],
    packages: ["@base-ui/react"],
  },
  command: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/command",
    description: "Command palette with keyboard navigation and search",
    categories: ["overlay", "navigation"],
    dependencies: ["dialog", "input-group"],
    packages: ["cmdk"],
  },
  "context-menu": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/context-menu",
    description: "Right-click context menu with items and submenus",
    categories: ["overlay"],
  },
  dialog: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/dialog",
    description: "Modal dialog overlay with title, description, and actions",
    categories: ["overlay"],
    dependencies: ["button"],
  },
  direction: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/direction",
    description: "RTL/LTR direction provider wrapper",
    categories: ["layout"],
  },
  "download-trigger": {
    source: "ark-ui",
    sourceType: "import",
    upstream: "https://ark-ui.com/react/docs/utilities/download-trigger",
    description:
      "Programmatic file download utility supporting string, Blob, File, and async data",
    categories: ["utility"],
    packages: ["@ark-ui/react"],
  },
  drawer: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/drawer",
    description: "Slide-out drawer panel from screen edge",
    categories: ["overlay"],
    packages: ["vaul"],
  },
  "dropdown-menu": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/dropdown-menu",
    description: "Dropdown menu with items, separators, and keyboard shortcuts",
    categories: ["overlay"],
  },
  empty: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/empty",
    description: "Empty state display with icon, title, and description",
    categories: ["feedback"],
  },
  "env-editor": {
    source: "tryelements",
    sourceType: "import",
    upstream: "https://www.tryelements.dev/docs/devtools/env-editor",
    description:
      "Key-value editor for environment variables with masked values, add/remove rows, and .env import/export",
    categories: ["forms", "data"],
    dependencies: ["button", "input"],
  },
  "error-boundary-ui": {
    source: "tryelements",
    sourceType: "import",
    upstream: "https://www.tryelements.dev/docs/devtools/error-boundary-ui",
    description:
      "Error fallback display with stack trace parsing, copy-to-clipboard, retry, and dev/prod verbosity modes",
    categories: ["feedback"],
    dependencies: ["button"],
  },
  field: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/field",
    description:
      "Form field wrapper with label, description, and error message",
    categories: ["forms"],
    dependencies: ["label", "separator"],
  },
  gauge: {
    source: "diceui",
    sourceType: "import",
    upstream: "https://www.diceui.com/docs/components/radix/gauge",
    description:
      "SVG gauge/meter with configurable min/max, thickness, start/end angles, and value text",
    categories: ["display", "feedback"],
  },
  "hover-card": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/hover-card",
    description: "Popup card appearing on hover",
    categories: ["overlay"],
  },
  input: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/input",
    description: "Text input field with focus and disabled states",
    categories: ["forms"],
  },
  "input-group": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/input-group",
    description: "Composite input with addon elements and buttons",
    categories: ["forms"],
    dependencies: ["button", "input", "textarea"],
  },
  "input-otp": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/input-otp",
    description: "One-time password input with segmented fields",
    categories: ["forms"],
    packages: ["input-otp"],
  },
  item: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/item",
    description: "List item with media, content, description, and actions",
    categories: ["display", "layout"],
    dependencies: ["separator"],
  },
  "json-viewer": {
    source: "tryelements",
    sourceType: "import",
    upstream: "https://www.tryelements.dev/docs/devtools/json-viewer",
    description:
      "Collapsible JSON tree with chart-token syntax highlighting, search filter, and copy-path-on-hover",
    categories: ["data", "display"],
    dependencies: ["button", "input"],
  },
  kbd: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/kbd",
    description: "Keyboard key display for shortcuts",
    categories: ["display"],
  },
  "key-value": {
    source: "diceui",
    sourceType: "import",
    upstream: "https://www.diceui.com/docs/components/radix/key-value",
    description:
      "Generic editable key-value pair input with paste-parsing, validation, duplicate detection, and reorder",
    categories: ["display", "forms"],
    dependencies: ["button", "input", "textarea"],
  },
  marquee: {
    source: "magicui",
    sourceType: "import",
    upstream: "https://magicui.design/docs/components/marquee",
    description:
      "Horizontal or vertical scrolling marquee with pause-on-hover, reverse, and configurable speed",
    categories: ["effects"],
  },
  "multi-step-loader": {
    source: "aceternity",
    sourceType: "import",
    upstream: "https://ui.aceternity.com/components/multi-step-loader",
    description:
      "Full-screen overlay that cycles through ordered loading states with check animations",
    categories: ["feedback", "effects"],
    packages: ["motion"],
  },
  "noise-background": {
    source: "aceternity",
    sourceType: "import",
    upstream: "https://ui.aceternity.com/components/noise-background",
    description:
      "Animated gradient backdrop with SVG turbulence noise overlay, semantic-token defaults, optional backdrop blur",
    categories: ["effects", "display"],
    packages: ["motion"],
  },
  label: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/label",
    description: "Form label element",
    categories: ["forms"],
  },
  menubar: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/menubar",
    description: "Horizontal menu bar with dropdown submenus",
    categories: ["navigation"],
  },
  "native-select": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/native-select",
    description: "Native HTML select with custom styling",
    categories: ["forms"],
  },
  "navigation-menu": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/navigation-menu",
    description: "Horizontal navigation with dropdown content panels",
    categories: ["navigation"],
  },
  pagination: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/pagination",
    description: "Page navigation with previous, next, and numbered links",
    categories: ["navigation"],
    dependencies: ["button"],
  },
  popover: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/popover",
    description: "Positioned popover triggered by a button or element",
    categories: ["overlay"],
  },
  progress: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/progress",
    description: "Linear progress bar indicator",
    categories: ["feedback"],
  },
  "qr-code": {
    source: "diceui",
    sourceType: "import",
    upstream: "https://www.diceui.com/docs/components/radix/qr-code",
    description:
      "QR code generator with configurable size, error correction level, optional logo overlay, and PNG/SVG download",
    categories: ["display"],
    packages: ["qrcode"],
  },
  "radio-group": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/radio-group",
    description: "Radio button group for single selection",
    categories: ["forms"],
  },
  resizable: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/resizable",
    description: "Resizable panel layout with drag handles",
    categories: ["layout"],
    packages: ["react-resizable-panels"],
  },
  "ring-loader": {
    source: "loading-ui",
    sourceType: "import",
    upstream: "https://loading-ui.com",
    description:
      "Lightweight SVG spinning ring indicator with currentColor and --duration override",
    categories: ["feedback"],
  },
  "scroll-area": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/scroll-area",
    description: "Custom scrollbar wrapper with smooth scrolling",
    categories: ["layout"],
  },
  select: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/select",
    description: "Styled dropdown select with search and keyboard support",
    categories: ["forms"],
  },
  separator: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/separator",
    description: "Visual divider line, horizontal or vertical",
    categories: ["layout"],
  },
  sheet: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/sheet",
    description: "Side panel sliding in from any screen edge",
    categories: ["overlay"],
    dependencies: ["button"],
  },
  sidebar: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/sidebar",
    description: "Collapsible layout sidebar with mobile support",
    categories: ["navigation", "layout"],
    dependencies: [
      "button",
      "input",
      "separator",
      "sheet",
      "skeleton",
      "tooltip",
    ],
    packages: ["next-themes"],
  },
  skeleton: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/skeleton",
    description: "Animated placeholder for loading content",
    categories: ["feedback"],
  },
  slider: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/slider",
    description: "Range slider with draggable thumb",
    categories: ["forms"],
  },
  "snail-timer": {
    source: "uicapsule",
    sourceType: "import",
    upstream: "https://www.uicapsule.com",
    description:
      "Animated countdown timer with a token-themed snail traversing the container, configurable initial seconds",
    categories: ["feedback"],
  },
  sonner: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/sonner",
    description: "Toast notification system",
    categories: ["feedback"],
    packages: ["sonner", "next-themes"],
  },
  "stateful-button": {
    source: "aceternity",
    sourceType: "import",
    upstream: "https://ui.aceternity.com/components/stateful-button",
    description:
      "Hook providing loading/success/error state machine for async button actions",
    categories: ["utility", "actions"],
  },
  spinner: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/spinner",
    description: "Animated loading spinner",
    categories: ["feedback"],
  },
  swap: {
    source: "diceui",
    sourceType: "import",
    upstream: "https://www.diceui.com/docs/components/radix/swap",
    description:
      "Animated toggle between two content states with fade, rotate, flip, and scale transitions",
    categories: ["actions", "effects"],
  },
  switch: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/switch",
    description: "Toggle switch for on/off states",
    categories: ["forms"],
  },
  table: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/table",
    description: "Data table with header, body, footer, and caption",
    categories: ["data"],
  },
  tabs: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/tabs",
    description: "Tabbed interface with content panels",
    categories: ["navigation"],
  },
  textarea: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/textarea",
    description: "Multi-line text input field",
    categories: ["forms"],
  },
  timeline: {
    source: "diceui",
    sourceType: "import",
    upstream: "https://www.diceui.com/docs/components/radix/timeline",
    description:
      "Vertical/horizontal timeline with active step tracking, connector lines, dot status, and optional alternate layout",
    categories: ["display"],
  },
  toggle: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/toggle",
    description: "Stateful toggle button with pressed/unpressed state",
    categories: ["actions"],
  },
  "toggle-group": {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/toggle-group",
    description: "Group of mutually exclusive toggle buttons",
    categories: ["actions"],
    dependencies: ["toggle"],
  },
  tooltip: {
    source: "shadcn",
    sourceType: "vanilla",
    upstream: "https://ui.shadcn.com/docs/components/tooltip",
    description: "Hover tooltip with text content",
    categories: ["overlay"],
  },
  "webhook-tester": {
    source: "tryelements",
    sourceType: "import",
    upstream: "https://www.tryelements.dev/docs/devtools/webhook-tester",
    description:
      "HTTP request builder with method selector, header editor, JSON body, and semantic-colored response. Requires caller-supplied onSend handler (no built-in fetch).",
    categories: ["forms", "data"],
    dependencies: ["button", "input", "native-select", "textarea"],
  },
}

export type { ComponentMeta, SourceType }
