import type * as React from "react"

/**
 * Common interface every icon component must satisfy. Extends
 * `SVGProps` so callers can pass `size`, `onClick`, `aria-label`,
 * etc — lucide and phosphor both accept this surface. The pack-
 * specific extras (lucide's `strokeWidth`, phosphor's `weight` +
 * `mirrored`) are NOT in the common type — pass them via the
 * pack's own component import if you need them.
 */
export type IconComponent = React.ComponentType<React.SVGProps<SVGSVGElement>>

/**
 * Canonical icon names. Each pack MUST export every name in this
 * list — enforced by `satisfies IconMap` on the pack's const + the
 * `pnpm check:icon-packs` script in CI.
 *
 * Adding a new icon: append it here, then add the corresponding
 * import to every pack. CI will fail until all packs are updated.
 */
export const ICON_NAMES = [
  "Activity",
  "AlertTriangle",
  "Archive",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRightIcon",
  "ArrowUp",
  "ArrowUpDown",
  "ArrowUpRight",
  "Award",
  "Banknote",
  "BarChart3",
  "BaselineIcon",
  "Battery",
  "Bell",
  "BookmarkIcon",
  "BookOpen",
  "BookOpenText",
  "Box",
  "Briefcase",
  "Bug",
  "Building2",
  "Calculator",
  "CalendarIcon",
  "Check",
  "CheckCircle2",
  "CheckCircle2Icon",
  "CheckIcon",
  "CheckSquareIcon",
  "ChevronDown",
  "ChevronDownIcon",
  "ChevronLeft",
  "ChevronLeftIcon",
  "ChevronRight",
  "ChevronRightIcon",
  "ChevronUp",
  "ChevronUpIcon",
  "ChevronsLeft",
  "ChevronsRight",
  "ChevronsUpDown",
  "ChevronsUpDownIcon",
  "CircleCheckIcon",
  "ClipboardIcon",
  "Code2",
  "Copy",
  "CopyIcon",
  "Download",
  "Ellipsis",
  "EraserIcon",
  "Eye",
  "EyeOff",
  "File",
  "FileArchive",
  "FileArchiveIcon",
  "FileAudio",
  "FileAudioIcon",
  "FileCodeIcon",
  "FileCogIcon",
  "FileIcon",
  "FileImage",
  "FileSpreadsheet",
  "FileText",
  "FileTextIcon",
  "FileVideo",
  "FileVideoIcon",
  "FilterIcon",
  "FilterXIcon",
  "FolderOpen",
  "Globe",
  "GraduationCap",
  "HashIcon",
  "History",
  "Home",
  "Inbox",
  "InfoIcon",
  "KeyRound",
  "LifeBuoy",
  "LinkIcon",
  "ListChecksIcon",
  "ListIcon",
  "Loader2",
  "Loader2Icon",
  "Lock",
  "Mail",
  "Maximize",
  "Maximize2",
  "MaximizeIcon",
  "MessageCircle",
  "MessageSquare",
  "Minimize2",
  "MinimizeIcon",
  "MinusIcon",
  "Monitor",
  "Moon",
  "MoreHorizontal",
  "MoreHorizontalIcon",
  "OctagonXIcon",
  "Palette",
  "PanelLeftClose",
  "PanelLeftIcon",
  "PanelLeftOpen",
  "PanelRight",
  "PanelRightClose",
  "PanelRightOpen",
  "Pencil",
  "PiggyBank",
  "Plus",
  "PlusCircle",
  "PlusIcon",
  "Presentation",
  "RefreshCw",
  "RotateCcw",
  "RotateCcwIcon",
  "ScissorsIcon",
  "Search",
  "SearchIcon",
  "Send",
  "Settings",
  "Settings2",
  "Shield",
  "Sparkles",
  "Square",
  "Star",
  "StarOff",
  "Sun",
  "Terminal",
  "TextInitialIcon",
  "Trash2",
  "Trash2Icon",
  "TriangleAlertIcon",
  "Upload",
  "UploadIcon",
  "User",
  "UserIcon",
  "UserPlus",
  "Users",
  "Volume2",
  "Wifi",
  "X",
  "XCircle",
  "XCircleIcon",
  "XIcon",
  "BriefcaseBusiness",
  "CalendarClock",
  "ChartNoAxesCombined",
  "FolderBookmark",
  "Goal",
  "IdCard",
  "SwatchBook",
  "BookUser",
  "Circle",
  "CircleUser",
  "ListTodo",
  "Keyboard",
  "GitPullRequestArrow",
  "Info",
  "CircleHelp",
  "Blocks",
  "Workflow",
  "HatGlasses",
  "CreditCard",
] as const

export type IconName = (typeof ICON_NAMES)[number]

/**
 * Exhaustive icon map: every `IconName` MUST resolve to an
 * `IconComponent`. `satisfies IconMap` on a pack will TypeScript-error
 * if a key is missing, plus the CI parity script catches drift on PRs
 * that touch only one pack.
 */
export type IconMap = Record<IconName, IconComponent>

/**
 * Identifier for an installed icon pack. Add new packs to this union
 * and to the `PACKS` lookup in `icon-context.tsx`.
 */
export type IconPackName = "lucide" | "phosphor" | "fontawesome"
