/**
 * The TOTP lifecycle, against the REAL Better Auth instance and a real
 * database: enrol → verify → sign in with a code → disable, plus the backup
 * codes and the password change's session revocation.
 *
 * Everything goes through `betaAuth().handler(new Request(...))` rather than
 * `auth.api.*`, because the HTTP handler is the surface the browser actually
 * talks to — it is where the rate limiter lives, where the cookies are set, and
 * where the twoFactor() plugin's sign-in hook runs. A test that called the api
 * shortcut would assert a path production never takes.
 */
import { createHmac } from "node:crypto"
import postgres from "postgres"
import { afterAll, beforeEach, describe, expect, it } from "vitest"

import { sharedDatabaseUrl, unique } from "../../tests/scratch-db"

const SECRET = `beta-test-secret-${"x".repeat(40)}`
process.env["BETTER_AUTH_SECRET"] ??= SECRET
process.env["BETTER_AUTH_URL"] ??= "http://localhost:3200"

const { betaAuth } = await import("./server")
const { BETA_COOKIE_NAMES, BETA_SESSION_COOKIE_NAME } = await import("./policy")

const sql = postgres(sharedDatabaseUrl(), { max: 4, onnotice: () => {} })

afterAll(async () => {
  await sql.end({ timeout: 5 })
})

const PASSWORD = "Beta-Heslo-2026!"
const ORIGIN = "http://localhost:3200"

/**
 * One IP per test, so the 5/minute budgets on the verify endpoints
 * (`BETA_RATE_LIMIT_RULES`) never leak across cases — a shared IP would make
 * the suite order-dependent the moment a test does six things.
 */
let ipCounter = 0
function freshIp(): string {
  ipCounter += 1
  return `198.51.100.${ipCounter % 250}`
}

type Call = {
  status: number
  body: unknown
  setCookie: string[]
  cookieHeader: string
}

async function call(
  path: string,
  options: { body?: unknown; cookie?: string; ip?: string } = {},
): Promise<Call> {
  const headers: Record<string, string> = {
    "content-type": "application/json",
    "cf-connecting-ip": options.ip ?? freshIp(),
    origin: ORIGIN,
  }
  if (options.cookie) headers["cookie"] = options.cookie

  const response = await betaAuth().handler(
    new Request(`${ORIGIN}/api/auth${path}`, {
      method: "POST",
      headers,
      body: JSON.stringify(options.body ?? {}),
    }),
  )

  const setCookie = response.headers.getSetCookie()
  const text = await response.text()
  return {
    status: response.status,
    body: text === "" ? null : (JSON.parse(text) as unknown),
    setCookie,
    cookieHeader: setCookie.map((c) => c.split(";")[0]!).join("; "),
  }
}

/** A real account, created the only way beta allows: through a setup link. */
async function account(): Promise<{ email: string; userId: string }> {
  const { consumeSetupToken, generateSetupToken, hashSetupToken } =
    await import("./setup-token")

  const email = `${unique("totp")}@example.com`
  const [staff] = await sql<{ id: string }[]>`
    INSERT INTO app_user (email, is_staff)
    VALUES (${`${unique("staff")}@example.com`}, true)
    RETURNING id
  `
  const raw = generateSetupToken()
  await sql`
    INSERT INTO user_setup_token
      (purpose, token_hash, email, issued_by_user_id, expires_at)
    VALUES ('account_setup', ${hashSetupToken(raw)}, ${email}, ${staff!.id},
            now() + interval '71 hours')
  `
  const result = await consumeSetupToken({
    rawToken: raw,
    allowedPurposes: ["account_setup"],
    password: PASSWORD,
    ip: null,
    userAgent: null,
  })
  if (!result.ok) throw new Error("fixture: setup link was refused")
  return { email, userId: result.userId }
}

/** Sign in with the password alone; returns whatever the endpoint answered. */
async function signIn(email: string, ip = freshIp()): Promise<Call> {
  return call("/sign-in/email", { body: { email, password: PASSWORD }, ip })
}

/**
 * RFC 6238, implemented here rather than imported.
 *
 * `@better-auth/utils` is a transitive dependency of better-auth, not a direct
 * one of this app, and adding it as a devDependency to compute six digits would
 * be a `pnpm-lock.yaml` change — a cold rebuild of every package in the
 * monorepo (PR-WORKFLOW's cache-buster rule). Thirty lines of node:crypto is the
 * cheaper trade, and it makes the test an INDEPENDENT implementation: a code
 * generated by the same library that verifies it would agree with a broken
 * library about a broken code.
 */
const BASE32 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"

function base32Decode(input: string): Buffer {
  const clean = input.replace(/=+$/, "").toUpperCase()
  let bits = 0
  let value = 0
  const out: number[] = []
  for (const char of clean) {
    const index = BASE32.indexOf(char)
    if (index === -1) throw new Error(`not base32: ${char}`)
    value = (value << 5) | index
    bits += 5
    if (bits >= 8) {
      bits -= 8
      out.push((value >>> bits) & 0xff)
    }
  }
  return Buffer.from(out)
}

function totp(secret: string, atMs: number = Date.now()): string {
  const counter = Math.floor(atMs / 1000 / 30)
  const message = Buffer.alloc(8)
  message.writeBigUInt64BE(BigInt(counter))
  const digest = createHmac("sha1", base32Decode(secret))
    .update(message)
    .digest()
  const offset = digest[digest.length - 1]! & 0x0f
  const binary =
    ((digest[offset]! & 0x7f) << 24) |
    ((digest[offset + 1]! & 0xff) << 16) |
    ((digest[offset + 2]! & 0xff) << 8) |
    (digest[offset + 3]! & 0xff)
  return String(binary % 1_000_000).padStart(6, "0")
}

/** The `secret` parameter of the `otpauth://` URI the enrol step returned. */
function secretOf(totpURI: string): string {
  const secret = new URL(totpURI).searchParams.get("secret")
  if (!secret) throw new Error(`no secret in ${totpURI}`)
  return secret
}

/**
 * Enrol and fully verify, returning what the caller needs to keep going.
 *
 * `cookie` is the NEW session cookie, not the one that was passed in.
 * `/two-factor/verify-totp` ROTATES the session on the enrolment path — it
 * mints a fresh one and deletes the active one
 * (`dist/plugins/two-factor/totp/index.mjs`) — so the caller's original cookie
 * is dead the moment enrolment succeeds. That is correct behaviour (a session
 * established before the second factor existed should not survive it acquiring
 * one) and it is exactly the kind of thing a test that reused the old cookie
 * would report as "disable is broken".
 */
async function enrol(cookie: string): Promise<{
  secret: string
  backupCodes: string[]
  cookie: string
}> {
  const enable = await call("/two-factor/enable", {
    body: { password: PASSWORD },
    cookie,
  })
  if (enable.status !== 200) throw new Error(`enable failed: ${enable.status}`)
  const { totpURI, backupCodes } = enable.body as {
    totpURI: string
    backupCodes: string[]
  }
  const secret = secretOf(totpURI)

  const verify = await call("/two-factor/verify-totp", {
    body: { code: totp(secret) },
    cookie,
  })
  if (verify.status !== 200) throw new Error(`verify failed: ${verify.status}`)

  return { secret, backupCodes, cookie: verify.cookieHeader || cookie }
}

async function sessionCount(userId: string): Promise<number> {
  const [row] = await sql<{ count: number }[]>`
    SELECT count(*)::int AS count FROM auth_session WHERE user_id = ${userId}
  `
  return row!.count
}

let subject: { email: string; userId: string }

beforeEach(async () => {
  subject = await account()
})

describe("TOTP lifecycle", () => {
  it("enrols, verifies, then challenges the next sign-in", async () => {
    const first = await signIn(subject.email)
    expect(first.status).toBe(200)

    // --- enable: a secret and codes exist, but the factor is NOT yet on ---
    const enable = await call("/two-factor/enable", {
      body: { password: PASSWORD },
      cookie: first.cookieHeader,
    })
    expect(enable.status).toBe(200)
    const enabled = enable.body as { totpURI: string; backupCodes: string[] }
    expect(enabled.totpURI.startsWith("otpauth://totp/")).toBe(true)
    expect(enabled.backupCodes.length).toBeGreaterThan(0)

    const [pending] = await sql<{ verified: boolean }[]>`
      SELECT verified FROM two_factor WHERE user_id = ${subject.userId}
    `
    // The column 0013 adds, doing its job: enrolment is not proof.
    expect(pending!.verified).toBe(false)
    const [beforeVerify] = await sql<{ two_factor_enabled: boolean }[]>`
      SELECT two_factor_enabled FROM app_user WHERE id = ${subject.userId}
    `
    expect(beforeVerify!.two_factor_enabled).toBe(false)

    // --- verify: the human proves they hold the secret ---
    const secret = secretOf(enabled.totpURI)
    const verify = await call("/two-factor/verify-totp", {
      body: { code: totp(secret) },
      cookie: first.cookieHeader,
    })
    expect(verify.status).toBe(200)

    const [after] = await sql<
      { verified: boolean; two_factor_enabled: boolean }[]
    >`
      SELECT t.verified, u.two_factor_enabled
        FROM two_factor t JOIN app_user u ON u.id = t.user_id
       WHERE t.user_id = ${subject.userId}
    `
    expect(after!.verified).toBe(true)
    expect(after!.two_factor_enabled).toBe(true)

    // --- sign in again: the password alone no longer produces a session ---
    const challenged = await signIn(subject.email)
    expect(challenged.status).toBe(200)
    expect(challenged.body).toMatchObject({ twoFactorRedirect: true })
    expect(
      await betaAuth().api.getSession({
        headers: new Headers({ cookie: challenged.cookieHeader }),
      }),
    ).toBeNull()
    // The challenge ticket is a credential in flight and carries the `__Host-`
    // name `policy.ts` assigns it.
    expect(
      challenged.setCookie.some((c) =>
        c.startsWith(`${BETA_COOKIE_NAMES.two_factor}=`),
      ),
    ).toBe(true)

    // --- and the code completes it ---
    const completed = await call("/two-factor/verify-totp", {
      body: { code: totp(secret) },
      cookie: challenged.cookieHeader,
    })
    expect(completed.status).toBe(200)
    expect(
      completed.setCookie.some((c) =>
        c.startsWith(`${BETA_SESSION_COOKIE_NAME}=`),
      ),
    ).toBe(true)
    expect(
      await betaAuth().api.getSession({
        headers: new Headers({ cookie: completed.cookieHeader }),
      }),
    ).not.toBeNull()
  })

  it("refuses a wrong code and does not enable the factor", async () => {
    const session = await signIn(subject.email)
    await call("/two-factor/enable", {
      body: { password: PASSWORD },
      cookie: session.cookieHeader,
    })

    const wrong = await call("/two-factor/verify-totp", {
      body: { code: "000000" },
      cookie: session.cookieHeader,
    })
    expect(wrong.status).toBeGreaterThanOrEqual(400)

    const [row] = await sql<{ two_factor_enabled: boolean }[]>`
      SELECT two_factor_enabled FROM app_user WHERE id = ${subject.userId}
    `
    expect(row!.two_factor_enabled).toBe(false)
  })

  it("refuses to enable without the account password", async () => {
    const session = await signIn(subject.email)
    const attempt = await call("/two-factor/enable", {
      body: { password: "Wrong-Pass-1!" },
      cookie: session.cookieHeader,
    })
    expect(attempt.status).toBeGreaterThanOrEqual(400)
    expect(
      await sql`SELECT 1 FROM two_factor WHERE user_id = ${subject.userId}`,
    ).toHaveLength(0)
  })

  it("disables only with the password, and clears the stored secret", async () => {
    const session = await signIn(subject.email)
    const enrolled = await enrol(session.cookieHeader)

    const refused = await call("/two-factor/disable", {
      body: { password: "Wrong-Pass-1!" },
      cookie: enrolled.cookie,
    })
    expect(refused.status).toBeGreaterThanOrEqual(400)
    expect(
      await sql`SELECT 1 FROM two_factor WHERE user_id = ${subject.userId}`,
    ).toHaveLength(1)

    const disabled = await call("/two-factor/disable", {
      body: { password: PASSWORD },
      cookie: enrolled.cookie,
    })
    expect(disabled.status).toBe(200)
    expect(
      await sql`SELECT 1 FROM two_factor WHERE user_id = ${subject.userId}`,
    ).toHaveLength(0)
    const [row] = await sql<{ two_factor_enabled: boolean }[]>`
      SELECT two_factor_enabled FROM app_user WHERE id = ${subject.userId}
    `
    expect(row!.two_factor_enabled).toBe(false)

    // And the password alone signs in again.
    const plain = await signIn(subject.email)
    expect(plain.body).not.toMatchObject({ twoFactorRedirect: true })
  })
})

describe("backup codes", () => {
  it("completes a sign-in once, and is consumed by doing so", async () => {
    const session = await signIn(subject.email)
    const { backupCodes } = await enrol(session.cookieHeader)
    const code = backupCodes[0]!

    const challenge = await signIn(subject.email)
    expect(challenge.body).toMatchObject({ twoFactorRedirect: true })
    const used = await call("/two-factor/verify-backup-code", {
      body: { code },
      cookie: challenge.cookieHeader,
    })
    expect(used.status).toBe(200)

    // The SAME code must not work a second time.
    const again = await signIn(subject.email)
    const reused = await call("/two-factor/verify-backup-code", {
      body: { code },
      cookie: again.cookieHeader,
    })
    expect(reused.status).toBeGreaterThanOrEqual(400)
  })

  it("regenerating replaces the old set", async () => {
    const session = await signIn(subject.email)
    const { backupCodes: original, cookie } = await enrol(session.cookieHeader)

    const regenerated = await call("/two-factor/generate-backup-codes", {
      body: { password: PASSWORD },
      cookie,
    })
    expect(regenerated.status).toBe(200)
    const fresh = (regenerated.body as { backupCodes: string[] }).backupCodes
    expect(fresh).not.toEqual(original)

    // An old code no longer completes a challenge.
    const challenge = await signIn(subject.email)
    const stale = await call("/two-factor/verify-backup-code", {
      body: { code: original[0]! },
      cookie: challenge.cookieHeader,
    })
    expect(stale.status).toBeGreaterThanOrEqual(400)
  })

  it("refuses to regenerate without the password", async () => {
    const session = await signIn(subject.email)
    const { cookie } = await enrol(session.cookieHeader)

    const attempt = await call("/two-factor/generate-backup-codes", {
      body: { password: "Wrong-Pass-1!" },
      cookie,
    })
    expect(attempt.status).toBeGreaterThanOrEqual(400)
  })
})

describe("password change", () => {
  it("revokes every OTHER session and keeps this one", async () => {
    const other = await signIn(subject.email)
    const here = await signIn(subject.email)
    expect(await sessionCount(subject.userId)).toBe(2)

    const changed = await call("/change-password", {
      body: {
        currentPassword: PASSWORD,
        newPassword: "Beta-Heslo-2027!",
        revokeOtherSessions: true,
      },
      cookie: here.cookieHeader,
    })
    expect(changed.status).toBe(200)

    // Exactly one session survives — the new one this browser was handed.
    expect(await sessionCount(subject.userId)).toBe(1)

    const otherStillWorks = await betaAuth().api.getSession({
      headers: new Headers({ cookie: other.cookieHeader }),
    })
    expect(otherStillWorks).toBeNull()

    // And the old password no longer signs anyone in.
    const withOld = await signIn(subject.email)
    expect(withOld.status).toBeGreaterThanOrEqual(400)
  })

  it("refuses without the current password, changing nothing", async () => {
    const session = await signIn(subject.email)
    const attempt = await call("/change-password", {
      body: {
        currentPassword: "Wrong-Pass-1!",
        newPassword: "Beta-Heslo-2027!",
        revokeOtherSessions: true,
      },
      cookie: session.cookieHeader,
    })
    expect(attempt.status).toBeGreaterThanOrEqual(400)

    const stillWorks = await signIn(subject.email)
    expect(stillWorks.status).toBe(200)
  })
})

describe("rate limits on the second factor", () => {
  it("cuts off repeated wrong codes from one IP", async () => {
    const session = await signIn(subject.email)
    await enrol(session.cookieHeader)

    const challenge = await signIn(subject.email)
    const ip = "198.51.100.251"
    const statuses: number[] = []
    for (let i = 0; i < 7; i++) {
      const attempt = await call("/two-factor/verify-totp", {
        body: { code: "000000" },
        cookie: challenge.cookieHeader,
        ip,
      })
      statuses.push(attempt.status)
    }

    // 5/minute: six digits with no budget is not a second factor.
    expect(statuses).toContain(429)
    expect(statuses.slice(0, 5).every((s) => s !== 429)).toBe(true)
  })
})
