// Směrná účtová osnova (reference data). Generated from a standard chart of accounts.
// No org/personal data. Used for Phase 2 (account -> výkaz řádek mapping).
import type { OsnovaAccount } from "../_lib/types"

export const OSNOVA: OsnovaAccount[] = [
  {
    ucet: "010000",
    nazev: "Dlouhodobý nehmotný majetek",
    nameEn: "Intangible fixed assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "012000",
    nazev: "Nehmotné výsledky výzkumu a vývoje",
    nameEn: "Intangible research and development results",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "013000",
    nazev: "Software",
    nameEn: "Software",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "014000",
    nazev: "Ostatní ocenitelná práva",
    nameEn: "Other appraisable rights",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "015000",
    nazev: "Goodwill",
    nameEn: "Goodwill",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "019000",
    nazev: "Ostatní dlouhodobý nehmotný majetek",
    nameEn: "Other long-term intangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "020000",
    nazev: "Dlouhodobý hmotný majetek odpisovaný",
    nameEn: "Depreciated tangible fixed assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "021000",
    nazev: "Stavby",
    nameEn: "Buildings, halls and structures",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "022000",
    nazev: "Hmotné movité věci a jejich soubory",
    nameEn: "Tangible movable assets and their sets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "025000",
    nazev: "Pěstitelské celky trvalých porostů",
    nameEn: "Perennial crops",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "026000",
    nazev: "Dospělá zvířata a jejich skupiny",
    nameEn: "Breeding and draught animals",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "029000",
    nazev: "Jiný dlouhodobý hmotný majetek",
    nameEn: "Other long-term tangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "030000",
    nazev: "Dlouhodobý hmotný majetek neodpisovaný",
    nameEn: "Non-depreciated tangible fixed assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "031000",
    nazev: "Pozemky",
    nameEn: "Land",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "032000",
    nazev: "Umělecká díla a sbírky",
    nameEn: "Works of art and collections",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "040000",
    nazev: "Nedokončený dlouhodobý nehmotný a hmotný majetek",
    nameEn: "Incomplete tangible and intangible fixed assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "041000",
    nazev: "Nedokončený dlouhodobý nehmotný majetek",
    nameEn: "Acquisition of long-term intangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "042000",
    nazev: "Nedokončený dlouhodobý hmotný majetek",
    nameEn: "Acquisition of long-term tangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "043000",
    nazev: "Pořízení dlouhodobého finančního majetku",
    nameEn: "Acquisition of financial fixed assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "050000",
    nazev: "Poskytnuté zálohy na dlouhodobý majetek",
    nameEn: "Provided advance payments on fixed assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "051000",
    nazev: "Poskytnuté zálohy a závdavky na dlouhodobý nehmotný majetek",
    nameEn: "Advance payments and deposits for long-term intangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "052000",
    nazev: "Poskytnuté zálohy a závdavky na dlouhodobý hmotný majetek",
    nameEn: "Advance payments and deposits for long-term tangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "053000",
    nazev: "Poskytnuté zálohy a závdavky na dlouhodobý finanční majetek",
    nameEn: "Advance payments and deposits for long-term financial assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "060000",
    nazev: "Dlouhodobý finanční majetek",
    nameEn: "Financial fixed assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "061000",
    nazev: "Podíly - ovládaná nebo ovládající osoba",
    nameEn: "Shares – controlled or controlling entity",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "062000",
    nazev: "Podíly - podstatný vliv",
    nameEn: "Shares in accounting units with substantial influence",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "063000",
    nazev: "Ostatní dlouhodobé cenné papíry a podíly",
    nameEn: "Other securities and ownership interests",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "065000",
    nazev: "Dluhové cenné papíry držené do splatnosti",
    nameEn: "Bonds held to maturity",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "066000",
    nazev: "Zápůjčky a úvěry - ovládaná nebo ovládající osoba",
    nameEn: "Loans and credits – controlled or controlling entity",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "067000",
    nazev: "Zápůjčky a úvěry - podstatný vliv",
    nameEn: "Other loans and credits",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "068000",
    nazev: "Zápůjčky a úvěry - ostatní",
    nameEn: "Loans and credits – substantial influence",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "069000",
    nazev: "Jiný dlouhodobý finanční majetek",
    nameEn: "Other long-term financial assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "070000",
    nazev: "Oprávky k dlouhodobému nehmotnému majetku",
    nameEn: "Accumulated depreciation of intangible fixed assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "072000",
    nazev: "Oprávky k nehmot.výsledkům výzkumu a vývoje",
    nameEn:
      "Accumulated amortization on intangible research and development results",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "073000",
    nazev: "Oprávky k softwaru",
    nameEn: "Accumulated amortization on software",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "074000",
    nazev: "Oprávky k ostatním ocenitelným právům",
    nameEn: "Accumulated amortization on appraisable rights",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "075000",
    nazev: "Oprávky ke goodwillu",
    nameEn: "Accumulated amortization on goodwill",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "079000",
    nazev: "Oprávky k ostatnímu dlouhodobému nehmotnému majetku",
    nameEn: "Accumulated amortization on other long-term intangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "080000",
    nazev: "Oprávky k dlouhodobému hmotnému majetku",
    nameEn: "Accumulated depreciation of tangible fixed assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "081000",
    nazev: "Oprávky ke stavbám",
    nameEn: "Accumulated amortization on buildings, halls and structures",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "082000",
    nazev: "Oprávky k hmotným movitým věcem a jejich souborům",
    nameEn:
      "Accumulated amortization for tangible movable assets and their sets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "085000",
    nazev: "Oprávky k pěstitelským celkům trvalých porostů",
    nameEn: "Accumulated amortization on perennial crops",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "086000",
    nazev: "Oprávky k dospělým zvířatům a jejich skupinám",
    nameEn: "Accumulated amortization on breeding and draught animals",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "089000",
    nazev: "Oprávky k jinému dlouhodobému hmotnému majetku",
    nameEn: "Accumulated amortization on other long-term tangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "090000",
    nazev: "Opravné položky k dlouhodobému majetku",
    nameEn: "Allowances against fixed assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "091000",
    nazev: "Opravná položka k dlouhodobému nehmotnému majetku",
    nameEn: "Allowances on long-term intangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "092000",
    nazev: "Opravná položka k dlouhodobému hmotnému majetku",
    nameEn: "Allowances on long-term tangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "093000",
    nazev: "Opravná položka k dlouhodobému nedokončenému nehmotnému majetku",
    nameEn: "Allowances on long-term incomplete intangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "094000",
    nazev: "Opravná položka k dlouhodobému nedokončenému hmotnému majetku",
    nameEn: "Allowances on long-term incomplete tangible assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "095000",
    nazev:
      "Opravná položka k poskytnutým zálohám a závdavkům na dlouhodobý majetek",
    nameEn: "Allowances on advance payments for long-term assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "096000",
    nazev: "Opravná položka k dlouhodobému finančnímu majetku",
    nameEn: "Allowances on long-term financial assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "097000",
    nazev: "Oceňovací rozdíl k nabytému majetku",
    nameEn: "Valuation difference on acquired assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "098000",
    nazev: "Oprávky k oceňovacímu rozdílu k nabytému majetku",
    nameEn:
      "Accumulated amortization on valuation difference on acquired assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "110000",
    nazev: "Materiál",
    nameEn: "Material",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "111000",
    nazev: "Pořízení materiálu",
    nameEn: "Acquisition of material",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "112000",
    nazev: "Materiál na skladě",
    nameEn: "Material in store",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "119000",
    nazev: "Materiál na cestě",
    nameEn: "Material in transit",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "120000",
    nazev: "Zásoby vlastní činnosti",
    nameEn: "Reserves from own operation",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "121000",
    nazev: "Nedokončená výroba",
    nameEn: "Work-in-progress",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "122000",
    nazev: "Polotovary vlastní výroby",
    nameEn: "Semi-finished products",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "123000",
    nazev: "Výrobky",
    nameEn: "Finished products",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "124000",
    nazev: "Mladá a ostatní zvířata a jejich skupiny",
    nameEn: "Animals",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "130000",
    nazev: "Zboží",
    nameEn: "Goods",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "131000",
    nazev: "Pořízení zboží",
    nameEn: "Acquired merchandise",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "132000",
    nazev: "Zboží na skladě a v prodejnách",
    nameEn: "Merchandise in store and in retail shops",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "139000",
    nazev: "Zboží na cestě",
    nameEn: "Merchandise in transit",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "150000",
    nazev: "Poskytnuté zálohy na zásoby",
    nameEn: "Granted advances on reserves",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "151000",
    nazev: "Poskytnuté zálohy a závdavky na materiál",
    nameEn: "Advance payments and deposits for material",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "152000",
    nazev: "Poskytnuté zálohy a závdavky na zvířata",
    nameEn: "Advance payments and deposits for animals",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "153000",
    nazev: "Poskytnuté zálohy a závdavky na zboží",
    nameEn: "Advance payments and deposits for merchandise",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "190000",
    nazev: "Opravné položky z zásobám",
    nameEn: "Allowances against reserves",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "191000",
    nazev: "Opravná položka k materiálu",
    nameEn: "Allowances on material",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "192000",
    nazev: "Opravná položka k nedokončené výrobě",
    nameEn: "Allowances on work-in-progress",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "193000",
    nazev: "Opravná položka k polotovarům vlastní výroby",
    nameEn: "Allowances on semi-finished products",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "194000",
    nazev: "Opravná položka k výrobkům",
    nameEn: "Allowances on finished products",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "195000",
    nazev: "Opravná položka k mladým a ostatním zvířatům a jejich skupinám",
    nameEn: "Allowances on animals",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "196000",
    nazev: "Opravná položka ke zboží",
    nameEn: "Allowances on merchandise",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "197000",
    nazev: "Opravná položka k zálohám a závdavkům na materiál",
    nameEn: "Allowances on advance payments and deposits for material",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "198000",
    nazev: "Opravná položka k zálohám a závdavkům na zboží",
    nameEn: "Allowances on advance payments and deposits for merchandise",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "199000",
    nazev: "Opravná položka k zálohám a závdavkům na zvířata",
    nameEn: "Allowances on advance payments and deposits for animals",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "210000",
    nazev: "Peněžní prostředky v pokladně",
    nameEn: "Financial resources in cash",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "211000",
    nazev: "Pokladna",
    nameEn: "Cash",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "213000",
    nazev: "Ceniny",
    nameEn: "Stamps and vouchers",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "220000",
    nazev: "Peněžní prostředky na účtech",
    nameEn: "Financial resources on accounts",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "221000",
    nazev: "Peněžní prostředky na účtech",
    nameEn: "Financial accounts",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "221001",
    nazev: "Bankovní účet CZK",
    nameEn: "Financial accounts",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "230000",
    nazev: "Krátkodobé úvěry",
    nameEn: "Short-term loans",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "231000",
    nazev: "Krátkodobé závazky k úvěrovým institucím",
    nameEn: "Short-term bank credits",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "232000",
    nazev: "Eskontní úvěry",
    nameEn: "Credits for discounted securities",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "233000",
    nazev: "Krátkodobé úvěry od nebankovních institucí",
    nameEn: "Short-term loans from non-banking institutions",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "240000",
    nazev: "Krátkodobé finanční výpomoci",
    nameEn: "Short-term financial aid",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "241000",
    nazev: "Emitované krátkodobé dluhopisy",
    nameEn: "Issued short-term bonds",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "249000",
    nazev: "Ostatní krátkodobé finanční výpomoci",
    nameEn: "Other short-term financial assistance",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "250000",
    nazev: "Krátkodobý finanční majetek",
    nameEn: "Short-term financial assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "251000",
    nazev: "Majetkové cenné papíry k obchodování",
    nameEn: "Shares and similar securities",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "252000",
    nazev: "Vlastní podíly",
    nameEn: "Own shares",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "253000",
    nazev: "Dluhové cenné papíry k obchodování",
    nameEn: "Bonds, debentures and similar securities",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "254000",
    nazev: "Podíly - ovládaná nebo ovládající osoba",
    nameEn: "Shares – controlled or controlling entity",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "255000",
    nazev: "Vlastní dluhopisy",
    nameEn: "Own bonds",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "256000",
    nazev:
      "Dluhové cenné papíry se splatností do jednoho roku držené do splatnosti",
    nameEn: "Bonds with maturity of 1 year or less held until maturity",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "257000",
    nazev: "Ostatní cenné papíry",
    nameEn: "Other securities",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "259000",
    nazev: "Pořizování krátkodobého finančního majetku",
    nameEn: "Acquisition of short-term financial assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "260000",
    nazev: "Převody mezi finančními účty",
    nameEn: "Transfers between financial accounts",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "261000",
    nazev: "Peníze na cestě",
    nameEn: "Cash in transit",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "290000",
    nazev: "Opravné položky ke krátkodobému finančnímu majetku",
    nameEn: "Allowances against short-term financial assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "291000",
    nazev: "Opravná položka ke krátkodobému finančnímu majetku",
    nameEn: "Allowances on short-term financial assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "310000",
    nazev: "Pohledávky (krátkodobé i dlouhodobé)",
    nameEn: "Receivables (short-term and long-term)",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "311000",
    nazev: "Pohledávky z obchodních vztahů",
    nameEn: "Receivables from business relationships",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "312000",
    nazev: "Směnky k inkasu",
    nameEn: "Bills for collection",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "313000",
    nazev: "Pohledávky za eskontované cenné papíry",
    nameEn: "Receivables from discounted securities",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "314000",
    nazev: "Poskytnuté zálohy a závdavky - dlouhodobé a krátkodobé",
    nameEn: "Advance payments and deposits - long-term and short-term",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "315000",
    nazev: "Ostatní pohledávky",
    nameEn: "Other receivables",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "320000",
    nazev: "Závazky (krátkodobé)",
    nameEn: "Liabilities (short-term)",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "321000",
    nazev: "Dluhy z obchodních vztahů",
    nameEn: "Debts from business relationships",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "322000",
    nazev: "Směnky k úhradě",
    nameEn: "Mature bills of exchange",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "324000",
    nazev: "Přijaté provozní zálohy a závdavky",
    nameEn: "Received operation advance payments and deposits",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "325000",
    nazev: "Ostatní dluhy",
    nameEn: "Other debts",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "330000",
    nazev: "Zúčtování se zaměstnanci a institucemi",
    nameEn: "Settlement with employees and institutions",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "331000",
    nazev: "Zaměstnanci",
    nameEn: "Employees",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "333000",
    nazev: "Ostatní dluhy vůči zaměstnancům",
    nameEn: "Other debts towards employees",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "335000",
    nazev: "Pohledávky za zaměstnanci",
    nameEn: "Receivables from employees",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "336000",
    nazev: "Zúčtování s institucemi soc. zabezpečení a zdrav. pojištění",
    nameEn:
      "Settlement with social security and health insurance institutions ",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "340000",
    nazev: "Zúčtování daní a dotací",
    nameEn: "Settlement of taxes and subsidies",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "341000",
    nazev: "Daň z příjmů",
    nameEn: "Income tax",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "342000",
    nazev: "Ostatní přímé daně",
    nameEn: "Other direct taxes",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "343000",
    nazev: "Daň z přidané hodnoty",
    nameEn: "Value added tax",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "345000",
    nazev: "Ostatní daně a poplatky",
    nameEn: "Other taxes and fees",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "346000",
    nazev: "Dotace ze státního rozpočtu",
    nameEn: "Funding from state budget",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "347000",
    nazev: "Ostatní dotace",
    nameEn: "Other funding",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "350000",
    nazev: "Pohledávky za společníky",
    nameEn: "Receivables from partners",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "351000",
    nazev: "Pohledávky - ovládaná nebo ovládající osoba",
    nameEn: "Receivables - controlled or controlling entity",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "352000",
    nazev: "Pohledávky - podstatný vliv",
    nameEn: "Receivables - substantial influence",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "353000",
    nazev: "Pohledávky za upsaný základní kapitál",
    nameEn: "Receivables from subscribed capital",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "354000",
    nazev: "Pohledávky za společníky při úhradě ztráty obchodní korporace",
    nameEn:
      "Receivables from partners when paying a loss of a business corporation",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "355000",
    nazev: "Ostatní pohledávky za společníky obchodní korporace",
    nameEn: "Other receivables from corporation partners",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "358000",
    nazev: "Pohledávky za společníky sdruženými ve společnosti",
    nameEn: "Receivables from associates in the company",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "360000",
    nazev: "Závazky ke společníkům",
    nameEn: "Liabilities towards partners",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "361000",
    nazev: "Dluhy - ovládaná nebo ovládající osoba",
    nameEn: "Debts - controlled or controlling entity",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "362000",
    nazev: "Dluhy - podstatný vliv",
    nameEn: "Debts - substantial influence",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "364000",
    nazev: "Dluhy ke společníkům obchodní korporace při rozdělování zisku",
    nameEn: "Debts towards corporation partners during profit distribution",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "365000",
    nazev: "Ostatní dluhy ke společníkům obchodní korporace",
    nameEn: "Other debts towards corporation partners",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "366000",
    nazev: "Dluhy ke společníkům obchodní korporace ze závislé činnosti",
    nameEn: "Debts towards corporation partners from dependent activities",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "367000",
    nazev: "Dluhy z upsaných nesplacených cenných  papírů a vkladů",
    nameEn: "Debts from subscribed unpaid securities and deposits",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "368000",
    nazev: "Dluhy ke společníkům sdruženým ve společnosti",
    nameEn: "Debts towards associates in the company",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "370000",
    nazev: "Jiné pohledávky a závazky",
    nameEn: "Other receivables and liabilities",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "371000",
    nazev: "Pohledávky z prodeje obchodního závodu",
    nameEn: "Receivables from sale of a plant",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "372000",
    nazev: "Dluhy z koupě obchodního závodu",
    nameEn: "Debts from purchase of a plant",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "373000",
    nazev: "Pohledávky a dluhy z pevných termínových operací",
    nameEn: "Receivables and debts from fixed future operations",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "374000",
    nazev: "Pohledávky z pachtu obchodního závodu",
    nameEn: "Receivables from a plant holding",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "375000",
    nazev: "Pohledávky z emitovaných dluhopisů",
    nameEn: "Receivables from issued bonds",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "376000",
    nazev: "Nakoupené opce",
    nameEn: "Purchased options",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "377000",
    nazev: "Prodané opce",
    nameEn: "Sold options",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "378000",
    nazev: "Jiné pohledávky",
    nameEn: "Other receivables",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "379000",
    nazev: "Jiné dluhy",
    nameEn: "Other debts",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "380000",
    nazev: "Přechodné účty aktiv a pasiv",
    nameEn: "Transitional assets and liabilities accounts",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "381000",
    nazev: "Náklady příštích období",
    nameEn: "Deferred costs",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "382000",
    nazev: "Komplexní náklady příštích období",
    nameEn: "Complex deferred costs",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "383000",
    nazev: "Výdaje příštích období",
    nameEn: "Deferred charges",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "384000",
    nazev: "Výnosy příštích období",
    nameEn: "Accrued revenues",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "385000",
    nazev: "Příjmy příštích období",
    nameEn: "Accrued income",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "388000",
    nazev: "Dohadné účty aktivní",
    nameEn: "Contingent assets",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "389000",
    nazev: "Dohadné účty pasivní",
    nameEn: "Contingent liabilities",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "390000",
    nazev: "Opravná položka k zúčtovacím vztahům a vnitřní zúčtování",
    nameEn: "Allowances against clearing relationships and internal clearing",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "391000",
    nazev: "Opravná položka k pohledávkám",
    nameEn: "Allowances on receivables",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: true,
  },
  {
    ucet: "395000",
    nazev: "Vnitřní zúčtování",
    nameEn: "Internal accounting",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "398000",
    nazev: "Spojovací účet při společnosti",
    nameEn: "Control account in the company",
    druh: "Rozvahový",
    typ: "Aktivní",
    opravkovy: false,
  },
  {
    ucet: "410000",
    nazev: "Základní kapitál a kapitálové fondy",
    nameEn: "Subscribed capital and capital funds",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "411000",
    nazev: "Základní kapitál",
    nameEn: "Capital",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "412000",
    nazev: "Ážio",
    nameEn: "Agio",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "413000",
    nazev: "Ostatní kapitálové fondy",
    nameEn: "Other capital funds",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "414000",
    nazev: "Oceňovací rozdíly z přecenění majetku a dluhů",
    nameEn: "Revaluation differences during revaluation of assets and debts",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "416000",
    nazev: "Rozdíly z ocenění při přeměnách obchodních korporací",
    nameEn: "Differences from valuation during transformations of corporations",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "417000",
    nazev: "Rozdíly z přeměn obchodních korporací",
    nameEn: "Differences from transformation of corporations",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "418000",
    nazev: "Oceňovací rozdíly z přecenění při přeměnách obchodních korporací",
    nameEn: "Revaluation differences during revaluation of assets and debts",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "419000",
    nazev: "Změny základního kapitálu",
    nameEn: "Changes of registered capital",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "420000",
    nazev: "Fondy ze zisku a převedené výsledky hospodaření",
    nameEn: "Revenue fund and transferred profit or loss",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "421000",
    nazev: "Rezervní fond",
    nameEn: "Reserve fund",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "422000",
    nazev: "Nedělitelný fond",
    nameEn: "Indivisible fund",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "423000",
    nazev: "Statutární fondy",
    nameEn: "Statutory funds",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "426000",
    nazev: "Jiný výsledek hospodaření minulých let",
    nameEn: "Other profit or loss from last years",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "427000",
    nazev: "Ostatní fondy",
    nameEn: "Other funds",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "428000",
    nazev: "Nerozdělený zisk minulých let",
    nameEn: "Undistributed profit from last years",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "429000",
    nazev: "Neuhrazená ztráta minulých let",
    nameEn: "Undistributed loss from last years",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "430000",
    nazev: "Výsledek hospodaření",
    nameEn: "Profit or loss",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "431000",
    nazev: "Výsledek hospodaření ve schvalovacím řízení",
    nameEn: "Loss or profit in approval procedure",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "432000",
    nazev: "Zálohy na podíly na zisku",
    nameEn: "Advance payments for profit shares",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "450000",
    nazev: "Rezervy",
    nameEn: "Reserves",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "451000",
    nazev: "Rezervy podle zvláštních právních předpisů",
    nameEn: "Reserves in accordance with special legal regulations",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "452000",
    nazev: "Rezerva na důchody a podobné závazky",
    nameEn: "Reserves for pensions and similar liabilities",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "453000",
    nazev: "Rezerva na daň z příjmů",
    nameEn: "Reserve for income tax",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "459000",
    nazev: "Ostatní rezervy",
    nameEn: "Other reserves",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "460000",
    nazev: "Dlouhodobé závazky k úvěrovým institucím",
    nameEn: "Long-term liabilities towards credit institutions",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "461000",
    nazev: "Dlouhodobé závazky k úvěrovým institucím",
    nameEn: "Bank loans",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "462000",
    nazev: "Úvěry od nebankovních institucí",
    nameEn: "Loans from non-banking institutions",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "470000",
    nazev: "Dlouhodobé závazky",
    nameEn: "Long-term liabilities",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "471000",
    nazev: "Dlouhodobé dluhy - ovládaná nebo ovládající osoba",
    nameEn: "Long-term debts - controlled or controlling entity",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "472000",
    nazev: "Dlouhodobé dluhy - podstatný vliv",
    nameEn: "Long-term liabilities - significant influence",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "473000",
    nazev: "Emitované dluhopisy",
    nameEn: "Issued bonds",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "474000",
    nazev: "Dluhy z pachtu obchodního závodu",
    nameEn: "Debts from plant holding",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "475000",
    nazev: "Dlouhodobé přijaté zálohy a závdavky",
    nameEn: "Long-term accepted advance payments and deposits",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "478000",
    nazev: "Dlouhodobé směnky k úhradě",
    nameEn: "Long-term mature bills of exchange",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "479000",
    nazev: "Jiné dlouhodobé dluhy",
    nameEn: "Other long-term debts",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "480000",
    nazev: "Odložený daňový závazek a pohledávka",
    nameEn: "Deferred tax liability and receivable",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "481000",
    nazev: "Odložený daňový dluh a pohledávka",
    nameEn: "Deferred tax debt and receivable",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "490000",
    nazev: "Individuální podnikatel",
    nameEn: "Individual entrepreneur",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "491000",
    nazev: "Účet individuálního podnikatele",
    nameEn: "Individual entrepreneur's account",
    druh: "Rozvahový",
    typ: "Pasivní",
    opravkovy: false,
  },
  {
    ucet: "500000",
    nazev: "Spotřebované nákupy",
    nameEn: "Expended purchases",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "501000",
    nazev: "Spotřeba materiálu",
    nameEn: "Consumption of material",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "502000",
    nazev: "Spotřeba energie",
    nameEn: "Consumption of energy",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "503000",
    nazev: "Spotřeba ostatních neskladovatelných dodávek",
    nameEn: "Consumption of other unstored deliveries",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "504000",
    nazev: "Prodané zboží",
    nameEn: "Sold merchandise",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "510000",
    nazev: "Služby",
    nameEn: "Services",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "511000",
    nazev: "Opravy a udržování",
    nameEn: "Repairs and maintenance",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "512000",
    nazev: "Cestovné",
    nameEn: "Travel expenses",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "513000",
    nazev: "Náklady na reprezentaci",
    nameEn: "Representation costs",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "518000",
    nazev: "Ostatní služby",
    nameEn: "Other services",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "520000",
    nazev: "Osobní náklady",
    nameEn: "Personal costs",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "521000",
    nazev: "Mzdové náklady",
    nameEn: "Wages and salaries",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "522000",
    nazev: "Příjmy společníků obchodní korporace ze závislé činnosti",
    nameEn: "Employment income of corporation partners ",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "523000",
    nazev: "Odměny členům orgánů obchodní korporace",
    nameEn: "Remuneration of members of corporation bodies",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "524000",
    nazev: "Zákonné sociální a zdravotní pojištění",
    nameEn: "Social security and health insurance",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "525000",
    nazev: "Ostatní sociální pojištění",
    nameEn: "Other social security ",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "526000",
    nazev: "Sociální náklady individuálního podnikatele",
    nameEn: "Social security expenses of an individual entrepreneur",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "527000",
    nazev: "Zákonné sociální náklady",
    nameEn: "Social security expenses",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "528000",
    nazev: "Ostatní sociální náklady",
    nameEn: "Other social security expenses",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "530000",
    nazev: "Daně a poplatky",
    nameEn: "Taxes and fees",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "531000",
    nazev: "Daň silniční",
    nameEn: "Road tax",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "532000",
    nazev: "Daň z nemovitých věcí",
    nameEn: "Real estate tax",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "538000",
    nazev: "Ostatní daně a poplatky",
    nameEn: "Other taxes and fees",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "540000",
    nazev: "Jiné provozní náklady",
    nameEn: "Other operating costs",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "541000",
    nazev: "Zůstatková cena prodaného dlouhodob. nehmot. a hmot. majetku",
    nameEn:
      "Depreciated value of sold long-term tangible and intangible assets",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "542000",
    nazev: "Prodaný materiál",
    nameEn: "Sold material",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "543000",
    nazev: "Dary",
    nameEn: "Gifts",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "544000",
    nazev: "Smluvní pokuty a úroky z prodlení",
    nameEn: "Contractual penalties and interests on late payments",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "545000",
    nazev: "Ostatní pokuty a penále",
    nameEn: "Other penalties and fines",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "546000",
    nazev: "Odpis pohledávky",
    nameEn: "Depreciation of receivable",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "547000",
    nazev: "Mimořádné provozní náklady",
    nameEn: "Exceptional operational costs",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "548000",
    nazev: "Jiné provozní náklady",
    nameEn: "Other operating costs",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "549000",
    nazev: "Manka a škody z provozní činnosti",
    nameEn: "Shortages and operation losses",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "550000",
    nazev:
      "Odpisy, rezervy, komplexní náklady příštích období a opravné položky v provozní oblasti",
    nameEn:
      "Depreciatons, reserves, complex accrued costs and allowances in the operating area",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "551000",
    nazev: "Odpisy dlouhodobého nehmotného a hmotného majetku",
    nameEn: "Depreciation of long-term intangible and tangible assets",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "552000",
    nazev: "Tvorba a zúčtování rezerv podle zvláštních právních předpisů",
    nameEn:
      "Creation and settlement of reserves according to special legal regulations",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "554000",
    nazev: "Tvorba a zúčtování ostatních rezerv",
    nameEn: "Creation and settlement of other reserves",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "555000",
    nazev: "Tvorba a zúčtování komplexních nákladů příštích období",
    nameEn: "Creation and settlement of complex deferred costs",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "557000",
    nazev: "Zúčtování oprávky k oceňovacímu rozdílu k nabytému majetku",
    nameEn:
      "Settlement of accumulated amortization on revaluation difference for acquired assets",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "558000",
    nazev: "Tvorba a zúčtování zákonných opravných položek v provozní činnosti",
    nameEn:
      "Creation and settlement of legal allowances on operation activities",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "559000",
    nazev: "Tvorba a zúčtování ostatních opravných položek v provozní činnosti",
    nameEn: "Creation and settlement of allowance on operation activities",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "560000",
    nazev: "Finanční náklady",
    nameEn: "Financial costs",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "561000",
    nazev: "Prodané cenné papíry a podíly",
    nameEn: "Sold securities and shares",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "562000",
    nazev: "Úroky",
    nameEn: "Interests",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "563000",
    nazev: "Kursové ztráty",
    nameEn: "Exchange rate loss",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "564000",
    nazev: "Náklady z přecenění cenných papírů",
    nameEn: "Costs from revaluation of securities",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "565000",
    nazev: "Mimořádné finanční náklady",
    nameEn: "Exceptional financial costs",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "566000",
    nazev: "Náklady z finančního majetku",
    nameEn: "Costs from revaluation of financial assets",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "567000",
    nazev: "Náklady z derivátových operací",
    nameEn: "Costs from derivative operations",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "568000",
    nazev: "Ostatní finanční náklady",
    nameEn: "Other financial costs",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "569000",
    nazev: "Manka a škody na finančním majetku",
    nameEn: "Shortages and losses on financial assets",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "570000",
    nazev: "Rezervy a opravné položky ve finanční oblasti",
    nameEn: "Reserves and allowances in the financial area",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "574000",
    nazev: "Tvorba a zúčtování finančních rezerv",
    nameEn: "Creation and settlement of financial reserves",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "579000",
    nazev: "Tvorba a zúčtování opravných položek ve finanční činnosti",
    nameEn: "Creation and settlement of allowance on financial activities",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "580000",
    nazev: "Změna stavu zásob vlastní činnosti a aktivace",
    nameEn: "Change of stock from own activities and activation",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "581000",
    nazev: "Změna stavu nedokončené výroby",
    nameEn: "Change in stock of work in progress",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "582000",
    nazev: "Změna stavu polotovarů vlastní výroby",
    nameEn: "Change in stock of own intermediate products",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "583000",
    nazev: "Změna stavu výrobků",
    nameEn: "Change in stock of products",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "584000",
    nazev: "Změna stavu zvířat",
    nameEn: "Change in stock of animals",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "585000",
    nazev: "Aktivace materiálu a zboží",
    nameEn: "Activation of goods and materials",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "586000",
    nazev: "Aktivace vnitropodnikových služeb",
    nameEn: "Activation of in-house services",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "587000",
    nazev: "Aktivace dlouhodobého nehmotného majetku",
    nameEn: "Activation of long-term intangible assets",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "588000",
    nazev: "Aktivace dlouhodobého hmotného majetku",
    nameEn: "Activation of long-term tangible assets",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "590000",
    nazev: "Daně z příjmů, převodové účty a rezerva na daň z příjmů",
    nameEn: "Income tax, transfer account and income tax reserve",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "591000",
    nazev: "Daň z příjmů - splatná",
    nameEn: "Income tax – payable",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "592000",
    nazev: "Daň z příjmů - odložená",
    nameEn: "Income tax – deferred",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "595000",
    nazev: "Dodatečné odvody daně z příjmů",
    nameEn: "Additional income tax returns",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "596000",
    nazev:
      "Převod podílu na výsledku hospodaření společníkům obchodní korporace",
    nameEn: "Transfer of profit/loss share to corporation partners",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "597000",
    nazev: "Převod provozních nákladů",
    nameEn: "Transfer of operational costs",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "598000",
    nazev: "Převod finančních nákladů",
    nameEn: "Transfer of financial costs",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "599000",
    nazev: "Tvorba a zúčtování rezervy na daň z příjmů",
    nameEn: "Creation and settlement of income tax reserve",
    druh: "Výsledovkový",
    typ: "Nákladový",
    opravkovy: false,
  },
  {
    ucet: "600000",
    nazev: "Tržby za vlastní výkony a zboží",
    nameEn: "Revenues from own services and goods",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "601000",
    nazev: "Tržby za vlastní výrobky",
    nameEn: "Revenues from production",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "602000",
    nazev: "Tržby z prodeje služeb",
    nameEn: "Revenues from sold services",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "604000",
    nazev: "Tržby za zboží",
    nameEn: "Revenues from merchandise",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "640000",
    nazev: "Jiné provozní výnosy",
    nameEn: "Other operating income",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "641000",
    nazev: "Tržby z prodeje dlouhodobého nehmotného a hmotného majetku",
    nameEn: "Revenues from sale of long-term intangible and tangible assets",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "642000",
    nazev: "Tržby z prodeje materiálu",
    nameEn: "Revenues from sale of material",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "643000",
    nazev: "Přijaté dary v provozní oblasti",
    nameEn: "Donations received from the operating area",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "644000",
    nazev: "Smluvní pokuty a úroky z prodlení",
    nameEn: "Contractual penalties and interests on late payments",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "646000",
    nazev: "Výnosy z odepsaných pohledávek",
    nameEn: "Yield from depreciated receivables",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "648000",
    nazev: "Jiné provozní výnosy",
    nameEn: "Other operating costs",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "649000",
    nazev: "Mimořádné provozní výnosy",
    nameEn: "Exceptional operational revenues",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "660000",
    nazev: "Finanční výnosy",
    nameEn: "Financial income",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "661000",
    nazev: "Tržby z prodeje cenných papírů a podílů",
    nameEn: "Revenues from sale of securities and shares",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "662000",
    nazev: "Úroky",
    nameEn: "Interests",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "663000",
    nazev: "Kursové zisky",
    nameEn: "Exchange rate profit",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "664000",
    nazev: "Výnosy z přecenění cenných papírů",
    nameEn: "Revenues from revaluation of securities",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "665000",
    nazev: "Výnosy z dlouhodobého finančního majetku",
    nameEn: "Revenues from long-term financial assets",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "666000",
    nazev: "Výnosy z krátkodobého finančního majetku",
    nameEn: "Revenues from short-term financial assets",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "667000",
    nazev: "Výnosy z derivátových operací",
    nameEn: "Revenues from derivative operations",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "668000",
    nazev: "Ostatní finanční výnosy",
    nameEn: "Other financial revenues",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "669000",
    nazev: "Mimořádné finanční výnosy",
    nameEn: "Exceptional financial revenues",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "690000",
    nazev: "Převodové účty",
    nameEn: "Transfer accounts",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "697000",
    nazev: "Převod provozních výnosů",
    nameEn: "Transfer of operational revenues",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "698000",
    nazev: "Převod finančních výnosů",
    nameEn: "Transfer of financial revenues",
    druh: "Výsledovkový",
    typ: "Výnosový",
    opravkovy: false,
  },
  {
    ucet: "700000",
    nazev: "Účty rozvažné",
    nameEn: "Balance accounts",
    druh: "Závěrkový",
    typ: "",
    opravkovy: false,
  },
  {
    ucet: "701000",
    nazev: "Počáteční účet rozvažný",
    nameEn: "Starting balance account",
    druh: "Závěrkový",
    typ: "",
    opravkovy: false,
  },
  {
    ucet: "702000",
    nazev: "Konečný účet rozvažný",
    nameEn: "Final balance account",
    druh: "Závěrkový",
    typ: "",
    opravkovy: false,
  },
  {
    ucet: "710000",
    nazev: "Účet zisků a ztrát",
    nameEn: "Profit and loss account",
    druh: "Závěrkový",
    typ: "",
    opravkovy: false,
  },
]
