// ROZVAHA (balance sheet) line taxonomy — plný rozsah, per vyhláška č. 500/2002
// Sb., příloha 1 (current podnikatelé form). No org or personal data — only the
// statutory řádek structure, formulas, and rendering flags.
//
// Two statements: ROZVAHA_AKTIVA (brutto / korekce / netto / minulé) and
// ROZVAHA_PASIVA (běžné / minulé). Engine rules live in ../_lib/types.ts:
//   - kind "calc"  -> value = signed sum of `formula` refs in the SAME column.
//   - kind "input" -> user-entered leaf (netto still auto-derived on aktiva).
//   - aktiva netto is ALWAYS derived (netto = brutto + korekce); `formula` is
//     supplied for brutto/korekce/minulé aggregation and ignored for netto.
//   - korekceNA -> aktiva korekce cell shows "x" (not applicable, adds 0).
//
// Structural note: the reference form used for the FY2025 ground-truth check
// numbers A.V at řádek 022, which requires A.IV. Výsledek hospodaření minulých
// let to carry three sub-items (A.IV.1..A.IV.3). That numbering is reproduced
// verbatim here so every stated řádek lands on the expected line.
import type { VykazStatement } from "../_lib/types"

export const ROZVAHA_AKTIVA: VykazStatement = {
  id: "rozvaha-aktiva",
  heading: "ROZVAHA",
  columns: ["brutto", "korekce", "netto", "minule"],
  lines: [
    {
      ozn: "",
      rada: "001",
      text: "AKTIVA CELKEM",
      kind: "calc",
      formula: "002+003+037+074",
      bold: true,
      indent: 0,
      inZkraceny: true,
    },
    {
      ozn: "A.",
      rada: "002",
      text: "Pohledávky za upsaný základní kapitál",
      kind: "input",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "B.",
      rada: "003",
      text: "Stálá aktiva",
      kind: "calc",
      formula: "004+014+027",
      bold: true,
      indent: 0,
      inZkraceny: true,
    },
    {
      ozn: "B.I.",
      rada: "004",
      text: "Dlouhodobý nehmotný majetek",
      kind: "calc",
      formula: "005+006+009+010+011",
      bold: true,
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "B.I.1.",
      rada: "005",
      text: "Nehmotné výsledky vývoje",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.I.2.",
      rada: "006",
      text: "Ocenitelná práva",
      kind: "calc",
      formula: "007+008",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.I.2.1.",
      rada: "007",
      text: "Software",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.I.2.2.",
      rada: "008",
      text: "Ostatní ocenitelná práva",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.I.3.",
      rada: "009",
      text: "Goodwill",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.I.4.",
      rada: "010",
      text: "Ostatní dlouhodobý nehmotný majetek",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.I.5.",
      rada: "011",
      text: "Poskytnuté zálohy na dlouhodobý nehmotný majetek a nedokončený dlouhodobý nehmotný majetek",
      kind: "calc",
      formula: "012+013",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.I.5.1.",
      rada: "012",
      text: "Poskytnuté zálohy na dlouhodobý nehmotný majetek",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.I.5.2.",
      rada: "013",
      text: "Nedokončený dlouhodobý nehmotný majetek",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.II.",
      rada: "014",
      text: "Dlouhodobý hmotný majetek",
      kind: "calc",
      formula: "015+018+019+020+024",
      bold: true,
      indent: 1,
      inZkraceny: true,
    },
    {
      ozn: "B.II.1.",
      rada: "015",
      text: "Pozemky a stavby",
      kind: "calc",
      formula: "016+017",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.II.1.1.",
      rada: "016",
      text: "Pozemky",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.II.1.2.",
      rada: "017",
      text: "Stavby",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.II.2.",
      rada: "018",
      text: "Hmotné movité věci a jejich soubory",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.II.3.",
      rada: "019",
      text: "Oceňovací rozdíl k nabytému majetku",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.II.4.",
      rada: "020",
      text: "Ostatní dlouhodobý hmotný majetek",
      kind: "calc",
      formula: "021+022+023",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.II.4.1.",
      rada: "021",
      text: "Pěstitelské celky trvalých porostů",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.II.4.2.",
      rada: "022",
      text: "Dospělá zvířata a jejich skupiny",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.II.4.3.",
      rada: "023",
      text: "Jiný dlouhodobý hmotný majetek",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.II.5.",
      rada: "024",
      text: "Poskytnuté zálohy na dlouhodobý hmotný majetek a nedokončený dlouhodobý hmotný majetek",
      kind: "calc",
      formula: "025+026",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.II.5.1.",
      rada: "025",
      text: "Poskytnuté zálohy na dlouhodobý hmotný majetek",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.II.5.2.",
      rada: "026",
      text: "Nedokončený dlouhodobý hmotný majetek",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.III.",
      rada: "027",
      text: "Dlouhodobý finanční majetek",
      kind: "calc",
      formula: "028+029+030+031+032+033+034",
      bold: true,
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "B.III.1.",
      rada: "028",
      text: "Podíly - ovládaná nebo ovládající osoba",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.III.2.",
      rada: "029",
      text: "Zápůjčky a úvěry - ovládaná nebo ovládající osoba",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.III.3.",
      rada: "030",
      text: "Podíly - podstatný vliv",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.III.4.",
      rada: "031",
      text: "Zápůjčky a úvěry - podstatný vliv",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.III.5.",
      rada: "032",
      text: "Ostatní dlouhodobé cenné papíry a podíly",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.III.6.",
      rada: "033",
      text: "Zápůjčky a úvěry - ostatní",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.III.7.",
      rada: "034",
      text: "Ostatní dlouhodobý finanční majetek",
      kind: "calc",
      formula: "035+036",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "B.III.7.1.",
      rada: "035",
      text: "Jiný dlouhodobý finanční majetek",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "B.III.7.2.",
      rada: "036",
      text: "Poskytnuté zálohy na dlouhodobý finanční majetek",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.",
      rada: "037",
      text: "Oběžná aktiva",
      kind: "calc",
      formula: "038+046+068+071",
      bold: true,
      indent: 0,
      inZkraceny: true,
    },
    {
      ozn: "C.I.",
      rada: "038",
      text: "Zásoby",
      kind: "calc",
      formula: "039+040+041+044+045",
      bold: true,
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "C.I.1.",
      rada: "039",
      text: "Materiál",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.2.",
      rada: "040",
      text: "Nedokončená výroba a polotovary",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.3.",
      rada: "041",
      text: "Výrobky a zboží",
      kind: "calc",
      formula: "042+043",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.3.1.",
      rada: "042",
      text: "Výrobky",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.I.3.2.",
      rada: "043",
      text: "Zboží",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.I.4.",
      rada: "044",
      text: "Mladá a ostatní zvířata a jejich skupiny",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.5.",
      rada: "045",
      text: "Poskytnuté zálohy na zásoby",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.II.",
      rada: "046",
      text: "Pohledávky",
      kind: "calc",
      formula: "047+057",
      bold: true,
      indent: 1,
      inZkraceny: true,
    },
    {
      ozn: "C.II.1.",
      rada: "047",
      text: "Dlouhodobé pohledávky",
      kind: "calc",
      formula: "048+049+050+051+052",
      bold: true,
      indent: 2,
      korekceNA: true,
      inZkraceny: true,
    },
    {
      ozn: "C.II.1.1.",
      rada: "048",
      text: "Pohledávky z obchodních vztahů",
      kind: "input",
      indent: 3,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "C.II.1.2.",
      rada: "049",
      text: "Pohledávky - ovládaná nebo ovládající osoba",
      kind: "input",
      indent: 3,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "C.II.1.3.",
      rada: "050",
      text: "Pohledávky - podstatný vliv",
      kind: "input",
      indent: 3,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "C.II.1.4.",
      rada: "051",
      text: "Odložená daňová pohledávka",
      kind: "input",
      indent: 3,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "C.II.1.5.",
      rada: "052",
      text: "Pohledávky - ostatní",
      kind: "calc",
      formula: "053+054+055+056",
      bold: true,
      indent: 3,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "C.II.1.5.1.",
      rada: "053",
      text: "Pohledávky za společníky",
      kind: "input",
      indent: 4,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "C.II.1.5.2.",
      rada: "054",
      text: "Dlouhodobé poskytnuté zálohy",
      kind: "input",
      indent: 4,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "C.II.1.5.3.",
      rada: "055",
      text: "Dohadné účty aktivní",
      kind: "input",
      indent: 4,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "C.II.1.5.4.",
      rada: "056",
      text: "Jiné pohledávky",
      kind: "input",
      indent: 4,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "C.II.2.",
      rada: "057",
      text: "Krátkodobé pohledávky",
      kind: "calc",
      formula: "058+059+060+061",
      bold: true,
      indent: 2,
      inZkraceny: true,
    },
    {
      ozn: "C.II.2.1.",
      rada: "058",
      text: "Pohledávky z obchodních vztahů",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.2.2.",
      rada: "059",
      text: "Pohledávky - ovládaná nebo ovládající osoba",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.2.3.",
      rada: "060",
      text: "Pohledávky - podstatný vliv",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.2.4.",
      rada: "061",
      text: "Pohledávky - ostatní",
      kind: "calc",
      formula: "062+063+064+065+066+067",
      bold: true,
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.2.4.1.",
      rada: "062",
      text: "Pohledávky za společníky",
      kind: "input",
      indent: 4,
      inZkraceny: false,
    },
    {
      ozn: "C.II.2.4.2.",
      rada: "063",
      text: "Sociální zabezpečení a zdravotní pojištění",
      kind: "input",
      indent: 4,
      inZkraceny: false,
    },
    {
      ozn: "C.II.2.4.3.",
      rada: "064",
      text: "Stát - daňové pohledávky",
      kind: "input",
      indent: 4,
      inZkraceny: false,
    },
    {
      ozn: "C.II.2.4.4.",
      rada: "065",
      text: "Krátkodobé poskytnuté zálohy",
      kind: "input",
      indent: 4,
      inZkraceny: false,
    },
    {
      ozn: "C.II.2.4.5.",
      rada: "066",
      text: "Dohadné účty aktivní",
      kind: "input",
      indent: 4,
      inZkraceny: false,
    },
    {
      ozn: "C.II.2.4.6.",
      rada: "067",
      text: "Jiné pohledávky",
      kind: "input",
      indent: 4,
      inZkraceny: false,
    },
    {
      ozn: "C.III.",
      rada: "068",
      text: "Krátkodobý finanční majetek",
      kind: "calc",
      formula: "069+070",
      bold: true,
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "C.III.1.",
      rada: "069",
      text: "Podíly - ovládaná nebo ovládající osoba",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.III.2.",
      rada: "070",
      text: "Ostatní krátkodobý finanční majetek",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.IV.",
      rada: "071",
      text: "Peněžní prostředky",
      kind: "calc",
      formula: "072+073",
      bold: true,
      indent: 1,
      korekceNA: true,
      inZkraceny: true,
    },
    {
      ozn: "C.IV.1.",
      rada: "072",
      text: "Peněžní prostředky v pokladně",
      kind: "input",
      indent: 2,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "C.IV.2.",
      rada: "073",
      text: "Peněžní prostředky na účtech",
      kind: "input",
      indent: 2,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "D.",
      rada: "074",
      text: "Časové rozlišení aktiv",
      kind: "calc",
      formula: "075+076+077",
      bold: true,
      indent: 0,
      korekceNA: true,
      inZkraceny: true,
    },
    {
      ozn: "D.1.",
      rada: "075",
      text: "Náklady příštích období",
      kind: "input",
      indent: 1,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "D.2.",
      rada: "076",
      text: "Komplexní náklady příštích období",
      kind: "input",
      indent: 1,
      korekceNA: true,
      inZkraceny: false,
    },
    {
      ozn: "D.3.",
      rada: "077",
      text: "Příjmy příštích období",
      kind: "input",
      indent: 1,
      korekceNA: true,
      inZkraceny: false,
    },
  ],
}

export const ROZVAHA_PASIVA: VykazStatement = {
  id: "rozvaha-pasiva",
  heading: "ROZVAHA",
  columns: ["bezne", "minule"],
  lines: [
    {
      ozn: "",
      rada: "001",
      text: "PASIVA CELKEM",
      kind: "calc",
      formula: "002+024+064",
      bold: true,
      indent: 0,
      inZkraceny: true,
    },
    {
      ozn: "A.",
      rada: "002",
      text: "Vlastní kapitál",
      kind: "calc",
      formula: "003+007+015+018+022+023",
      bold: true,
      indent: 0,
      inZkraceny: true,
    },
    {
      ozn: "A.I.",
      rada: "003",
      text: "Základní kapitál",
      kind: "calc",
      formula: "004+005+006",
      bold: true,
      indent: 1,
      inZkraceny: true,
    },
    {
      ozn: "A.I.1.",
      rada: "004",
      text: "Základní kapitál",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "A.I.2.",
      rada: "005",
      text: "Vlastní podíly (-)",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "A.I.3.",
      rada: "006",
      text: "Změny základního kapitálu (+/-)",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "A.II.",
      rada: "007",
      text: "Ážio a kapitálové fondy",
      kind: "calc",
      formula: "008+009",
      bold: true,
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "A.II.1.",
      rada: "008",
      text: "Ážio",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "A.II.2.",
      rada: "009",
      text: "Kapitálové fondy",
      kind: "calc",
      formula: "010+011+012+013+014",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "A.II.2.1.",
      rada: "010",
      text: "Ostatní kapitálové fondy",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "A.II.2.2.",
      rada: "011",
      text: "Oceňovací rozdíly z přecenění majetku a závazků (+/-)",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "A.II.2.3.",
      rada: "012",
      text: "Oceňovací rozdíly z přecenění při přeměnách obchodních korporací (+/-)",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "A.II.2.4.",
      rada: "013",
      text: "Rozdíly z přeměn obchodních korporací (+/-)",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "A.II.2.5.",
      rada: "014",
      text: "Rozdíly z ocenění při přeměnách obchodních korporací (+/-)",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "A.III.",
      rada: "015",
      text: "Fondy ze zisku",
      kind: "calc",
      formula: "016+017",
      bold: true,
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "A.III.1.",
      rada: "016",
      text: "Ostatní rezervní fondy",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "A.III.2.",
      rada: "017",
      text: "Statutární a ostatní fondy",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "A.IV.",
      rada: "018",
      text: "Výsledek hospodaření minulých let (+/-)",
      kind: "calc",
      formula: "019+020+021",
      bold: true,
      indent: 1,
      inZkraceny: true,
    },
    {
      ozn: "A.IV.1.",
      rada: "019",
      text: "Nerozdělený zisk minulých let",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "A.IV.2.",
      rada: "020",
      text: "Neuhrazená ztráta minulých let (-)",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "A.IV.3.",
      rada: "021",
      text: "Jiný výsledek hospodaření minulých let (+/-)",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "A.V.",
      rada: "022",
      text: "Výsledek hospodaření běžného účetního období (+/-)",
      kind: "input",
      indent: 1,
      inZkraceny: true,
    },
    {
      ozn: "A.VI.",
      rada: "023",
      text: "Rozhodnuto o zálohové výplatě podílu na zisku (-)",
      kind: "input",
      indent: 1,
      inZkraceny: true,
    },
    {
      ozn: "B.+C.",
      rada: "024",
      text: "Cizí zdroje",
      kind: "calc",
      formula: "025+030",
      bold: true,
      indent: 0,
      inZkraceny: true,
    },
    {
      ozn: "B.",
      rada: "025",
      text: "Rezervy",
      kind: "calc",
      formula: "026+027+028+029",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "B.1.",
      rada: "026",
      text: "Rezerva na důchody a podobné závazky",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "B.2.",
      rada: "027",
      text: "Rezerva na daň z příjmů",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "B.3.",
      rada: "028",
      text: "Rezervy podle zvláštních právních předpisů",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "B.4.",
      rada: "029",
      text: "Ostatní rezervy",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "C.",
      rada: "030",
      text: "Závazky",
      kind: "calc",
      formula: "031+046",
      bold: true,
      indent: 0,
      inZkraceny: true,
    },
    {
      ozn: "C.I.",
      rada: "031",
      text: "Dlouhodobé závazky",
      kind: "calc",
      formula: "032+035+036+037+038+039+040+041+042",
      bold: true,
      indent: 1,
      inZkraceny: true,
    },
    {
      ozn: "C.I.1.",
      rada: "032",
      text: "Vydané dluhopisy",
      kind: "calc",
      formula: "033+034",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.1.1.",
      rada: "033",
      text: "Vyměnitelné dluhopisy",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.I.1.2.",
      rada: "034",
      text: "Ostatní dluhopisy",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.I.2.",
      rada: "035",
      text: "Závazky k úvěrovým institucím",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.3.",
      rada: "036",
      text: "Dlouhodobé přijaté zálohy",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.4.",
      rada: "037",
      text: "Závazky z obchodních vztahů",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.5.",
      rada: "038",
      text: "Dlouhodobé směnky k úhradě",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.6.",
      rada: "039",
      text: "Závazky - ovládaná nebo ovládající osoba",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.7.",
      rada: "040",
      text: "Závazky - podstatný vliv",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.8.",
      rada: "041",
      text: "Odložený daňový závazek",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.9.",
      rada: "042",
      text: "Závazky - ostatní",
      kind: "calc",
      formula: "043+044+045",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.I.9.1.",
      rada: "043",
      text: "Závazky ke společníkům",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.I.9.2.",
      rada: "044",
      text: "Dohadné účty pasivní",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.I.9.3.",
      rada: "045",
      text: "Jiné závazky",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.",
      rada: "046",
      text: "Krátkodobé závazky",
      kind: "calc",
      formula: "047+050+051+052+053+054+055+056",
      bold: true,
      indent: 1,
      inZkraceny: true,
    },
    {
      ozn: "C.II.1.",
      rada: "047",
      text: "Vydané dluhopisy",
      kind: "calc",
      formula: "048+049",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.II.1.1.",
      rada: "048",
      text: "Vyměnitelné dluhopisy",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.1.2.",
      rada: "049",
      text: "Ostatní dluhopisy",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.2.",
      rada: "050",
      text: "Závazky k úvěrovým institucím",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.II.3.",
      rada: "051",
      text: "Krátkodobé přijaté zálohy",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.II.4.",
      rada: "052",
      text: "Závazky z obchodních vztahů",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.II.5.",
      rada: "053",
      text: "Krátkodobé směnky k úhradě",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.II.6.",
      rada: "054",
      text: "Závazky - ovládaná nebo ovládající osoba",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.II.7.",
      rada: "055",
      text: "Závazky - podstatný vliv",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.II.8.",
      rada: "056",
      text: "Závazky ostatní",
      kind: "calc",
      formula: "057+058+059+060+061+062+063",
      bold: true,
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "C.II.8.1.",
      rada: "057",
      text: "Závazky ke společníkům",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.8.2.",
      rada: "058",
      text: "Krátkodobé finanční výpomoci",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.8.3.",
      rada: "059",
      text: "Závazky k zaměstnancům",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.8.4.",
      rada: "060",
      text: "Závazky ze sociálního zabezpečení a zdravotního pojištění",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.8.5.",
      rada: "061",
      text: "Stát - daňové závazky a dotace",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.8.6.",
      rada: "062",
      text: "Dohadné účty pasivní",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "C.II.8.7.",
      rada: "063",
      text: "Jiné závazky",
      kind: "input",
      indent: 3,
      inZkraceny: false,
    },
    {
      ozn: "D.",
      rada: "064",
      text: "Časové rozlišení pasiv",
      kind: "calc",
      formula: "065+066",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "D.1.",
      rada: "065",
      text: "Výdaje příštích období",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "D.2.",
      rada: "066",
      text: "Výnosy příštích období",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
  ],
}
