// Výkaz zisku a ztráty (druhové členění), plný rozsah.
// Statutory form per vyhláška č. 500/2002 Sb., příloha č. 2. No org or personal
// data, only the form taxonomy (řádky, označení, formulas). Values are entered
// in the UI and live in VykazValues, never here.
//
// Formula convention (see _lib/types.ts): a calc line's `formula` is a signed
// sum over other lines' `rada` in the SAME column. Leaves are `kind:"input"`.
// The whole form is plný rozsah, so `inZkraceny` is false on every line.
import type { VykazStatement } from "../_lib/types"

export const VZZ: VykazStatement = {
  id: "vzz",
  heading: "VÝKAZ ZISKU A ZTRÁTY",
  columns: ["bezne", "minule"],
  lines: [
    {
      ozn: "I.",
      rada: "001",
      text: "Tržby z prodeje výrobků a služeb",
      kind: "input",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "II.",
      rada: "002",
      text: "Tržby za prodej zboží",
      kind: "input",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "A.",
      rada: "003",
      text: "Výkonová spotřeba",
      kind: "calc",
      formula: "004+005+006",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "A.1.",
      rada: "004",
      text: "Náklady vynaložené na prodané zboží",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "A.2.",
      rada: "005",
      text: "Spotřeba materiálu a energie",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "A.3.",
      rada: "006",
      text: "Služby",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "B.",
      rada: "007",
      text: "Změna stavu zásob vlastní činnosti (+/-)",
      kind: "input",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "C.",
      rada: "008",
      text: "Aktivace (-)",
      kind: "input",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "D.",
      rada: "009",
      text: "Osobní náklady",
      kind: "calc",
      formula: "010+011",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "D.1.",
      rada: "010",
      text: "Mzdové náklady",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "D.2.",
      rada: "011",
      text: "Náklady na sociální zabezpečení, zdravotní pojištění a ostatní náklady",
      kind: "calc",
      formula: "012+013",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "D.2.1.",
      rada: "012",
      text: "Náklady na sociální zabezpečení a zdravotní pojištění",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "D.2.2.",
      rada: "013",
      text: "Ostatní náklady",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "E.",
      rada: "014",
      text: "Úpravy hodnot v provozní oblasti",
      kind: "calc",
      formula: "015+018+019",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "E.1.",
      rada: "015",
      text: "Úpravy hodnot dlouhodobého nehmotného a hmotného majetku",
      kind: "calc",
      formula: "016+017",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "E.1.1.",
      rada: "016",
      text: "Úpravy hodnot dlouhodobého nehmotného a hmotného majetku - trvalé",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "E.1.2.",
      rada: "017",
      text: "Úpravy hodnot dlouhodobého nehmotného a hmotného majetku - dočasné",
      kind: "input",
      indent: 2,
      inZkraceny: false,
    },
    {
      ozn: "E.2.",
      rada: "018",
      text: "Úpravy hodnot zásob",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "E.3.",
      rada: "019",
      text: "Úpravy hodnot pohledávek",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "III.",
      rada: "020",
      text: "Ostatní provozní výnosy",
      kind: "calc",
      formula: "021+022+023",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "III.1.",
      rada: "021",
      text: "Tržby z prodaného dlouhodobého majetku",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "III.2.",
      rada: "022",
      text: "Tržby z prodaného materiálu",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "III.3.",
      rada: "023",
      text: "Jiné provozní výnosy",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "F.",
      rada: "024",
      text: "Ostatní provozní náklady",
      kind: "calc",
      formula: "025+026+027+028+029",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "F.1.",
      rada: "025",
      text: "Zůstatková cena prodaného dlouhodobého majetku",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "F.2.",
      rada: "026",
      text: "Prodaný materiál",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "F.3.",
      rada: "027",
      text: "Daně a poplatky",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "F.4.",
      rada: "028",
      text: "Rezervy v provozní oblasti a komplexní náklady příštích období",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "F.5.",
      rada: "029",
      text: "Jiné provozní náklady",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "*",
      rada: "030",
      text: "Provozní výsledek hospodaření (+/-)",
      kind: "calc",
      formula: "001+002-003-007-008-009-014+020-024",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "IV.",
      rada: "031",
      text: "Výnosy z dlouhodobého finančního majetku - podíly",
      kind: "calc",
      formula: "032+033",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "IV.1.",
      rada: "032",
      text: "Výnosy z podílů - ovládaná nebo ovládající osoba",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "IV.2.",
      rada: "033",
      text: "Ostatní výnosy z podílů",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "G.",
      rada: "034",
      text: "Náklady vynaložené na prodané podíly",
      kind: "input",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "V.",
      rada: "035",
      text: "Výnosy z ostatního dlouhodobého finančního majetku",
      kind: "calc",
      formula: "036+037",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "V.1.",
      rada: "036",
      text: "Výnosy z ostatního dlouhodobého finančního majetku - ovládaná nebo ovládající osoba",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "V.2.",
      rada: "037",
      text: "Ostatní výnosy z ostatního dlouhodobého finančního majetku",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "H.",
      rada: "038",
      text: "Náklady související s ostatním dlouhodobým finančním majetkem",
      kind: "input",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "VI.",
      rada: "039",
      text: "Výnosové úroky a podobné výnosy",
      kind: "calc",
      formula: "040+041",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "VI.1.",
      rada: "040",
      text: "Výnosové úroky a podobné výnosy - ovládaná nebo ovládající osoba",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "VI.2.",
      rada: "041",
      text: "Ostatní výnosové úroky a podobné výnosy",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "I.",
      rada: "042",
      text: "Úpravy hodnot a rezervy ve finanční oblasti",
      kind: "input",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "J.",
      rada: "043",
      text: "Nákladové úroky a podobné náklady",
      kind: "calc",
      formula: "044+045",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "J.1.",
      rada: "044",
      text: "Nákladové úroky a podobné náklady - ovládaná nebo ovládající osoba",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "J.2.",
      rada: "045",
      text: "Ostatní nákladové úroky a podobné náklady",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "VII.",
      rada: "046",
      text: "Ostatní finanční výnosy",
      kind: "input",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "K.",
      rada: "047",
      text: "Ostatní finanční náklady",
      kind: "input",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "*",
      rada: "048",
      text: "Finanční výsledek hospodaření (+/-)",
      kind: "calc",
      formula: "031-034+035-038+039-042-043+046-047",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "**",
      rada: "049",
      text: "Výsledek hospodaření před zdaněním (+/-)",
      kind: "calc",
      formula: "030+048",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "L.",
      rada: "050",
      text: "Daň z příjmů",
      kind: "calc",
      formula: "051+052",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "L.1.",
      rada: "051",
      text: "Daň z příjmů splatná",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "L.2.",
      rada: "052",
      text: "Daň z příjmů odložená (+/-)",
      kind: "input",
      indent: 1,
      inZkraceny: false,
    },
    {
      ozn: "**",
      rada: "053",
      text: "Výsledek hospodaření po zdanění (+/-)",
      kind: "calc",
      formula: "049-050",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "M.",
      rada: "054",
      text: "Převod podílu na výsledku hospodaření společníkům (+/-)",
      kind: "input",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "***",
      rada: "055",
      text: "Výsledek hospodaření za účetní období (+/-)",
      kind: "calc",
      formula: "053-054",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
    {
      ozn: "*",
      rada: "056",
      // FY2025 (§1d ZoÚ + §35 vyhl. 500/2002, effective 1.1.2024): čistý obrat =
      // výnosy z prodeje výrobků, zboží a služeb only (účty 601/602/604 = I.+II.),
      // excluding financial income (VI./VII.) and other operating income (III.).
      // Business-model exceptions (finance-model entities) override manually.
      text: "Čistý obrat za účetní období",
      kind: "calc",
      formula: "001+002",
      bold: true,
      indent: 0,
      inZkraceny: false,
    },
  ],
}
