"use client"

/**
 * Phosphor icon pack. Maps every canonical `IconName` from `../types`
 * to its closest Phosphor equivalent. Phosphor uses different
 * conventions than lucide (`House` not `Home`, `Gear` not `Settings`,
 * `MagnifyingGlass` not `Search`, `Chevron*` → `Caret*`, etc.), so
 * the mapping is explicit.
 *
 * NOTE: `"use client"` is required because `@phosphor-icons/react`
 * calls `React.createContext()` at module top-level — that API is not
 * available in the React RSC runtime. The directive turns this file
 * into a client-only module; server components importing it (e.g.
 * the root layout pulling `IconProvider` via the barrel) get a
 * client reference, not the evaluated module.
 *
 * Lucide ships some icons under two names (`Foo` AND `FooIcon`); both
 * names point to the same Phosphor component here. `Trash2` and
 * `TrashSimple`-style variant mapping is intentional — pick whatever
 * reads closest to lucide's silhouette.
 *
 * If you add a new name to `ICON_NAMES`, this file (and every other
 * pack) MUST add the corresponding entry. `pnpm check:icon-packs`
 * catches drift.
 */
import {
  Archive,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  ArrowsClockwise,
  ArrowsDownUp,
  ArrowsIn,
  ArrowsOut,
  ArrowsOutSimple,
  BatteryFull,
  Bell,
  BookOpen,
  BookOpenText,
  Bookmark,
  Briefcase,
  Buildings,
  Bug,
  Calculator,
  Calendar,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CaretUpDown,
  ChartBar,
  ChatCircle,
  ChatTeardrop,
  Check,
  CheckCircle,
  CheckSquare,
  CircleNotch,
  Clipboard,
  ClockCounterClockwise,
  Code,
  Copy,
  DotsThree,
  Download,
  Envelope,
  Eraser,
  Eye,
  EyeSlash,
  File,
  FileArchive,
  FileAudio,
  FileCode,
  FileImage,
  FileText,
  FileVideo,
  FileXls,
  FolderOpen,
  Funnel,
  FunnelSimpleX,
  Gear,
  GearSix,
  Globe,
  GraduationCap,
  Hash,
  House,
  Info,
  Key,
  Lifebuoy,
  LinkSimple,
  List,
  ListChecks,
  Lock,
  MagnifyingGlass,
  Minus,
  Money,
  Monitor,
  Moon,
  Package,
  Palette,
  PaperPlaneTilt,
  Pencil,
  PiggyBank,
  Plus,
  PlusCircle,
  Presentation,
  Prohibit,
  Pulse,
  Scissors,
  Shield,
  Sidebar,
  SidebarSimple,
  Sparkle,
  SpeakerHigh,
  Square,
  Star,
  Sun,
  Terminal,
  TextAa,
  TextT,
  Trash,
  Tray,
  Trophy,
  Upload,
  User,
  UserPlus,
  Users,
  Warning,
  WifiHigh,
  X,
  XCircle,
  ChartLineUp,
  Folder,
  IdentificationCard,
  Swatches,
  Target,
  BookOpenUser,
  Question,
  Circle,
  UserCircle,
  Keyboard,
  GitPullRequest,
  SquaresFour,
  FlowArrow,
  Sunglasses,
  CreditCard,
} from "@phosphor-icons/react"

import type { IconMap } from "../types"

export const phosphorIcons = {
  Activity: Pulse,
  AlertTriangle: Warning,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRightIcon: ArrowRight,
  ArrowUp,
  ArrowUpDown: ArrowsDownUp,
  ArrowUpRight,
  Award: Trophy, // Phosphor has no "Award" badge; Trophy is the closest semantic.
  Banknote: Money,
  BarChart3: ChartBar,
  BaselineIcon: TextAa,
  Battery: BatteryFull,
  Bell,
  BookmarkIcon: Bookmark,
  BookOpen,
  BookOpenText,
  Box: Package,
  Briefcase,
  Bug,
  Building2: Buildings,
  Calculator,
  CalendarIcon: Calendar,
  Check,
  CheckCircle2: CheckCircle,
  CheckCircle2Icon: CheckCircle,
  CheckIcon: Check,
  CheckSquareIcon: CheckSquare,
  ChevronDown: CaretDown,
  ChevronDownIcon: CaretDown,
  ChevronLeft: CaretLeft,
  ChevronLeftIcon: CaretLeft,
  ChevronRight: CaretRight,
  ChevronRightIcon: CaretRight,
  ChevronUp: CaretUp,
  ChevronUpIcon: CaretUp,
  ChevronsLeft: CaretDoubleLeft,
  ChevronsRight: CaretDoubleRight,
  ChevronsUpDown: CaretUpDown,
  ChevronsUpDownIcon: CaretUpDown,
  CircleCheckIcon: CheckCircle,
  ClipboardIcon: Clipboard,
  Code2: Code,
  Copy,
  CopyIcon: Copy,
  Download,
  Ellipsis: DotsThree,
  EraserIcon: Eraser,
  Eye,
  EyeOff: EyeSlash,
  File,
  FileArchive,
  FileArchiveIcon: FileArchive,
  FileAudio,
  FileAudioIcon: FileAudio,
  FileCodeIcon: FileCode,
  FileCogIcon: File, // Phosphor has no FileCog/FileGear; plain File is more honest than FileLock (encryption ≠ config).
  FileIcon: File,
  FileImage,
  FileSpreadsheet: FileXls,
  FileText,
  FileTextIcon: FileText,
  FileVideo,
  FileVideoIcon: FileVideo,
  FilterIcon: Funnel,
  FilterXIcon: FunnelSimpleX,
  FolderOpen,
  Globe,
  GraduationCap,
  HashIcon: Hash,
  History: ClockCounterClockwise,
  Home: House,
  Inbox: Tray,
  InfoIcon: Info,
  KeyRound: Key,
  LifeBuoy: Lifebuoy,
  LinkIcon: LinkSimple,
  ListChecksIcon: ListChecks,
  ListIcon: List,
  Loader2: CircleNotch,
  Loader2Icon: CircleNotch,
  Lock,
  Mail: Envelope,
  Maximize: ArrowsOut,
  Maximize2: ArrowsOutSimple,
  MaximizeIcon: ArrowsOut,
  MessageCircle: ChatCircle,
  MessageSquare: ChatTeardrop,
  Minimize2: ArrowsIn,
  MinimizeIcon: ArrowsIn,
  MinusIcon: Minus,
  Monitor,
  Moon,
  MoreHorizontal: DotsThree,
  MoreHorizontalIcon: DotsThree,
  OctagonXIcon: Prohibit,
  Palette,
  // Phosphor has no open/close variants; differentiate by `Sidebar`
  // (with content lines = open) vs `SidebarSimple` (clean = closed).
  PanelLeftClose: SidebarSimple,
  PanelLeftIcon: Sidebar,
  PanelLeftOpen: Sidebar,
  PanelRight: Sidebar,
  PanelRightClose: SidebarSimple,
  PanelRightOpen: Sidebar,
  Pencil,
  PiggyBank,
  Plus,
  PlusCircle,
  PlusIcon: Plus,
  Presentation,
  RefreshCw: ArrowsClockwise,
  RotateCcw: ArrowCounterClockwise,
  RotateCcwIcon: ArrowCounterClockwise,
  ScissorsIcon: Scissors,
  Search: MagnifyingGlass,
  SearchIcon: MagnifyingGlass,
  Send: PaperPlaneTilt,
  Settings: Gear,
  Settings2: GearSix,
  Shield,
  Sparkles: Sparkle,
  Square,
  Star,
  StarOff: Star,
  Sun,
  Terminal,
  TextInitialIcon: TextT,
  Trash2: Trash,
  Trash2Icon: Trash,
  TriangleAlertIcon: Warning,
  Upload,
  UploadIcon: Upload,
  User,
  UserIcon: User,
  UserPlus,
  Users,
  Volume2: SpeakerHigh,
  Wifi: WifiHigh,
  X,
  XCircle,
  XCircleIcon: XCircle,
  XIcon: X,
  // Rail nav additions — nearest Phosphor silhouettes.
  BriefcaseBusiness: Briefcase,
  CalendarClock: Calendar, // no calendar-clock variant
  ChartNoAxesCombined: ChartLineUp,
  FolderBookmark: Folder, // no folder-bookmark variant
  Goal: Target,
  IdCard: IdentificationCard,
  SwatchBook: Swatches,
  BookUser: BookOpenUser,
  Circle: Circle,
  CircleUser: UserCircle,
  ListTodo: ListChecks,
  Keyboard: Keyboard,
  GitPullRequestArrow: GitPullRequest,
  Info: Info,
  CircleHelp: Question,
  Blocks: SquaresFour,
  Workflow: FlowArrow,
  HatGlasses: Sunglasses,
  CreditCard: CreditCard,
} satisfies IconMap
