import type { UtilityPageDefinition, UtilityPageId } from "./utility-page.types"

function content<const Id extends UtilityPageId>(id: Id) {
  return {
    codeLabel: `utilityPage.states.${id}.codeLabel`,
    title: `utilityPage.states.${id}.title`,
    description: `utilityPage.states.${id}.description`,
  } as const
}

export const UTILITY_PAGE_CATALOG = {
  route_not_found: {
    id: "route_not_found",
    errorType: "navigation",
    condition: "expected",
    duration: "permanent",
    recovery: "navigate",
    defaultSurface: "global",
    httpStatus: 404,
    ...content("route_not_found"),
    tone: "neutral",
    actions: ["go_back"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  resource_not_found: {
    id: "resource_not_found",
    errorType: "navigation",
    condition: "expected",
    duration: "unknown",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 404,
    ...content("resource_not_found"),
    tone: "neutral",
    actions: ["go_back"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  resource_gone: {
    id: "resource_gone",
    errorType: "navigation",
    condition: "expected",
    duration: "permanent",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 410,
    ...content("resource_gone"),
    tone: "neutral",
    actions: ["go_back"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  invalid_link: {
    id: "invalid_link",
    errorType: "navigation",
    condition: "expected",
    duration: "permanent",
    recovery: "navigate",
    defaultSurface: "auth",
    httpStatus: 400,
    ...content("invalid_link"),
    tone: "warning",
    actions: ["go_back", "contact_support"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  expired_link: {
    id: "expired_link",
    errorType: "navigation",
    condition: "expected",
    duration: "permanent",
    recovery: "navigate",
    defaultSurface: "auth",
    httpStatus: 410,
    ...content("expired_link"),
    tone: "warning",
    actions: ["sign_in", "contact_support"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  authentication_required: {
    id: "authentication_required",
    errorType: "authentication",
    condition: "expected",
    duration: "temporary",
    recovery: "navigate",
    defaultSurface: "auth",
    httpStatus: 401,
    ...content("authentication_required"),
    tone: "neutral",
    actions: ["sign_in"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  session_expired: {
    id: "session_expired",
    errorType: "authentication",
    condition: "expected",
    duration: "temporary",
    recovery: "navigate",
    defaultSurface: "auth",
    httpStatus: 401,
    ...content("session_expired"),
    tone: "neutral",
    actions: ["sign_in"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  reauthentication_required: {
    id: "reauthentication_required",
    errorType: "authentication",
    condition: "expected",
    duration: "temporary",
    recovery: "navigate",
    defaultSurface: "auth",
    httpStatus: 401,
    ...content("reauthentication_required"),
    tone: "neutral",
    actions: ["reauthenticate"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  mfa_required: {
    id: "mfa_required",
    errorType: "authentication",
    condition: "expected",
    duration: "temporary",
    recovery: "navigate",
    defaultSurface: "auth",
    httpStatus: 401,
    ...content("mfa_required"),
    tone: "neutral",
    actions: ["sign_in"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  auth_link_invalid: {
    id: "auth_link_invalid",
    errorType: "authentication",
    condition: "expected",
    duration: "permanent",
    recovery: "navigate",
    defaultSurface: "auth",
    httpStatus: 400,
    ...content("auth_link_invalid"),
    tone: "warning",
    actions: ["sign_in", "contact_support"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  invite_invalid: {
    id: "invite_invalid",
    errorType: "authentication",
    condition: "expected",
    duration: "permanent",
    recovery: "navigate",
    defaultSurface: "auth",
    httpStatus: 400,
    ...content("invite_invalid"),
    tone: "warning",
    actions: ["sign_in", "contact_support"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  account_locked: {
    id: "account_locked",
    errorType: "authentication",
    condition: "expected",
    duration: "temporary",
    recovery: "navigate",
    defaultSurface: "auth",
    httpStatus: 423,
    ...content("account_locked"),
    tone: "warning",
    actions: ["contact_support"],
    telemetry: { log: "warning", report: "none" },
    reference: "when_available",
    noIndex: true,
  },
  account_disabled: {
    id: "account_disabled",
    errorType: "authentication",
    condition: "expected",
    duration: "unknown",
    recovery: "navigate",
    defaultSurface: "auth",
    httpStatus: 403,
    ...content("account_disabled"),
    tone: "warning",
    actions: ["contact_support"],
    telemetry: { log: "warning", report: "none" },
    reference: "when_available",
    noIndex: true,
  },
  access_denied: {
    id: "access_denied",
    errorType: "authorization",
    condition: "expected",
    duration: "unknown",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 403,
    ...content("access_denied"),
    tone: "neutral",
    actions: ["go_back"],
    telemetry: { log: "warning", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  membership_required: {
    id: "membership_required",
    errorType: "authorization",
    condition: "expected",
    duration: "unknown",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 403,
    ...content("membership_required"),
    tone: "neutral",
    actions: ["choose_organization", "request_access"],
    telemetry: { log: "warning", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  action_forbidden: {
    id: "action_forbidden",
    errorType: "authorization",
    condition: "expected",
    duration: "unknown",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 403,
    ...content("action_forbidden"),
    tone: "neutral",
    actions: ["go_back", "request_access"],
    telemetry: { log: "warning", report: "none" },
    reference: "when_available",
    noIndex: true,
  },
  resource_access_denied: {
    id: "resource_access_denied",
    errorType: "authorization",
    condition: "expected",
    duration: "unknown",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 403,
    ...content("resource_access_denied"),
    tone: "neutral",
    actions: ["go_back", "request_access"],
    telemetry: { log: "warning", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  workspace_unavailable: {
    id: "workspace_unavailable",
    errorType: "tenancy",
    condition: "expected",
    duration: "unknown",
    recovery: "navigate",
    defaultSurface: "global",
    httpStatus: 404,
    ...content("workspace_unavailable"),
    tone: "neutral",
    actions: ["go_back", "contact_support"],
    telemetry: { log: "warning", report: "none" },
    reference: "when_available",
    noIndex: true,
  },
  organization_unavailable: {
    id: "organization_unavailable",
    errorType: "tenancy",
    condition: "expected",
    duration: "unknown",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 404,
    ...content("organization_unavailable"),
    tone: "neutral",
    actions: ["choose_organization"],
    telemetry: { log: "warning", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  organization_suspended: {
    id: "organization_suspended",
    errorType: "tenancy",
    condition: "expected",
    duration: "unknown",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 423,
    ...content("organization_suspended"),
    tone: "warning",
    actions: ["choose_organization", "contact_support"],
    telemetry: { log: "warning", report: "none" },
    reference: "when_available",
    noIndex: true,
  },
  organization_archived: {
    id: "organization_archived",
    errorType: "tenancy",
    condition: "expected",
    duration: "permanent",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 410,
    ...content("organization_archived"),
    tone: "neutral",
    actions: ["choose_organization", "contact_support"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  feature_not_enabled: {
    id: "feature_not_enabled",
    errorType: "tenancy",
    condition: "expected",
    duration: "unknown",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 403,
    ...content("feature_not_enabled"),
    tone: "neutral",
    actions: ["go_back", "contact_support"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  maintenance_scheduled: {
    id: "maintenance_scheduled",
    errorType: "availability",
    condition: "expected",
    duration: "temporary",
    recovery: "navigate",
    defaultSurface: "global",
    httpStatus: 503,
    ...content("maintenance_scheduled"),
    tone: "warning",
    actions: ["open_status", "go_back"],
    telemetry: { log: "none", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  maintenance_active: {
    id: "maintenance_active",
    errorType: "availability",
    condition: "expected",
    duration: "temporary",
    recovery: "manual_retry",
    defaultSurface: "global",
    httpStatus: 503,
    ...content("maintenance_active"),
    tone: "warning",
    actions: ["retry", "open_status"],
    telemetry: { log: "none", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  service_unavailable: {
    id: "service_unavailable",
    errorType: "availability",
    condition: "unexpected",
    duration: "temporary",
    recovery: "manual_retry",
    defaultSurface: "global",
    httpStatus: 503,
    ...content("service_unavailable"),
    tone: "danger",
    actions: ["retry"],
    telemetry: { log: "error", report: "automatic_with_user_feedback" },
    reference: "when_available",
    noIndex: true,
  },
  service_degraded: {
    id: "service_degraded",
    errorType: "availability",
    condition: "unexpected",
    duration: "temporary",
    recovery: "manual_retry",
    defaultSurface: "shell",
    httpStatus: 503,
    ...content("service_degraded"),
    tone: "warning",
    actions: ["retry", "open_status"],
    telemetry: { log: "error", report: "automatic" },
    reference: "when_available",
    noIndex: true,
  },
  system_waking: {
    id: "system_waking",
    errorType: "availability",
    condition: "expected",
    duration: "temporary",
    recovery: "automatic_retry",
    defaultSurface: "global",
    httpStatus: 503,
    ...content("system_waking"),
    tone: "neutral",
    actions: ["open_status"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  dependency_unavailable: {
    id: "dependency_unavailable",
    errorType: "availability",
    condition: "unexpected",
    duration: "temporary",
    recovery: "manual_retry",
    defaultSurface: "shell",
    httpStatus: 503,
    ...content("dependency_unavailable"),
    tone: "danger",
    actions: ["retry", "open_status"],
    telemetry: { log: "error", report: "automatic" },
    reference: "required",
    noIndex: true,
  },
  read_only_mode: {
    id: "read_only_mode",
    errorType: "availability",
    condition: "expected",
    duration: "temporary",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 503,
    ...content("read_only_mode"),
    tone: "warning",
    actions: ["open_status", "go_back"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  unexpected_server_error: {
    id: "unexpected_server_error",
    errorType: "runtime",
    condition: "unexpected",
    duration: "unknown",
    recovery: "manual_retry",
    defaultSurface: "global",
    httpStatus: 500,
    ...content("unexpected_server_error"),
    tone: "danger",
    actions: ["retry"],
    telemetry: { log: "error", report: "automatic_with_user_feedback" },
    reference: "when_available",
    noIndex: true,
  },
  unexpected_client_error: {
    id: "unexpected_client_error",
    errorType: "runtime",
    condition: "unexpected",
    duration: "unknown",
    recovery: "manual_retry",
    defaultSurface: "shell",
    httpStatus: null,
    ...content("unexpected_client_error"),
    tone: "danger",
    actions: ["reload"],
    telemetry: { log: "error", report: "automatic_with_user_feedback" },
    reference: "when_available",
    noIndex: true,
  },
  request_timeout: {
    id: "request_timeout",
    errorType: "runtime",
    condition: "unexpected",
    duration: "temporary",
    recovery: "manual_retry",
    defaultSurface: "shell",
    httpStatus: 408,
    ...content("request_timeout"),
    tone: "warning",
    actions: ["retry"],
    telemetry: { log: "warning", report: "automatic" },
    reference: "when_available",
    noIndex: true,
  },
  gateway_error: {
    id: "gateway_error",
    errorType: "runtime",
    condition: "unexpected",
    duration: "temporary",
    recovery: "manual_retry",
    defaultSurface: "global",
    httpStatus: 502,
    ...content("gateway_error"),
    tone: "danger",
    actions: ["retry", "open_status"],
    telemetry: { log: "error", report: "automatic" },
    reference: "when_available",
    noIndex: true,
  },
  chunk_load_failed: {
    id: "chunk_load_failed",
    errorType: "runtime",
    condition: "unexpected",
    duration: "temporary",
    recovery: "manual_retry",
    defaultSurface: "shell",
    httpStatus: null,
    ...content("chunk_load_failed"),
    tone: "warning",
    actions: ["reload"],
    telemetry: { log: "warning", report: "automatic" },
    reference: "when_available",
    noIndex: true,
  },
  update_required: {
    id: "update_required",
    errorType: "runtime",
    condition: "expected",
    duration: "temporary",
    recovery: "manual_retry",
    defaultSurface: "shell",
    httpStatus: 409,
    ...content("update_required"),
    tone: "neutral",
    actions: ["reload"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  offline: {
    id: "offline",
    errorType: "connectivity",
    condition: "expected",
    duration: "temporary",
    recovery: "automatic_retry",
    defaultSurface: "shell",
    httpStatus: null,
    ...content("offline"),
    tone: "warning",
    actions: ["retry"],
    telemetry: { log: "none", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  connection_lost: {
    id: "connection_lost",
    errorType: "connectivity",
    condition: "expected",
    duration: "temporary",
    recovery: "manual_retry",
    defaultSurface: "shell",
    httpStatus: null,
    ...content("connection_lost"),
    tone: "warning",
    actions: ["retry"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  connection_restoring: {
    id: "connection_restoring",
    errorType: "connectivity",
    condition: "expected",
    duration: "temporary",
    recovery: "automatic_retry",
    defaultSurface: "shell",
    httpStatus: null,
    ...content("connection_restoring"),
    tone: "neutral",
    actions: [],
    telemetry: { log: "none", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  unsupported_browser: {
    id: "unsupported_browser",
    errorType: "client",
    condition: "expected",
    duration: "permanent",
    recovery: "navigate",
    defaultSurface: "global",
    httpStatus: null,
    ...content("unsupported_browser"),
    tone: "warning",
    actions: ["contact_support"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  javascript_required: {
    id: "javascript_required",
    errorType: "client",
    condition: "expected",
    duration: "permanent",
    recovery: "manual_retry",
    defaultSurface: "global",
    httpStatus: null,
    ...content("javascript_required"),
    tone: "warning",
    actions: ["reload"],
    telemetry: { log: "none", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  cookies_required: {
    id: "cookies_required",
    errorType: "client",
    condition: "expected",
    duration: "temporary",
    recovery: "manual_retry",
    defaultSurface: "auth",
    httpStatus: null,
    ...content("cookies_required"),
    tone: "warning",
    actions: ["reload", "contact_support"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
  storage_unavailable: {
    id: "storage_unavailable",
    errorType: "client",
    condition: "unexpected",
    duration: "unknown",
    recovery: "manual_retry",
    defaultSurface: "global",
    httpStatus: null,
    ...content("storage_unavailable"),
    tone: "warning",
    actions: ["reload"],
    telemetry: { log: "warning", report: "automatic_with_user_feedback" },
    reference: "when_available",
    noIndex: true,
  },
  rate_limited: {
    id: "rate_limited",
    errorType: "capacity",
    condition: "expected",
    duration: "temporary",
    recovery: "manual_retry",
    defaultSurface: "shell",
    httpStatus: 429,
    ...content("rate_limited"),
    tone: "warning",
    actions: ["retry"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "when_available",
    noIndex: true,
  },
  quota_exceeded: {
    id: "quota_exceeded",
    errorType: "capacity",
    condition: "expected",
    duration: "unknown",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 429,
    ...content("quota_exceeded"),
    tone: "warning",
    actions: ["go_back", "contact_support"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "when_available",
    noIndex: true,
  },
  ai_budget_exhausted: {
    id: "ai_budget_exhausted",
    errorType: "capacity",
    condition: "expected",
    duration: "temporary",
    recovery: "navigate",
    defaultSurface: "shell",
    httpStatus: 429,
    ...content("ai_budget_exhausted"),
    tone: "warning",
    actions: ["go_back", "contact_support"],
    telemetry: { log: "warning", report: "none" },
    reference: "when_available",
    noIndex: true,
  },
  cooldown_active: {
    id: "cooldown_active",
    errorType: "capacity",
    condition: "expected",
    duration: "temporary",
    recovery: "automatic_retry",
    defaultSurface: "shell",
    httpStatus: 429,
    ...content("cooldown_active"),
    tone: "neutral",
    actions: ["retry"],
    telemetry: { log: "aggregate", report: "none" },
    reference: "hidden",
    noIndex: true,
  },
} as const satisfies Record<UtilityPageId, UtilityPageDefinition>

export function getUtilityPageDefinition(
  state: UtilityPageId,
): UtilityPageDefinition {
  return UTILITY_PAGE_CATALOG[state]
}
