import { App } from "aws-cdk-lib"
import { Match, Template } from "aws-cdk-lib/assertions"
import { describe, expect, it } from "vitest"
import { SecretsStack } from "../lib/secrets-stack.js"
import { TEST_ACCOUNT, TEST_REGION } from "./helper.js"

function buildSecretsStack(): SecretsStack {
  const app = new App()
  return new SecretsStack(app, "SecretsBootstrap", {
    env: { account: TEST_ACCOUNT, region: TEST_REGION },
  })
}

describe("SecretsStack — Vault auto-unseal KMS + IAM", () => {
  const stack = buildSecretsStack()
  const template = Template.fromStack(stack)

  it("creates exactly one KMS Customer-Managed Key with rotation enabled", () => {
    template.resourceCountIs("AWS::KMS::Key", 1)
    template.hasResourceProperties("AWS::KMS::Key", {
      EnableKeyRotation: true,
      Description: Match.stringLikeRegexp("Auto-unseals"),
    })
  })

  it("retains the KMS Key on stack delete (RETAIN policy)", () => {
    // RemovalPolicy.RETAIN is the first line of defence against `cdk destroy`
    // orphaning the Vault data. CFN-level DeletionPolicy must be `Retain`.
    template.hasResource("AWS::KMS::Key", {
      DeletionPolicy: "Retain",
      UpdateReplacePolicy: "Retain",
    })
  })

  it("attaches a deny statement on kms:ScheduleKeyDeletion to AnyPrincipal", () => {
    // Belt-and-suspenders on top of RETAIN. RETAIN protects against
    // `cdk destroy`; this resource policy protects against any direct call
    // to `aws kms schedule-key-deletion` even by the root account.
    template.hasResourceProperties("AWS::KMS::Key", {
      KeyPolicy: {
        Statement: Match.arrayWith([
          Match.objectLike({
            Sid: "DenyScheduleKeyDeletion",
            Effect: "Deny",
            Principal: { AWS: "*" },
            Action: "kms:ScheduleKeyDeletion",
          }),
        ]),
      },
    })
  })

  it("creates the KMS alias alias/monorepo-vault-unseal", () => {
    template.hasResourceProperties("AWS::KMS::Alias", {
      AliasName: "alias/monorepo-vault-unseal",
    })
  })

  it("creates three IAM users: vault-unseal-vps + vault-aws-auth-verifier + vault-ssm-sync", () => {
    template.resourceCountIs("AWS::IAM::User", 3)
    template.hasResourceProperties("AWS::IAM::User", {
      UserName: "vault-unseal-vps",
    })
    template.hasResourceProperties("AWS::IAM::User", {
      UserName: "vault-aws-auth-verifier",
    })
    template.hasResourceProperties("AWS::IAM::User", {
      UserName: "vault-ssm-sync",
    })
  })

  it("vault-aws-auth-verifier has only the 4 identity-check actions (no KMS / no SSM / no SM)", () => {
    template.hasResourceProperties("AWS::IAM::Policy", {
      PolicyDocument: {
        Statement: Match.arrayWith([
          Match.objectLike({
            Sid: "VaultAwsAuthVerifierIdentityChecks",
            Effect: "Allow",
            Action: Match.arrayWith([
              "sts:GetCallerIdentity",
              "iam:GetUser",
              "iam:GetRole",
              "iam:GetInstanceProfile",
            ]),
            Resource: "*",
          }),
        ]),
      },
      Users: Match.arrayWith([
        Match.objectLike({
          Ref: Match.stringLikeRegexp("VaultAwsAuthVerifierUser"),
        }),
      ]),
    })
  })

  it("exposes vault-aws-auth-verifier user on the stack instance + CfnOutput", () => {
    expect(stack.vaultAwsAuthVerifierUser).toBeDefined()
    template.hasOutput("VaultAwsAuthVerifierUserName", {})
  })

  it("does NOT create an access key in CFN (operator generates out-of-band)", () => {
    // Programmatic credentials are generated by hand via
    // `aws iam create-access-key --user-name vault-unseal-vps` and stored in
    // macOS Keychain + paper. Keeping them out of CFN means they never appear
    // in `aws cloudformation describe-stacks` outputs.
    template.resourceCountIs("AWS::IAM::AccessKey", 0)
  })

  it("grants vault-unseal-vps Encrypt/Decrypt/ReEncrypt/GenerateDataKey + DescribeKey scoped to the Key ARN", () => {
    template.hasResourceProperties("AWS::IAM::Policy", {
      PolicyDocument: {
        Statement: Match.arrayWith([
          Match.objectLike({
            // grantEncryptDecrypt emits in this exact order; arrayWith
            // requires the listed patterns to appear in the same relative
            // order in the actual array.
            Action: Match.arrayWith([
              "kms:Decrypt",
              "kms:Encrypt",
              "kms:ReEncrypt*",
              "kms:GenerateDataKey*",
            ]),
            Effect: "Allow",
            Resource: Match.objectLike({
              "Fn::GetAtt": Match.arrayWith([
                Match.stringLikeRegexp("VaultUnsealKey"),
              ]),
            }),
          }),
          Match.objectLike({
            Action: "kms:DescribeKey",
            Effect: "Allow",
            Resource: Match.objectLike({
              "Fn::GetAtt": Match.arrayWith([
                Match.stringLikeRegexp("VaultUnsealKey"),
              ]),
            }),
          }),
        ]),
      },
    })
  })

  it("KMS Resource: '*' is allowed only when guarded by kms:ViaService = ssm.<region>.amazonaws.com", () => {
    // Original invariant: vault-unseal-vps must NOT have unrestricted KMS
    // access — that user's KMS calls are scoped to the unseal Key ARN.
    //
    // M4 exception: vault-ssm-sync needs kms:GenerateDataKey + kms:Decrypt
    // on the AWS-managed `alias/aws/ssm` key (default SecureString
    // encryption). AWS-managed-key resource policies do not honour an
    // ARN-scoped Allow from another principal's policy — the SSM API
    // itself gates access via the kms:ViaService condition. So a
    // Resource: '*' is acceptable iff the condition narrows the use to
    // SSM-only calls.
    const policy = template.findResources("AWS::IAM::Policy")
    for (const [, resource] of Object.entries(policy)) {
      const statements = (
        resource.Properties as { PolicyDocument: { Statement: unknown[] } }
      ).PolicyDocument.Statement
      for (const stmt of statements) {
        const s = stmt as {
          Action?: string | string[]
          Resource?: string | unknown
          Condition?: { StringEquals?: Record<string, string> }
        }
        const actions = Array.isArray(s.Action) ? s.Action : [s.Action]
        if (
          !actions.some((a) => typeof a === "string" && a.startsWith("kms:"))
        ) {
          continue
        }
        if (s.Resource === "*") {
          const viaService = s.Condition?.StringEquals?.["kms:ViaService"]
          expect(viaService).toMatch(/^ssm\.[a-z0-9-]+\.amazonaws\.com$/)
        }
      }
    }
  })

  it("exposes Key + User on the stack instance for downstream wiring", () => {
    expect(stack.vaultUnsealKey).toBeDefined()
    expect(stack.vaultUnsealUser).toBeDefined()
    // `userName` is a CFN Token at synth time; check via the template instead.
    template.hasResourceProperties("AWS::IAM::User", {
      UserName: "vault-unseal-vps",
    })
  })

  it("publishes Key ID, Key ARN, and User Names as CfnOutputs", () => {
    template.hasOutput("VaultUnsealKeyId", {})
    template.hasOutput("VaultUnsealKeyArn", {})
    template.hasOutput("VaultUnsealUserName", {})
    template.hasOutput("VaultAwsAuthVerifierUserName", {})
    template.hasOutput("VaultSsmSyncUserName", {})
  })

  it("vault-ssm-sync has ssm:PutParameter/GetParameter scoped to the 6 sync params", () => {
    // Scoped to the 4 secret + 2 heartbeat params. No `*`. No
    // ssm:DeleteParameter (compromised key can overwrite, never erase).
    template.hasResourceProperties("AWS::IAM::Policy", {
      PolicyDocument: {
        Statement: Match.arrayWith([
          Match.objectLike({
            Sid: "VaultSsmSyncWriteScopedParams",
            Effect: "Allow",
            Action: Match.arrayWith(["ssm:PutParameter", "ssm:GetParameter"]),
            // Resource is an array of 6 ARN strings — one per param.
            Resource: Match.arrayWith([
              Match.stringLikeRegexp("/monorepo/staging/better-auth-secret$"),
              Match.stringLikeRegexp("/monorepo/staging/resend-api-key$"),
              Match.stringLikeRegexp("/monorepo/staging/sync-heartbeat$"),
              Match.stringLikeRegexp(
                "/monorepo/production/better-auth-secret$",
              ),
              Match.stringLikeRegexp("/monorepo/production/resend-api-key$"),
              Match.stringLikeRegexp("/monorepo/production/sync-heartbeat$"),
            ]),
          }),
        ]),
      },
      Users: Match.arrayWith([
        Match.objectLike({
          Ref: Match.stringLikeRegexp("VaultSsmSyncUser"),
        }),
      ]),
    })
  })

  it("vault-ssm-sync KMS access is gated by kms:ViaService = ssm.<region>.amazonaws.com", () => {
    // The AWS-managed alias/aws/ssm key gates SecureString crypto. The
    // policy is `Resource: *` (managed-key constraint) but the
    // kms:ViaService condition narrows the action to ssm-only calls
    // — the same hardening AWS docs recommend.
    template.hasResourceProperties("AWS::IAM::Policy", {
      PolicyDocument: {
        Statement: Match.arrayWith([
          Match.objectLike({
            Sid: "VaultSsmSyncKmsForSsmDefaultKey",
            Effect: "Allow",
            Action: Match.arrayWith(["kms:GenerateDataKey", "kms:Decrypt"]),
            Resource: "*",
            Condition: {
              StringEquals: Match.objectLike({
                "kms:ViaService": Match.stringLikeRegexp(
                  "^ssm\\.[a-z0-9-]+\\.amazonaws\\.com$",
                ),
              }),
            },
          }),
        ]),
      },
    })
  })

  it("does NOT grant vault-ssm-sync any access to the Vault auto-unseal CMK", () => {
    // Blast-radius separation: even if vault-ssm-sync keys leak, attacker
    // cannot touch the auto-unseal KMS Key. Verified by ensuring the
    // sync user's policy has no statement referencing the VaultUnsealKey
    // Fn::GetAtt.
    const policies = template.findResources("AWS::IAM::Policy")
    for (const [, resource] of Object.entries(policies)) {
      const props = resource.Properties as {
        PolicyDocument: { Statement: unknown[] }
        Users?: Array<{ Ref?: string }>
      }
      const isSyncUserPolicy = (props.Users ?? []).some((u) =>
        (u.Ref ?? "").startsWith("VaultSsmSyncUser"),
      )
      if (!isSyncUserPolicy) continue
      const stmtStr = JSON.stringify(props.PolicyDocument.Statement)
      expect(stmtStr).not.toContain("VaultUnsealKey")
    }
  })
})
