import { App } from "aws-cdk-lib"
import { Match, Template } from "aws-cdk-lib/assertions"
import { describe, expect, it } from "vitest"
import { SecretsStack } from "../lib/secrets-stack.js"
import { TEST_ACCOUNT, TEST_REGION } from "./helper.js"

function buildSecretsStack(): SecretsStack {
  const app = new App()
  return new SecretsStack(app, "SecretsBootstrap", {
    env: { account: TEST_ACCOUNT, region: TEST_REGION },
  })
}

describe("SecretsStack — Vault auto-unseal KMS + IAM", () => {
  const stack = buildSecretsStack()
  const template = Template.fromStack(stack)

  it("creates exactly one KMS Customer-Managed Key with rotation enabled", () => {
    template.resourceCountIs("AWS::KMS::Key", 1)
    template.hasResourceProperties("AWS::KMS::Key", {
      EnableKeyRotation: true,
      Description: Match.stringLikeRegexp("Auto-unseals"),
    })
  })

  it("retains the KMS Key on stack delete (RETAIN policy)", () => {
    // RemovalPolicy.RETAIN is the first line of defence against `cdk destroy`
    // orphaning the Vault data. CFN-level DeletionPolicy must be `Retain`.
    template.hasResource("AWS::KMS::Key", {
      DeletionPolicy: "Retain",
      UpdateReplacePolicy: "Retain",
    })
  })

  it("attaches a deny statement on kms:ScheduleKeyDeletion to AnyPrincipal", () => {
    // Belt-and-suspenders on top of RETAIN. RETAIN protects against
    // `cdk destroy`; this resource policy protects against any direct call
    // to `aws kms schedule-key-deletion` even by the root account.
    template.hasResourceProperties("AWS::KMS::Key", {
      KeyPolicy: {
        Statement: Match.arrayWith([
          Match.objectLike({
            Sid: "DenyScheduleKeyDeletion",
            Effect: "Deny",
            Principal: { AWS: "*" },
            Action: "kms:ScheduleKeyDeletion",
          }),
        ]),
      },
    })
  })

  it("creates the KMS alias alias/monorepo-vault-unseal", () => {
    template.hasResourceProperties("AWS::KMS::Alias", {
      AliasName: "alias/monorepo-vault-unseal",
    })
  })

  it("creates two IAM users: vault-unseal-vps + vault-aws-auth-verifier", () => {
    template.resourceCountIs("AWS::IAM::User", 2)
    template.hasResourceProperties("AWS::IAM::User", {
      UserName: "vault-unseal-vps",
    })
    template.hasResourceProperties("AWS::IAM::User", {
      UserName: "vault-aws-auth-verifier",
    })
  })

  it("vault-aws-auth-verifier has only the 4 identity-check actions (no KMS / no SSM / no SM)", () => {
    template.hasResourceProperties("AWS::IAM::Policy", {
      PolicyDocument: {
        Statement: Match.arrayWith([
          Match.objectLike({
            Sid: "VaultAwsAuthVerifierIdentityChecks",
            Effect: "Allow",
            Action: Match.arrayWith([
              "sts:GetCallerIdentity",
              "iam:GetUser",
              "iam:GetRole",
              "iam:GetInstanceProfile",
            ]),
            Resource: "*",
          }),
        ]),
      },
      Users: Match.arrayWith([
        Match.objectLike({
          Ref: Match.stringLikeRegexp("VaultAwsAuthVerifierUser"),
        }),
      ]),
    })
  })

  it("exposes vault-aws-auth-verifier user on the stack instance + CfnOutput", () => {
    expect(stack.vaultAwsAuthVerifierUser).toBeDefined()
    template.hasOutput("VaultAwsAuthVerifierUserName", {})
  })

  it("does NOT create an access key in CFN (operator generates out-of-band)", () => {
    // Programmatic credentials are generated by hand via
    // `aws iam create-access-key --user-name vault-unseal-vps` and stored in
    // macOS Keychain + paper. Keeping them out of CFN means they never appear
    // in `aws cloudformation describe-stacks` outputs.
    template.resourceCountIs("AWS::IAM::AccessKey", 0)
  })

  it("grants vault-unseal-vps Encrypt/Decrypt/ReEncrypt/GenerateDataKey + DescribeKey scoped to the Key ARN", () => {
    template.hasResourceProperties("AWS::IAM::Policy", {
      PolicyDocument: {
        Statement: Match.arrayWith([
          Match.objectLike({
            // grantEncryptDecrypt emits in this exact order; arrayWith
            // requires the listed patterns to appear in the same relative
            // order in the actual array.
            Action: Match.arrayWith([
              "kms:Decrypt",
              "kms:Encrypt",
              "kms:ReEncrypt*",
              "kms:GenerateDataKey*",
            ]),
            Effect: "Allow",
            Resource: Match.objectLike({
              "Fn::GetAtt": Match.arrayWith([
                Match.stringLikeRegexp("VaultUnsealKey"),
              ]),
            }),
          }),
          Match.objectLike({
            Action: "kms:DescribeKey",
            Effect: "Allow",
            Resource: Match.objectLike({
              "Fn::GetAtt": Match.arrayWith([
                Match.stringLikeRegexp("VaultUnsealKey"),
              ]),
            }),
          }),
        ]),
      },
    })
  })

  it("does NOT grant Resource: '*' anywhere — every KMS action is scoped to the single Key", () => {
    const policy = template.findResources("AWS::IAM::Policy")
    for (const [, resource] of Object.entries(policy)) {
      const statements = (
        resource.Properties as { PolicyDocument: { Statement: unknown[] } }
      ).PolicyDocument.Statement
      for (const stmt of statements) {
        const s = stmt as {
          Action?: string | string[]
          Resource?: string | unknown
        }
        const actions = Array.isArray(s.Action) ? s.Action : [s.Action]
        if (
          actions.some((a) => typeof a === "string" && a.startsWith("kms:"))
        ) {
          expect(s.Resource).not.toBe("*")
        }
      }
    }
  })

  it("exposes Key + User on the stack instance for downstream wiring", () => {
    expect(stack.vaultUnsealKey).toBeDefined()
    expect(stack.vaultUnsealUser).toBeDefined()
    // `userName` is a CFN Token at synth time; check via the template instead.
    template.hasResourceProperties("AWS::IAM::User", {
      UserName: "vault-unseal-vps",
    })
  })

  it("publishes Key ID, Key ARN, and User Name as CfnOutputs", () => {
    template.hasOutput("VaultUnsealKeyId", {})
    template.hasOutput("VaultUnsealKeyArn", {})
    template.hasOutput("VaultUnsealUserName", {})
  })
})
