"use client"

import * as React from "react"
import type { Table } from "@tanstack/react-table"

import { ArchetypeTable } from "@workspace/ui/blocks/archetypes"
import {
  buildTableToolbar,
  SectionList,
  sectionInspectorActivityLog,
  sectionInspectorKeyDetails,
  sectionInspectorLinkedRecords,
  sectionInspectorMoneyTotals,
  sectionTable,
} from "@workspace/ui/blocks/content-panel"
import type {
  ContentFooterAction,
  ContentHeaderFavoriteToggle,
  ContentToolbarProps,
  TableColumnOption,
  TableColumnSpec,
  TableSectionRow,
  ViewTab,
} from "@workspace/ui/blocks/content-panel"
import type { InspectorTab } from "@workspace/ui/blocks/inspector-sheet"
import { toast } from "@workspace/ui/components/sonner"

import { orgHref } from "@/lib/org/href"

/**
 * DebugNormalTableView — the Debug → Archetype Table (Normal Table) reference
 * page. It demonstrates the Table archetype WITH ALL of its mandatory chrome:
 * views, the favorite star, the auto-generated per-column filter, and the
 * selection footer — plus the optional multi-tab row Inspector. Everything comes
 * from the packages/ui blocks; nothing is hand-rolled.
 *
 * Governance the page relies on (so it can't regress to a bare table):
 *   - `views` / `favorite` / `selectionActions` are REQUIRED by ArchetypeTable.
 *   - the toolbar FILTER is AUTO-GENERATED by the archetype from the columns
 *     below — the page deliberately does NOT wire a filter; every column is
 *     filterable for free (add a column → it gains a filter).
 *
 * Rows come from `demo_debug_normal_table_record` (dev-seeded, never real product
 * data), projected server-side into plain `TableSectionRow`s.
 */

const STATUS_OPTIONS: TableColumnOption[] = [
  { value: "draft", label: "Draft" },
  { value: "posted", label: "Posted" },
  { value: "rejected", label: "Rejected" },
]

const COLUMNS: TableColumnSpec[] = [
  { id: "document", header: "Document", kind: "text", role: "id", width: 160 },
  { id: "partner", header: "Partner", kind: "text", width: 180 },
  // `badge` renders the status chip AND filters as an option dropdown (kind →
  // option), its choices defaulting to these `options`.
  {
    id: "status",
    header: "Status",
    kind: "badge",
    options: STATUS_OPTIONS,
    width: 130,
  },
  { id: "amount", header: "Amount", kind: "number", align: "end", width: 140 },
  // Explicit filter override: the value is an ISO date string, so give it the
  // date-range filter rather than the `text` default its `kind` would pick.
  {
    id: "issuedOn",
    header: "Issued",
    kind: "text",
    filter: { variant: "date" },
    width: 140,
  },
]

/** The bulk actions the selection footer offers (demo — they just toast). */
function selectionActions(
  table: Table<TableSectionRow> | null,
): ContentFooterAction[] {
  const count = () => table?.getFilteredSelectedRowModel().rows.length ?? 0
  return [
    {
      id: "export",
      label: "Export",
      icon: "FileDown",
      onSelect: () => toast.success(`Export ${count()} row(s) (demo)`),
    },
    {
      id: "delete",
      label: "Delete",
      icon: "Trash2",
      variant: "destructive",
      onSelect: () => toast.success(`Delete ${count()} row(s) (demo)`),
    },
  ]
}

/**
 * The row Inspector, one entry per tab. `details` is BUILT FROM THE ROW's own
 * columns (identity + money totals); `activity` / `related` are demo tabs whose
 * content is not column-derived; `export` is a non-column tab that is always
 * available regardless of the columns. Tabs with no content are omitted by the
 * rail — this is what makes the Inspector show more than one page.
 */
function buildInspectorTabs(
  row: TableSectionRow,
): Partial<Record<InspectorTab, React.ReactNode>> {
  const doc = String(row.document ?? "")
  const partner = String(row.partner ?? "")
  const status = String(row.status ?? "")
  const amount = Number(row.amount ?? 0)
  const net = Math.round(amount * 0.8 * 100) / 100
  const vat = Math.round((amount - net) * 100) / 100

  return {
    details: (
      <SectionList
        sections={[
          sectionInspectorKeyDetails({
            lines: [
              { label: "Document", value: doc, icon: "HashIcon" },
              { label: "Partner", value: partner, icon: "Building2" },
              {
                label: "Status",
                value: status,
                type: "select",
                options: STATUS_OPTIONS,
                icon: "CheckCircle2",
              },
              {
                label: "Issued",
                value: String(row.issuedOn ?? ""),
                type: "date",
                icon: "CalendarIcon",
              },
              {
                label: "Note",
                value: String(row.note ?? ""),
                icon: "TextInitialIcon",
              },
            ],
          }),
          sectionInspectorMoneyTotals({
            title: "Totals",
            rows: [
              { label: "Net", amount: net },
              { label: "VAT 21%", amount: vat },
              { label: "Total", amount, emphasis: true },
            ],
          }),
        ]}
      />
    ),
    activity: (
      <SectionList
        sections={[
          sectionInspectorActivityLog({
            title: "Activity",
            entries: [
              {
                id: "a1",
                field: "Status",
                before: "draft",
                after: status,
                when: "10:15",
                by: "You",
                onUndo: () => toast.success("Reverted Status (demo)"),
              },
              {
                id: "a2",
                field: "Amount",
                before: "0",
                after: String(amount),
                when: "10:12",
                by: "You",
                onUndo: () => toast.success("Reverted Amount (demo)"),
              },
            ],
          }),
        ]}
      />
    ),
    related: (
      <SectionList
        sections={[
          sectionInspectorLinkedRecords({
            title: "Relations",
            addLabel: "Link a document",
            onAdd: () => toast.success("Link a record (demo)"),
            onRemove: (id) => toast.success(`Unlinked ${id} (demo)`),
            items: [
              {
                id: "partner",
                relation: "Partner",
                label: partner,
                meta: "Counterparty",
                icon: "Building2",
              },
            ],
          }),
        ]}
      />
    ),
  }
}

export function DebugNormalTableView({
  slug,
  title,
  rows,
  favorite,
}: {
  slug: string
  title: string
  rows: readonly TableSectionRow[]
  favorite: ContentHeaderFavoriteToggle
}) {
  const [activeTab, setActiveTab] = React.useState("all")
  const [search, setSearch] = React.useState("")

  // Views segment the rows by status (a coarse, page-owned narrow); the
  // archetype's auto filter narrows further (fine, per-column).
  const viewRows = React.useMemo(
    () =>
      activeTab === "all"
        ? rows
        : rows.filter((row) => String(row.status ?? "") === activeTab),
    [rows, activeTab],
  )

  const views: ViewTab[] = React.useMemo(
    () => [
      { value: "all", label: "All", count: rows.length },
      ...STATUS_OPTIONS.map((option) => ({
        value: option.value,
        label: option.label,
        count: rows.filter((row) => String(row.status ?? "") === option.value)
          .length,
      })),
    ],
    [rows],
  )

  const buildToolbar = React.useCallback(
    (
      table: Table<TableSectionRow> | null,
    ): ContentToolbarProps<TableSectionRow> =>
      // No `filter` here on purpose — ArchetypeTable auto-generates it from the
      // columns. The page owns only search (+ the columns manager, default on).
      buildTableToolbar(table, {
        search: { value: search, onChange: setSearch },
      }),
    [search],
  )

  return (
    <ArchetypeTable<TableSectionRow>
      title={title}
      breadcrumb={[
        { label: "Debug", href: orgHref(slug, "debug"), icon: "Bug" },
      ]}
      favorite={favorite}
      views={{
        tabs: views,
        value: activeTab,
        onValueChange: setActiveTab,
        onAddView: () => toast.success("Add view — coming soon"),
      }}
      toolbar={buildToolbar}
      selectionActions={selectionActions}
      sections={[
        sectionTable({
          anchor: "records",
          columns: COLUMNS,
          rows: viewRows,
          rowIdKey: "id",
          features: { search: true, inspect: true },
          emptyText: "No demo records — seed the dev org first.",
        }),
      ]}
      inspectorRowTitle={(row) => `#${String(row.document ?? "")}`}
      inspectorRowName={(row) => String(row.partner ?? "")}
      inspectorRowContent={buildInspectorTabs}
    />
  )
}
