"use client"

import * as React from "react"
import type { Table } from "@tanstack/react-table"

import { ArchetypeTable } from "@workspace/ui/blocks/archetypes"
import {
  buildTableToolbar,
  SectionList,
  sectionInspectorActivityLog,
  sectionInspectorKeyDetails,
  sectionInspectorLinkedRecords,
  sectionInspectorMoneyTotals,
  sectionTable,
} from "@workspace/ui/blocks/content-panel"
import type {
  ContentFooterAction,
  ContentHeaderFavoriteToggle,
  ContentToolbarProps,
  SectionCellCommit,
  TableCellValue,
  TableColumnOption,
  TableColumnSpec,
  TableSectionRow,
  ViewTab,
} from "@workspace/ui/blocks/content-panel"
import type { InspectorTab } from "@workspace/ui/blocks/inspector-sheet"
import { toast } from "@workspace/ui/components/sonner"

import { orgHref } from "@/lib/org/href"

/**
 * DebugNormalTableView — the Debug → Archetype Table (Normal Table) reference
 * page: a FULLY FUNCTIONING Table archetype (not a static mock). It owns the rows
 * in client state, so every affordance actually mutates the table data:
 *   - inline cell edit (Partner, Amount) saves through `onCellEdit`;
 *   - inspector fields (Partner, Status, Issued, Note) save through the same
 *     commit and are reflected back in the grid;
 *   - the Approve / Reject inspector actions set the row's status;
 *   - the selection footer Delete removes rows, Export copies them to clipboard.
 * Edits are session-scoped client state (they reset on reload) — never a write to
 * the seeded demo table — so the reference stays a clean, re-seedable template.
 *
 * Everything is composed from the packages/ui blocks. `views` / `favorite` /
 * `selectionActions` are the archetype's mandatory chrome; the per-column filter
 * is auto-generated by the archetype from the columns below.
 */

const STATUS_OPTIONS: TableColumnOption[] = [
  { value: "draft", label: "Draft" },
  { value: "posted", label: "Posted" },
  { value: "rejected", label: "Rejected" },
]

const COLUMNS: TableColumnSpec[] = [
  { id: "document", header: "Document", kind: "text", role: "id", width: 160 },
  // Inline-editable in the grid (click to edit) — the edit persists via onCellEdit.
  {
    id: "partner",
    header: "Partner",
    kind: "text",
    edit: "inline",
    width: 180,
  },
  // Rendered as a colored badge (display); edited via the Inspector's select.
  {
    id: "status",
    header: "Status",
    kind: "badge",
    options: STATUS_OPTIONS,
    width: 130,
  },
  {
    id: "amount",
    header: "Amount",
    kind: "number",
    edit: "inline",
    align: "end",
    width: 140,
  },
  // ISO date string → give it the date-range filter (overrides the text default).
  {
    id: "issuedOn",
    header: "Issued",
    kind: "text",
    filter: { variant: "date" },
    width: 140,
  },
]

export function DebugNormalTableView({
  slug,
  title,
  rows: initialRows,
  favorite,
}: {
  slug: string
  title: string
  rows: readonly TableSectionRow[]
  favorite: ContentHeaderFavoriteToggle
}) {
  const [activeTab, setActiveTab] = React.useState("all")
  const [search, setSearch] = React.useState("")
  // The single source of truth for the grid + inspector: seeded once from the
  // server rows, then owned here so every edit is visible immediately.
  const [rows, setRows] = React.useState<TableSectionRow[]>(() =>
    initialRows.map((row) => ({ ...row })),
  )

  /** Write one field of one row — the shared commit behind inline cell edits,
   *  inspector-field edits, and the Approve/Reject actions. */
  const commit = React.useCallback(
    (rowId: string, field: string, value: TableCellValue) => {
      setRows((prev) =>
        prev.map((row) =>
          String(row.id) === rowId ? { ...row, [field]: value } : row,
        ),
      )
    },
    [],
  )

  const onCellEdit: SectionCellCommit = React.useCallback(
    ({ rowId, columnId, value }) => {
      commit(rowId, columnId, value)
    },
    [commit],
  )

  // Views segment by status (page-owned, coarse); the archetype's auto filter
  // narrows further (per column).
  const viewRows = React.useMemo(
    () =>
      activeTab === "all"
        ? rows
        : rows.filter((row) => String(row.status ?? "") === activeTab),
    [rows, activeTab],
  )

  const views: ViewTab[] = React.useMemo(
    () => [
      { value: "all", label: "All", count: rows.length },
      ...STATUS_OPTIONS.map((option) => ({
        value: option.value,
        label: option.label,
        count: rows.filter((row) => String(row.status ?? "") === option.value)
          .length,
      })),
    ],
    [rows],
  )

  const buildToolbar = React.useCallback(
    (
      table: Table<TableSectionRow> | null,
    ): ContentToolbarProps<TableSectionRow> =>
      buildTableToolbar(table, {
        search: { value: search, onChange: setSearch },
      }),
    [search],
  )

  const selectionActions = React.useCallback(
    (table: Table<TableSectionRow> | null): ContentFooterAction[] => {
      const selected = () => table?.getFilteredSelectedRowModel().rows ?? []
      return [
        {
          id: "export",
          label: "Export",
          icon: "FileDown",
          onSelect: () => {
            const picked = selected().map((row) => row.original)
            const header = COLUMNS.map((column) => column.header).join(",")
            const body = picked
              .map((row) =>
                COLUMNS.map((column) => String(row[column.id] ?? "")).join(","),
              )
              .join("\n")
            void navigator.clipboard.writeText(`${header}\n${body}`)
            toast.success(`Copied ${picked.length} row(s) to clipboard`)
          },
        },
        {
          id: "delete",
          label: "Delete",
          icon: "Trash2",
          variant: "destructive",
          onSelect: () => {
            const ids = new Set(
              selected().map((row) => String(row.original.id)),
            )
            setRows((prev) => prev.filter((row) => !ids.has(String(row.id))))
            table?.resetRowSelection()
            toast.success(`Deleted ${ids.size} row(s)`)
          },
        },
      ]
    },
    [],
  )

  return (
    <ArchetypeTable<TableSectionRow>
      title={title}
      breadcrumb={[
        { label: "Debug", href: orgHref(slug, "debug"), icon: "Bug" },
      ]}
      favorite={favorite}
      views={{
        tabs: views,
        value: activeTab,
        onValueChange: setActiveTab,
        onAddView: () => toast.success("Add view — coming soon"),
      }}
      toolbar={buildToolbar}
      selectionActions={selectionActions}
      onCellEdit={onCellEdit}
      sections={[
        sectionTable({
          anchor: "records",
          columns: COLUMNS,
          rows: viewRows,
          rowIdKey: "id",
          features: { search: true, inspect: true },
          emptyText: "No demo records — seed the dev org first.",
        }),
      ]}
      inspectorRowTitle={(row) => `#${String(row.document ?? "")}`}
      inspectorRowName={(row) => String(row.partner ?? "")}
      inspectorRowContent={(row) => buildInspectorTabs(row, commit)}
      inspectorDeclineLabel="Reject"
      inspectorApproveLabel="Approve"
      onInspectorDecline={(row) => {
        commit(String(row.id), "status", "rejected")
        toast.success(`Rejected #${String(row.document ?? "")}`)
      }}
      onInspectorApprove={(row) => {
        commit(String(row.id), "status", "posted")
        toast.success(`Approved #${String(row.document ?? "")}`)
      }}
      onInspectorCopy={(row, what) => {
        const value =
          what === "link"
            ? `${window.location.origin}${window.location.pathname}?inspect=${String(row.id ?? "")}`
            : what === "id"
              ? String(row.id ?? "")
              : `#${String(row.document ?? "")}`
        void navigator.clipboard.writeText(value)
        toast.success(
          what === "link"
            ? "Link copied"
            : what === "id"
              ? "ID copied"
              : "Number copied",
        )
      }}
      onInspectorSwitchLayout={() => toast.success("Switch layout (demo)")}
    />
  )
}

/**
 * The row Inspector, one entry per tab. `details` is BUILT FROM the row's own
 * columns and its editable fields commit straight back into the table row (the
 * archetype re-derives the inspected row by id, so the edit shows in both the
 * grid and the inspector). `activity` / `related` are non-column demo tabs.
 * Tabs not returned here are not shown (the rail lists only tabs with content).
 */
function buildInspectorTabs(
  row: TableSectionRow,
  commit: (rowId: string, field: string, value: TableCellValue) => void,
): Partial<Record<InspectorTab, React.ReactNode>> {
  const id = String(row.id)
  const doc = String(row.document ?? "")
  const partner = String(row.partner ?? "")
  const status = String(row.status ?? "")
  const amount = Number(row.amount ?? 0)
  const net = Math.round(amount * 0.8 * 100) / 100
  const vat = Math.round((amount - net) * 100) / 100

  return {
    details: (
      <SectionList
        sections={[
          sectionInspectorKeyDetails({
            lines: [
              {
                label: "Document",
                value: doc,
                icon: "HashIcon",
                readOnly: true,
              },
              {
                label: "Partner",
                value: partner,
                icon: "Building2",
                onChange: (next) => commit(id, "partner", next),
              },
              {
                label: "Status",
                value: status,
                type: "select",
                options: STATUS_OPTIONS,
                icon: "CheckCircle2",
                onChange: (next) => commit(id, "status", next),
              },
              {
                label: "Amount",
                value: amount,
                type: "money",
                currency: "CZK",
                readOnly: true,
              },
              {
                label: "Issued",
                value: String(row.issuedOn ?? ""),
                type: "date",
                icon: "CalendarIcon",
                onChange: (next) => commit(id, "issuedOn", next),
              },
              {
                label: "Note",
                value: String(row.note ?? ""),
                icon: "TextInitialIcon",
                onChange: (next) => commit(id, "note", next),
              },
            ],
          }),
          sectionInspectorMoneyTotals({
            title: "Totals",
            rows: [
              { label: "Net", amount: net },
              { label: "VAT 21%", amount: vat },
              { label: "Total", amount, emphasis: true },
            ],
          }),
        ]}
      />
    ),
    activity: (
      <SectionList
        sections={[
          sectionInspectorActivityLog({
            title: "Activity",
            entries: [
              {
                id: "a1",
                field: "Status",
                before: "draft",
                after: status,
                when: "10:15",
                by: "You",
                onUndo: () => commit(id, "status", "draft"),
              },
              {
                id: "a2",
                field: "Amount",
                before: "0",
                after: String(amount),
                when: "10:12",
                by: "You",
                onUndo: () => commit(id, "amount", 0),
              },
            ],
          }),
        ]}
      />
    ),
    related: (
      <SectionList
        sections={[
          sectionInspectorLinkedRecords({
            title: "Relations",
            addLabel: "Link a document",
            onAdd: () => toast.success("Link a record (demo)"),
            onRemove: (linkedId) =>
              toast.success(`Unlinked ${linkedId} (demo)`),
            items: [
              {
                id: "partner",
                relation: "Partner",
                label: partner,
                meta: "Counterparty",
                icon: "Building2",
              },
            ],
          }),
        ]}
      />
    ),
  }
}
