"use client"

/**
 * Font Awesome (free-solid) icon pack.
 *
 * Font Awesome uses an icon-prop API (`<FontAwesomeIcon icon={faX} />`)
 * instead of named components. To match the pack contract — every
 * entry must be a `React.ComponentType<SVGProps>` — each canonical
 * name is wrapped in a tiny component that forwards SVG props to
 * `FontAwesomeIcon`. The wrapper is memoized by definition so React
 * doesn't churn refs on every render.
 *
 * Required `"use client"`: `@fortawesome/fontawesome-svg-core` calls
 * `React.createContext()`-equivalent module init that doesn't survive
 * the RSC runtime cleanly. Treat as client-only — server pulling this
 * via the icon-packs barrel gets a client reference, not the module
 * body.
 */
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core"
import {
  faAnglesLeft,
  faAnglesRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowUpRightFromSquare,
  faArrowsRotate,
  faBan,
  faBars,
  faBatteryFull,
  faBell,
  faBookOpen,
  faBookOpenReader,
  faBookmark,
  faBox,
  faBoxArchive,
  faBriefcase,
  faBug,
  faBuilding,
  faCalculator,
  faCalendar,
  faChalkboardUser,
  faChartColumn,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleCheck,
  faCircleInfo,
  faCirclePlus,
  faCircleXmark,
  faClipboard,
  faClockRotateLeft,
  faCode,
  faCommentDots,
  faCompress,
  faCopy,
  faDesktop,
  faDownload,
  faEllipsis,
  faEnvelope,
  faEraser,
  faExpand,
  faEye,
  faEyeSlash,
  faFile,
  faFileAudio,
  faFileCode,
  faFileExcel,
  faFileImage,
  faFileLines,
  faFileVideo,
  faFileZipper,
  faFilter,
  faFilterCircleXmark,
  faFolderOpen,
  faGear,
  faGlobe,
  faGraduationCap,
  faHashtag,
  faHeartPulse,
  faHouse,
  faInbox,
  faKey,
  faLifeRing,
  faLink,
  faList,
  faListCheck,
  faLock,
  faMagnifyingGlass,
  faMaximize,
  faMessage,
  faMinimize,
  faMinus,
  faMoneyBill,
  faMoon,
  faPalette,
  faPaperPlane,
  faPen,
  faPiggyBank,
  faPlus,
  faRotateLeft,
  faScissors,
  faShield,
  faSliders,
  faSpinner,
  faSquare,
  faSquareCheck,
  faStar,
  faStarHalfStroke,
  faSun,
  faT,
  faTableColumns,
  faTerminal,
  faTrash,
  faTriangleExclamation,
  faTrophy,
  faUpload,
  faUser,
  faUserPlus,
  faUsers,
  faVolumeHigh,
  faWandMagicSparkles,
  faWifi,
  faXmark,
  faBullseye,
  faCalendarDays,
  faChartLine,
  faFolder,
  faIdCard,
  faSwatchbook,
  faAddressBook,
  faCircle,
  faCircleUser,
  faKeyboard,
  faCodePullRequest,
  faCircleQuestion,
  faShapes,
  faDiagramProject,
  faGlasses,
  faCreditCard,
} from "@fortawesome/free-solid-svg-icons"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import * as React from "react"

import type { IconComponent, IconMap } from "../types"

/**
 * Wrap a Font Awesome IconDefinition in a component matching
 * `IconComponent`. Memoized — same input definition = same component
 * identity, so React doesn't remount on every parent re-render.
 */
const wrapperCache = new WeakMap<IconDefinition, IconComponent>()

function wrap(definition: IconDefinition): IconComponent {
  const cached = wrapperCache.get(definition)
  if (cached) return cached
  const Component: IconComponent = (props) => (
    // Cast to a generic prop bag — FontAwesomeIcon's prop surface
    // differs from SVGProps, but the runtime forwards className,
    // style, aria-*, data-* fine. The cast appeases TypeScript
    // without narrowing the SVGProps surface IconComponent promises.
    <FontAwesomeIcon
      icon={definition}
      {...(props as Record<string, unknown>)}
    />
  )
  Component.displayName = `FA(${definition.iconName})`
  wrapperCache.set(definition, Component)
  return Component
}

export const fontawesomeIcons = {
  Activity: wrap(faHeartPulse), // FA free-solid has no `pulse`; HeartPulse is the closest activity glyph.
  AlertTriangle: wrap(faTriangleExclamation),
  Archive: wrap(faBoxArchive),
  ArrowDown: wrap(faArrowDown),
  ArrowLeft: wrap(faArrowLeft),
  ArrowRightIcon: wrap(faArrowRight),
  ArrowUp: wrap(faArrowUp),
  ArrowUpDown: wrap(faSliders), // No native dual-up-down glyph; sliders carries the same "swap order" affordance.
  ArrowUpRight: wrap(faArrowUpRightFromSquare),
  Award: wrap(faTrophy),
  Banknote: wrap(faMoneyBill),
  BarChart3: wrap(faChartColumn),
  BaselineIcon: wrap(faT),
  Battery: wrap(faBatteryFull),
  Bell: wrap(faBell),
  BookmarkIcon: wrap(faBookmark),
  BookOpen: wrap(faBookOpen),
  BookOpenText: wrap(faBookOpenReader),
  Box: wrap(faBox),
  Briefcase: wrap(faBriefcase),
  Bug: wrap(faBug),
  Building2: wrap(faBuilding),
  Calculator: wrap(faCalculator),
  CalendarIcon: wrap(faCalendar),
  Check: wrap(faCheck),
  CheckCircle2: wrap(faCircleCheck),
  CheckCircle2Icon: wrap(faCircleCheck),
  CheckIcon: wrap(faCheck),
  CheckSquareIcon: wrap(faSquareCheck),
  ChevronDown: wrap(faChevronDown),
  ChevronDownIcon: wrap(faChevronDown),
  ChevronLeft: wrap(faChevronLeft),
  ChevronLeftIcon: wrap(faChevronLeft),
  ChevronRight: wrap(faChevronRight),
  ChevronRightIcon: wrap(faChevronRight),
  ChevronUp: wrap(faChevronUp),
  ChevronUpIcon: wrap(faChevronUp),
  ChevronsLeft: wrap(faAnglesLeft),
  ChevronsRight: wrap(faAnglesRight),
  ChevronsUpDown: wrap(faSliders),
  ChevronsUpDownIcon: wrap(faSliders),
  CircleCheckIcon: wrap(faCircleCheck),
  ClipboardIcon: wrap(faClipboard),
  Code2: wrap(faCode),
  Copy: wrap(faCopy),
  CopyIcon: wrap(faCopy),
  Download: wrap(faDownload),
  Ellipsis: wrap(faEllipsis),
  EraserIcon: wrap(faEraser),
  Eye: wrap(faEye),
  EyeOff: wrap(faEyeSlash),
  File: wrap(faFile),
  FileArchive: wrap(faFileZipper),
  FileArchiveIcon: wrap(faFileZipper),
  FileAudio: wrap(faFileAudio),
  FileAudioIcon: wrap(faFileAudio),
  FileCodeIcon: wrap(faFileCode),
  FileCogIcon: wrap(faFile), // FA free has no FileCog; plain File is more honest than a wrong-semantic alternative.
  FileIcon: wrap(faFile),
  FileImage: wrap(faFileImage),
  FileSpreadsheet: wrap(faFileExcel),
  FileText: wrap(faFileLines),
  FileTextIcon: wrap(faFileLines),
  FileVideo: wrap(faFileVideo),
  FileVideoIcon: wrap(faFileVideo),
  FilterIcon: wrap(faFilter),
  FilterXIcon: wrap(faFilterCircleXmark),
  FolderOpen: wrap(faFolderOpen),
  Globe: wrap(faGlobe),
  GraduationCap: wrap(faGraduationCap),
  HashIcon: wrap(faHashtag),
  History: wrap(faClockRotateLeft),
  Home: wrap(faHouse),
  Inbox: wrap(faInbox),
  InfoIcon: wrap(faCircleInfo),
  KeyRound: wrap(faKey),
  LifeBuoy: wrap(faLifeRing),
  LinkIcon: wrap(faLink),
  ListChecksIcon: wrap(faListCheck),
  ListIcon: wrap(faList),
  Loader2: wrap(faSpinner),
  Loader2Icon: wrap(faSpinner),
  Lock: wrap(faLock),
  Mail: wrap(faEnvelope),
  Maximize: wrap(faMaximize),
  Maximize2: wrap(faExpand),
  MaximizeIcon: wrap(faMaximize),
  MessageCircle: wrap(faCommentDots),
  MessageSquare: wrap(faMessage),
  Minimize2: wrap(faMinimize),
  MinimizeIcon: wrap(faCompress),
  MinusIcon: wrap(faMinus),
  Monitor: wrap(faDesktop),
  Moon: wrap(faMoon),
  MoreHorizontal: wrap(faEllipsis),
  MoreHorizontalIcon: wrap(faEllipsis),
  OctagonXIcon: wrap(faBan), // FA free has no OctagonX; Ban is the closest "blocked" octagonal glyph.
  Palette: wrap(faPalette),
  // FA has no Sidebar; differentiate Open vs Close via Bars (open menu) vs TableColumns (split).
  PanelLeftClose: wrap(faTableColumns),
  PanelLeftIcon: wrap(faBars),
  PanelLeftOpen: wrap(faBars),
  PanelRight: wrap(faBars),
  PanelRightClose: wrap(faTableColumns),
  PanelRightOpen: wrap(faBars),
  Pencil: wrap(faPen),
  PiggyBank: wrap(faPiggyBank),
  Plus: wrap(faPlus),
  PlusCircle: wrap(faCirclePlus),
  PlusIcon: wrap(faPlus),
  Presentation: wrap(faChalkboardUser),
  RefreshCw: wrap(faArrowsRotate),
  RotateCcw: wrap(faRotateLeft),
  RotateCcwIcon: wrap(faRotateLeft),
  ScissorsIcon: wrap(faScissors),
  Search: wrap(faMagnifyingGlass),
  SearchIcon: wrap(faMagnifyingGlass),
  Send: wrap(faPaperPlane),
  Settings: wrap(faGear),
  Settings2: wrap(faSliders),
  Shield: wrap(faShield),
  Sparkles: wrap(faWandMagicSparkles), // FA free has no Sparkles in solid; WandMagicSparkles is the closest.
  Square: wrap(faSquare),
  Star: wrap(faStar),
  StarOff: wrap(faStarHalfStroke), // No native off-state; half-stroke is the closest "partial / unset" affordance.
  Sun: wrap(faSun),
  Terminal: wrap(faTerminal),
  TextInitialIcon: wrap(faT),
  Trash2: wrap(faTrash),
  Trash2Icon: wrap(faTrash),
  TriangleAlertIcon: wrap(faTriangleExclamation),
  Upload: wrap(faUpload),
  UploadIcon: wrap(faUpload),
  User: wrap(faUser),
  UserIcon: wrap(faUser),
  UserPlus: wrap(faUserPlus),
  Users: wrap(faUsers),
  Volume2: wrap(faVolumeHigh),
  Wifi: wrap(faWifi),
  X: wrap(faXmark),
  XCircle: wrap(faCircleXmark),
  XCircleIcon: wrap(faCircleXmark),
  XIcon: wrap(faXmark),
  // Rail nav additions — nearest Font Awesome free-solid glyphs.
  BriefcaseBusiness: wrap(faBriefcase),
  CalendarClock: wrap(faCalendarDays), // no calendar-clock; days is closest
  ChartNoAxesCombined: wrap(faChartLine),
  FolderBookmark: wrap(faFolder), // no folder-bookmark variant
  Goal: wrap(faBullseye),
  IdCard: wrap(faIdCard),
  SwatchBook: wrap(faSwatchbook),
  BookUser: wrap(faAddressBook),
  Circle: wrap(faCircle),
  CircleUser: wrap(faCircleUser),
  ListTodo: wrap(faListCheck),
  Keyboard: wrap(faKeyboard),
  GitPullRequestArrow: wrap(faCodePullRequest),
  Info: wrap(faCircleInfo),
  CircleHelp: wrap(faCircleQuestion),
  Blocks: wrap(faShapes),
  Workflow: wrap(faDiagramProject),
  HatGlasses: wrap(faGlasses),
  CreditCard: wrap(faCreditCard),
} satisfies IconMap
