-- 0029_accounting_posting.sql
--
-- v2 accounting — posting (header + double-entry line + monetary line) + signature.posting_id
--
-- Source: docs/specs/accounting-schema.sql (PG18-validated v2 design, #395 tip 0ea2bf31).
-- Regime spine. posting.depreciation_plan_id/inventory_count_id FKs activated in 0030.
-- Handwritten SQL (ADR-0009). One whole-file transaction; runs through the safe runner path.

BEGIN;

-- category (= kategorie) — peněžní-deník income/expense category (§5.7, §9).
CREATE TABLE category (
  id              uuid          PRIMARY KEY DEFAULT uuidv7(),
  organization_id uuid          NOT NULL REFERENCES organization (id),
  type            category_type NOT NULL,
  name            text          NOT NULL,
  created_at      timestamptz   NOT NULL DEFAULT now(),
  updated_at      timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT category_id_org_unique UNIQUE (id, organization_id)
);

-- posting (= ucetni_zapis) — the shared posting header (§12), made on the basis of a
-- doklad (§6/2). §5.2. For DAŇOVÁ EVIDENCE a TECHNICAL CONTAINER (§7b ZDP): the table
-- is reused as-is, columns stay NOT NULL. Append-only (R8; no updated_at).
CREATE TABLE posting (
  id                   uuid            PRIMARY KEY DEFAULT uuidv7(),
  organization_id      uuid            NOT NULL,
  period_id            uuid            NOT NULL,                  -- obdobi_id (§5.2); regime spine. A correction may post into a different OPEN period (R8/R12)
  regime_code          text            NOT NULL,                 -- pinned == accounting_period.regime_code via composite FK; lines need it for their FK
  summary_record_id    uuid            NOT NULL,                 -- doklad_id (§5.2, R2) — posting on the basis of a doklad (§6/2)
  accounting_event_id  uuid            NOT NULL,                 -- pripad_id (§5.2, R2) — which case is booked; one doklad may cover many cases (§11/1)
  depreciation_plan_id uuid,                                     -- odpisovy_plan_id (§5.2/§6) — set if generated by depreciation (UC-4)
  inventory_count_id   uuid,                                     -- inventura_id (§5.2/§6) — set if generated by inventory manko/přebytek (UC-4)
  posting_date         date            NOT NULL,                 -- datum (§5.2) — deník order + period membership; CHECK ∈ period (trigger)
  posting_kind         posting_kind    NOT NULL,                 -- druh (§5.2): SIMPLE | COMPOUND
  responsible_user_id  uuid            NOT NULL REFERENCES app_user (id),  -- odpovedna_osoba (§5.2, R10); MVP e-signature simplification
  posted_at            timestamptz     NOT NULL,                 -- okamzik_zauctovani (§5.2)
  corrects_posting_id  uuid,                                     -- opravuje_zapis_id (R8/§35) — self-FK; correction posts into an OPEN period
  correction_type      correction_type,                          -- set iff corrects_posting_id set
  is_opening           boolean         NOT NULL DEFAULT false,   -- B2: 701 počáteční-stav opening posting; read-model trigger EXCLUDES from turnover (sets opening_balance), still in deník
  created_at           timestamptz     NOT NULL DEFAULT now(),
  CONSTRAINT posting_id_org_unique        UNIQUE (id, organization_id),
  CONSTRAINT posting_id_period_unique     UNIQUE (id, period_id),                      -- B1: line.(posting_id, period_id) -> here, pins line.period == posting.period
  CONSTRAINT posting_id_org_regime_unique UNIQUE (id, organization_id, regime_code),  -- line-FK target (R7 spine)
  CONSTRAINT posting_period_regime_fk FOREIGN KEY (period_id, organization_id, regime_code)
    REFERENCES accounting_period (id, organization_id, regime_code),                  -- REGIME SPINE
  CONSTRAINT posting_summary_fk FOREIGN KEY (summary_record_id, organization_id)
    REFERENCES summary_record (id, organization_id),                                  -- R2
  CONSTRAINT posting_event_fk FOREIGN KEY (accounting_event_id, organization_id)
    REFERENCES accounting_event (id, organization_id),                               -- R2
  CONSTRAINT posting_correction_fk FOREIGN KEY (corrects_posting_id, organization_id, regime_code)
    REFERENCES posting (id, organization_id, regime_code),
  CONSTRAINT posting_correction_pair_chk CHECK ((corrects_posting_id IS NULL) = (correction_type IS NULL))
  -- depreciation_plan_id / inventory_count_id FKs are ACTIVATED via ALTER after the
  -- supporting tables are created (see "Activate deferred posting FKs" below).
  -- TRIGGERS (migration): append-only block; closed-period + posting_date ∈ [period_start, period_end] (R12, V2-DEFERRED).
);

-- posting_double_entry_line (= zapis_radek) — one Má dáti / Dal side (§13/2). §5.3.
-- The posted form of a partial_record (dílčí). PODVOJNÉ only (R7).
CREATE TABLE posting_double_entry_line (
  id                uuid          PRIMARY KEY DEFAULT uuidv7(),
  organization_id   uuid          NOT NULL,
  posting_id        uuid          NOT NULL,                      -- zapis_id (§5.3)
  period_id         uuid          NOT NULL,                      -- B1: = posting's period; pins the account to the posting's period chart
  regime_code       text          NOT NULL,                     -- CHECK = 'DOUBLE_ENTRY' (R7); composite FK carries tenancy+regime
  account_id        uuid          NOT NULL,                      -- ucet_id (§5.3, R1) — valid account from the org chart
  partial_record_id uuid,                                        -- dilci_id (§5.3) "Zaúčtování" §6/2; nullable for generated postings (701, depreciation, storno)
  side              debit_credit  NOT NULL,                      -- strana (§5.3): MD | Dal
  amount            numeric(19,4) NOT NULL,                      -- castka (§5.3, R13); may be negative (storno)
  created_at        timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT posting_de_line_regime_chk CHECK (regime_code = 'DOUBLE_ENTRY'),
  CONSTRAINT posting_de_line_posting_fk FOREIGN KEY (posting_id, organization_id, regime_code)
    REFERENCES posting (id, organization_id, regime_code),
  CONSTRAINT posting_de_line_posting_period_fk FOREIGN KEY (posting_id, period_id)
    REFERENCES posting (id, period_id),                                              -- B1: line.period == posting.period
  CONSTRAINT posting_de_line_account_fk FOREIGN KEY (account_id, organization_id)
    REFERENCES account (id, organization_id),                                        -- R1 (tenancy)
  CONSTRAINT posting_de_line_account_period_fk FOREIGN KEY (account_id, period_id)
    REFERENCES account (id, period_id),                                             -- B1: account is in THIS period's chart (closes cross-period hole)
  CONSTRAINT posting_de_line_partial_fk FOREIGN KEY (partial_record_id, organization_id)
    REFERENCES partial_record (id, organization_id)                                  -- §6/2; NOT unique (1 dílčí -> many lines)
  -- TRIGGERS (migration): append-only; closed-period+date via parent; R4 balance =
  --   CONSTRAINT TRIGGER DEFERRABLE INITIALLY DEFERRED, per posting:
  --   count(*) >= 2 AND SUM(amount) FILTER(side=DEBIT) = SUM(amount) FILTER(side=CREDIT)
  --   [>= 2 closes the v1 empty-entry hole]. Never fires for cash postings.
);

-- posting_monetary_line (= penezni_denik_radek) — one classified peněžní-deník row
-- (§13b / §7b). §5.4 + §9. The posted form of a partial_record in cash-book format.
-- JEDNODUCHÉ / DAŇOVÁ EVIDENCE only (R7). A single cash movement may need several rows (§9).
CREATE TABLE posting_monetary_line (
  id                uuid           PRIMARY KEY DEFAULT uuidv7(),
  organization_id   uuid           NOT NULL,
  posting_id        uuid           NOT NULL,                     -- zapis_id (§5.4)
  regime_code       text           NOT NULL,                     -- CHECK IN ('SINGLE_ENTRY','TAX_RECORDS') (R7)
  partial_record_id uuid,                                        -- dilci_id (§5.4) "Zaúčtování" §6/2; nullable
  category_id       uuid,                                        -- kategorie_id (§5.4, §9); nullable (generated postings)
  location          monetary_location  NOT NULL,                     -- misto (§5.4): CASH | BANK
  direction         monetary_direction NOT NULL,                     -- smer (§5.4): INFLOW | OUTFLOW
  is_tax_relevant   boolean        NOT NULL,                     -- danovy (§5.4, §9)
  is_clearing       boolean        NOT NULL DEFAULT false,       -- prubezny (§5.4, §9): průběžná položka
  tax_base          numeric(19,4),                               -- zaklad_dane (§5.4, §9); nullable
  amount            numeric(19,4)  NOT NULL,                      -- castka (§5.4, R13)
  created_at        timestamptz    NOT NULL DEFAULT now(),
  CONSTRAINT posting_monetary_line_regime_chk CHECK (regime_code IN ('SINGLE_ENTRY','TAX_RECORDS')),
  CONSTRAINT posting_monetary_line_posting_fk FOREIGN KEY (posting_id, organization_id, regime_code)
    REFERENCES posting (id, organization_id, regime_code),
  CONSTRAINT posting_monetary_line_partial_fk FOREIGN KEY (partial_record_id, organization_id)
    REFERENCES partial_record (id, organization_id),
  CONSTRAINT posting_monetary_line_category_fk FOREIGN KEY (category_id, organization_id)
    REFERENCES category (id, organization_id)                                        -- §5.4
  -- TRIGGERS (migration): append-only; closed-period+date via parent.
);

-- signature.posting_id amendment — the FOR_POSTING role link (= v1 podpis.zapis_id,
-- §5.6 / §33a/4). Added here because it FKs the posting table defined above. The CHECK
-- enforces exactly-one-of (event_id, posting_id), keyed on role.
ALTER TABLE signature
  ADD COLUMN posting_id uuid,
  ADD CONSTRAINT signature_posting_fk FOREIGN KEY (posting_id, organization_id)
    REFERENCES posting (id, organization_id),
  ADD CONSTRAINT signature_role_target_chk CHECK (
    (role = 'FOR_EVENT'   AND event_id IS NOT NULL AND posting_id IS NULL) OR
    (role = 'FOR_POSTING' AND posting_id IS NOT NULL AND event_id IS NULL)
  );

COMMIT;
