-- 0081_financial_institution_seed.sql
--
-- ČNB bank-code register seed (52 rows). GENERATED by
-- packages/db/scripts/gen-bank-seed.ts from packages/db/data/bank.json. Idempotent
-- (ON CONFLICT DO NOTHING). Re-generate with the script; do not hand-edit rows.
-- Display names are NOT seeded here — they localize via next-intl (bankNames).

BEGIN;

INSERT INTO financial_institution (bank_code) VALUES
  ('0100'),
  ('0300'),
  ('0600'),
  ('0710'),
  ('0800'),
  ('2010'),
  ('2020'),
  ('2030'),
  ('2040'),
  ('2050'),
  ('2060'),
  ('2070'),
  ('2100'),
  ('2200'),
  ('2210'),
  ('2220'),
  ('2230'),
  ('2240'),
  ('2250'),
  ('2310'),
  ('2600'),
  ('2700'),
  ('3030'),
  ('3500'),
  ('4000'),
  ('4300'),
  ('5000'),
  ('5400'),
  ('5500'),
  ('5800'),
  ('6000'),
  ('6100'),
  ('6200'),
  ('6210'),
  ('6300'),
  ('6363'),
  ('6700'),
  ('6800'),
  ('7910'),
  ('7940'),
  ('7950'),
  ('7960'),
  ('7970'),
  ('7980'),
  ('7990'),
  ('8030'),
  ('8040'),
  ('8060'),
  ('8090'),
  ('8150'),
  ('8200'),
  ('9910')
ON CONFLICT (bank_code) DO NOTHING;

COMMIT;
