-- 0083_constant_symbol_seed.sql
--
-- Konstantní symbol register seed (15 rows). GENERATED by
-- packages/db/scripts/gen-constant-symbol-seed.ts from
-- packages/db/data/constant-symbol.json. Idempotent (ON CONFLICT DO NOTHING).
-- Re-generate with the script; do not hand-edit rows. Display names are NOT
-- seeded here — they localize via next-intl (constantSymbolNames).

BEGIN;

INSERT INTO constant_symbol (code) VALUES
  ('0008'),
  ('0058'),
  ('0108'),
  ('0138'),
  ('0168'),
  ('0208'),
  ('0308'),
  ('0358'),
  ('0379'),
  ('0408'),
  ('0479'),
  ('0558'),
  ('0748'),
  ('4648'),
  ('7618')
ON CONFLICT (code) DO NOTHING;

COMMIT;
