-- 0085_payment_form_seed.sql
--
-- Forma úhrady register seed (8 rows). GENERATED by
-- packages/db/scripts/gen-payment-form-seed.ts from packages/db/data/payment-form.json.
-- Idempotent (ON CONFLICT DO NOTHING). Re-generate with the script; do not hand-edit
-- rows. Names + invoice phrases are NOT seeded here — they localize via next-intl
-- (paymentFormNames / paymentFormPhrases).

BEGIN;

INSERT INTO payment_form (code, offer_on_invoice, offer_on_cash_desk, offer_on_pos) VALUES
  ('DOBIRKA', true, false, false),
  ('HOTOVE', true, true, true),
  ('KARTA', true, true, true),
  ('NESPECIFIKOVANO', true, false, false),
  ('PREVOD', true, false, false),
  ('SEK', true, false, false),
  ('SLOZENKA', true, false, false),
  ('ZAPOCET', true, false, false)
ON CONFLICT (code) DO NOTHING;

COMMIT;
