#!/usr/bin/env tsx
/**
 * App-structure snapshot generator.
 *
 * `apps/api` (NestJS) cannot import the org nav trees — they live in
 * `apps/web/app/[orgSlug]/_nav`, which is Next.js app-router source (no package
 * export, stripped from the prod image by `output: "standalone"`). So instead
 * of moving the nav into a shared package + rewriting the GUI adapter, this
 * script reads the typed nav at build time — the exact repo-root import
 * `scripts/check-nav.ts` already relies on — and emits a committed data
 * snapshot the api controller serves:
 *
 *   apps/web nav.ts trees  ──(this script)──►  apps/api/.../structure.data.ts
 *
 * The snapshot is the flat-per-module shape from `packages/shared/src/api/
 * structure.ts` (group is a page attribute, not a nested node) — codegen-safe,
 * no recursion. Per-page `archetype`/`purpose` come from the sparse
 * `PAGE_ANNOTATIONS` map; a route absent there yields null.
 *
 * `--check` regenerates in memory and fails (exit 1) if the committed snapshot
 * is stale — the drift guard. Wired into `pnpm gen:all` + a lefthook
 * `structure-drift` hook (mirrors `nav-drift` / `sitemap-drift`).
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import type {
  SidebarNavEntry,
  SidebarNavPage,
} from "@workspace/ui/blocks/sidebar-panel"

import {
  MODULE_NAV,
  moduleKeyFromHref,
  orgRailNav,
} from "../apps/web/app/[orgSlug]/_nav/org-nav"
import {
  PAGE_ANNOTATIONS,
  type GetStructureResponse,
  type NavPage,
  type NavSubpage,
} from "../packages/shared/src/api/structure"

const SLUG = "__slug__"
const here = dirname(fileURLToPath(import.meta.url))
const OUT_FILE = join(
  here,
  "..",
  "apps",
  "api",
  "src",
  "v1",
  "structure",
  "structure.data.ts",
)

/** Strip the placeholder slug prefix → org-relative route ("" = module index). */
function toRoute(href: string): string {
  return href.replace(`/${SLUG}`, "").replace(/^\//, "")
}

const seenRoutes = new Set<string>()

function toSubpage(
  s: NonNullable<SidebarNavPage["subpages"]>[number],
): NavSubpage {
  const route = toRoute(s.href)
  seenRoutes.add(route)
  const ann = PAGE_ANNOTATIONS[route] ?? {}
  return {
    label: s.label,
    route,
    tba: s.tba ?? false,
    archetype: ann.archetype ?? null,
    purpose: ann.purpose ?? null,
  }
}

function toPage(p: SidebarNavPage, group: string | null): NavPage {
  const route = toRoute(p.href)
  seenRoutes.add(route)
  const ann = PAGE_ANNOTATIONS[route] ?? {}
  return {
    group,
    label: p.label,
    route,
    icon: p.icon,
    tba: p.tba ?? false,
    archetype: ann.archetype ?? null,
    purpose: ann.purpose ?? null,
    subpages: (p.subpages ?? []).map(toSubpage),
  }
}

/** Flatten a module's sidebar tree to a flat page list (group → page attribute). */
function flatten(tree: SidebarNavEntry[]): NavPage[] {
  const pages: NavPage[] = []
  for (const entry of tree) {
    if ("href" in entry) {
      pages.push(toPage(entry, null))
    } else {
      for (const page of entry.pages) pages.push(toPage(page, entry.label))
    }
  }
  return pages
}

function build(): GetStructureResponse {
  const modules: GetStructureResponse["modules"] = []
  for (const entry of orgRailNav(SLUG)) {
    if (entry === "separator") continue
    const key = moduleKeyFromHref(entry.href, SLUG)
    const base = key ? `/${SLUG}/${key}` : `/${SLUG}`
    const builder = MODULE_NAV[key]
    if (!builder) throw new Error(`No MODULE_NAV builder for key "${key}"`)
    modules.push({
      key,
      label: entry.label,
      route: key,
      icon: entry.icon,
      pages: flatten(builder(base)),
    })
  }

  // Drift guard: an annotation keyed on a route that no longer exists is stale.
  const stale = Object.keys(PAGE_ANNOTATIONS).filter((r) => !seenRoutes.has(r))
  if (stale.length > 0) {
    throw new Error(
      `PAGE_ANNOTATIONS keys not found in the nav tree (stale — fix in ` +
        `packages/shared/src/api/structure.ts):\n  ${stale.join("\n  ")}`,
    )
  }
  return { modules }
}

function render(data: GetStructureResponse): string {
  return (
    "// AUTO-GENERATED by scripts/gen-structure.ts — do not edit.\n" +
    "// Regenerate with `pnpm gen:structure` (runs inside `pnpm gen:all`).\n" +
    'import type { GetStructureResponse } from "@workspace/shared/api"\n' +
    "\n" +
    "export const APP_STRUCTURE: GetStructureResponse = " +
    JSON.stringify(data, null, 2) +
    "\n"
  )
}

function main(): void {
  const check = process.argv.includes("--check")
  const next = render(build())
  if (check) {
    const current = readFileSync(OUT_FILE, "utf8")
    if (current !== next) {
      process.stderr.write(
        "[gen-structure] structure.data.ts is stale. Run `pnpm gen:structure` and commit.\n",
      )
      process.exit(1)
    }
    process.stdout.write(
      "[gen-structure] OK — snapshot in sync with the nav.\n",
    )
    return
  }
  mkdirSync(dirname(OUT_FILE), { recursive: true })
  writeFileSync(OUT_FILE, next)
  process.stdout.write(`[gen-structure] wrote ${OUT_FILE}\n`)
}

main()
