#!/usr/bin/env bash
# Generate apps/web/.env.local with random secrets for local development.
#
# Idempotent-ish: if the file already exists, this script aborts unless --force is passed.
# Secrets are derived from `openssl rand -base64 33` (264 bits, safely > 32 bytes).
#
# Usage:
#   bash scripts/generate-env.sh           # create if absent
#   bash scripts/generate-env.sh --force   # overwrite existing
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${ROOT}/apps/web/.env.local"

if [ -e "$TARGET" ] && [ "${1:-}" != "--force" ]; then
  echo "Refusing to overwrite existing $TARGET (pass --force to overwrite)."
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets."
  exit 1
fi

BETTER_AUTH_SECRET="$(openssl rand -base64 33)"
APP_TOKEN_SECRET="$(openssl rand -base64 33)"

cat > "$TARGET" <<EOF
# Generated by scripts/generate-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Never commit this file.

# App runtime: connect through pgBouncer (transaction mode, port 6432) as app_user.
# FORCE RLS applies on this connection. Matches infra/compose/docker-compose.dev.yml.
DATABASE_URL=postgres://app_user:dev_user@localhost:6432/app_dev
# Migration runner + admin scripts: direct Postgres (port 5432) as app_owner.
# Required by packages/db migration runner (it rejects pgBouncer port 6432).
DATABASE_DIRECT_URL=postgres://app_owner:dev_owner@localhost:5432/app_dev

BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
BETTER_AUTH_URL=http://localhost:3000
NEXT_PUBLIC_BETTER_AUTH_URL=http://localhost:3000
BETTER_AUTH_TRUSTED_ORIGINS=http://localhost:3000

APP_TOKEN_SECRET=${APP_TOKEN_SECRET}

# Email transport: leave RESEND_API_KEY empty to log emails to the console
# in dev. See packages/email for the runtime decision.
RESEND_API_KEY=
EMAIL_FROM=no-reply@localhost
EOF

chmod 600 "$TARGET"
echo "Wrote $TARGET (chmod 600)."
echo "Secrets generated:"
echo "  BETTER_AUTH_SECRET    (33 bytes base64)"
echo "  APP_TOKEN_SECRET      (33 bytes base64)"
