#!/usr/bin/env bash
# Generate apps/web/.env.local with random secrets for local development.
#
# Idempotent-ish: if the file already exists, this script aborts unless --force is passed.
# Secrets are derived from `openssl rand -base64 33` (264 bits, safely > 32 bytes).
#
# Optional environment overrides (used by the Conductor per-workspace setup so
# each parallel workspace binds its own port + isolated database):
#   WEB_PORT        listen port + auth base-URL origin port   (default 3000)
#   DB_URL          DATABASE_URL (app runtime, role app_user)  (default pgBouncer app_dev)
#   DB_DIRECT_URL   DATABASE_DIRECT_URL (migrations, app_owner) (default direct app_dev)
#
# Usage:
#   bash scripts/generate-env.sh           # create if absent
#   bash scripts/generate-env.sh --force   # overwrite existing
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${ROOT}/apps/web/.env.local"

if [ -e "$TARGET" ] && [ "${1:-}" != "--force" ]; then
  echo "Refusing to overwrite existing $TARGET (pass --force to overwrite)."
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets."
  exit 1
fi

WEB_PORT="${WEB_PORT:-3000}"
DB_URL="${DB_URL:-postgres://app_user:dev_user@localhost:6432/app_dev}"
DB_DIRECT_URL="${DB_DIRECT_URL:-postgres://app_owner:dev_owner@localhost:5432/app_dev}"
BETTER_AUTH_SECRET="$(openssl rand -base64 33)"
APP_TOKEN_SECRET="$(openssl rand -base64 33)"
ORIGIN="http://localhost:${WEB_PORT}"

# Create the secret file 0600 from the start (no world-readable window before
# the trailing chmod).
umask 077

cat > "$TARGET" <<EOF
# Generated by scripts/generate-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Never commit this file. Canonical reference: apps/web/.env.example.

# App runtime DB connection (role app_user). FORCE RLS applies here.
DATABASE_URL=${DB_URL}
# Migration runner + admin scripts: direct Postgres as app_owner.
# Required by the packages/db migration runner (it rejects pgBouncer port 6432).
DATABASE_DIRECT_URL=${DB_DIRECT_URL}

# Identity session signing (Better Auth) + AI-tool token signing. Independent of
# the password hash, so a per-workspace random value is safe once seeded.
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
APP_TOKEN_SECRET=${APP_TOKEN_SECRET}

# Dev listen port + auth origin. The auth base-URL resolver keys cookie scope
# and email links off these, so an isolated workspace on its own port still
# produces working links.
PORT=${WEB_PORT}
BETTER_AUTH_URL=${ORIGIN}
NEXT_PUBLIC_BETTER_AUTH_URL=${ORIGIN}
BETTER_AUTH_TRUSTED_ORIGINS=${ORIGIN}

# Email transport: leave RESEND_API_KEY empty to log emails to the console
# in dev. See packages/email for the runtime decision. The forgot-password
# reset URL is printed to the dev-server console — copy it to test the flow.
RESEND_API_KEY=
EMAIL_FROM=no-reply@localhost

# Dev-only HTTP endpoints (second gate alongside NODE_ENV check).
# Set to 0 or remove to disable the endpoint even in dev.
ENABLE_DEV_OUTBOX=1
ENABLE_DEV_PREVIEW=1

# S3 document store (packages/storage). Points at the dev-compose minio, which
# seeds the documents-dev bucket. No CMK locally (DOCUMENTS_KMS_KEY_ID unset →
# no SSE-KMS enforcement in dev). Credentials are DOCUMENT-STORE-SCOPED, not the
# global AWS_ACCESS_KEY_ID — so avatar-storage (real APP_BUCKET) keeps using the
# normal provider chain instead of inheriting the minio dev keys. Non-secret dev
# defaults matching infra/compose/docker-compose.dev.yml.
S3_ENDPOINT=http://localhost:9000
DOCUMENTS_BUCKET=documents-dev
AWS_REGION=eu-central-1
DOCUMENTS_S3_ACCESS_KEY_ID=dev_minio
DOCUMENTS_S3_SECRET_ACCESS_KEY=dev_minio_password
EOF

chmod 600 "$TARGET"
echo "Wrote $TARGET (chmod 600) — port ${WEB_PORT}, db ${DB_DIRECT_URL##*/}."
