#!/usr/bin/env bash
# Generate apps/admin/.env.local for local development.
#
# The admin app shares the workspace's Postgres database + Better Auth secret
# with the web app (same isolated ws_p<port> DB), but runs under its own
# origin/port and gates access with ADMIN_WORKSPACE_ALLOWLIST (a comma-separated
# list of workspace ids; empty = deny everyone). The Conductor setup script
# calls this after seeding, passing the seeded workspace id so the demo owner
# can reach admin.
#
# Required environment:
#   DB_URL              app_user connection to the workspace DB (FORCE RLS)
#   ADMIN_PORT          admin dev port ($CONDUCTOR_PORT + 2)
#   WEB_PORT, API_PORT  sibling app ports (for base-URL wiring)
#   WS_ALLOWLIST        comma-separated workspace ids allowed into admin
#   BETTER_AUTH_SECRET, APP_TOKEN_SECRET   reused from the web env (shared DB)
set -euo pipefail

: "${DB_URL:?DB_URL required}"
: "${ADMIN_PORT:?ADMIN_PORT required}"
: "${WEB_PORT:?WEB_PORT required}"
: "${API_PORT:?API_PORT required}"
: "${BETTER_AUTH_SECRET:?BETTER_AUTH_SECRET required}"
: "${APP_TOKEN_SECRET:?APP_TOKEN_SECRET required}"
WS_ALLOWLIST="${WS_ALLOWLIST:-}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${ROOT}/apps/admin/.env.local"
ORIGIN="http://localhost:${ADMIN_PORT}"

umask 077
cat > "$TARGET" <<EOF
# Generated by scripts/generate-admin-env.sh — never commit this file.
# Canonical reference: apps/admin/.env.example.

# Same isolated workspace database as apps/web (role app_user, FORCE RLS).
DATABASE_URL=${DB_URL}

# Auth: shared secret with web (same DB), but admin runs under its own origin.
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
APP_TOKEN_SECRET=${APP_TOKEN_SECRET}
BETTER_AUTH_URL=${ORIGIN}
NEXT_PUBLIC_BETTER_AUTH_URL=${ORIGIN}
BETTER_AUTH_TRUSTED_ORIGINS=${ORIGIN}

# Admin access gate: only members of these workspace ids can enter. Set to the
# seeded workspace so owner@example.com gets in. Empty denies everyone.
ADMIN_WORKSPACE_ALLOWLIST=${WS_ALLOWLIST}

# Sibling app origins.
WEB_BASE_URL=http://localhost:${WEB_PORT}
API_BASE_URL=http://localhost:${API_PORT}
API_INTERNAL_URL=http://localhost:${API_PORT}

# Email: empty -> console transport in dev.
RESEND_API_KEY=
EMAIL_FROM=no-reply@localhost
EOF

chmod 600 "$TARGET"
echo "Wrote $TARGET (admin, port ${ADMIN_PORT}, allowlist ${WS_ALLOWLIST:-<empty>})."
