import { isFavorited, toggleFavorite } from "@/lib/org/favorite-actions"

import { ArchetypeTableView } from "./archetype-table-view"

export const metadata = { title: "Archetype Table" }

/**
 * Settings → Debug → Archetype Table — the reference page for the **Table**
 * archetype: ContentHeader (with views + favorite) · a ContentToolbar whose
 * per-column filter is AUTO-GENERATED by the archetype · ContentBody with the
 * Table section · a selection ContentFooter. The archetype is minted inside the
 * client `ArchetypeTableView` (branded descriptors can't cross RSC); the favorite
 * star is threaded in as a bound server action (it is a required part of the
 * Table archetype).
 */
export default async function ArchetypeTablePage({
  params,
}: {
  params: Promise<{ orgSlug: string }>
}) {
  const { orgSlug } = await params
  const route = "settings/debug/archetype-table"
  const active = await isFavorited({ slug: orgSlug, route })

  async function onToggleFavorite() {
    "use server"
    const result = await toggleFavorite({
      slug: orgSlug,
      route,
      module: "debug",
      label: "Archetype Table",
    })
    if (!result.ok) throw new Error("favorite toggle failed")
    return result.favorited
  }

  return (
    <ArchetypeTableView
      favorite={{ initialActive: active, onToggle: onToggleFavorite }}
    />
  )
}
