import { Controller, Get } from "@nestjs/common"
import { ApiOkResponse, ApiOperation, ApiTags } from "@nestjs/swagger"
import {
  ARCHETYPES,
  type GetStructureResponse,
  type ListArchetypesResponse,
} from "@workspace/shared/api"

import { APP_STRUCTURE } from "./structure.data"

/**
 * `GET /v1/structure` + `GET /v1/structure/archetypes` — the org application's
 * information architecture, for agents to discover the surface outside the GUI.
 *
 * `APP_STRUCTURE` is a build-time snapshot of the typed `nav.ts` trees
 * (generated by `scripts/gen-structure.ts`); `ARCHETYPES` is the static layout
 * catalog. Both are tenant-agnostic static data — no DB, no tenant read.
 *
 * Public endpoints (no API key); the IA is identical for every org and carries
 * no tenant data.
 */
@ApiTags("Structure")
@Controller({ path: "structure", version: "1" })
export class StructureController {
  @Get()
  @ApiOperation({
    summary: "Get application structure",
    description:
      "Returns the ten rail modules with their full page tree, build-status, " +
      "and layout archetype. Public — no API key required.",
  })
  @ApiOkResponse({ description: "The full application structure." })
  getStructure(): GetStructureResponse {
    return APP_STRUCTURE
  }

  @Get("archetypes")
  @ApiOperation({
    summary: "List layout archetypes",
    description:
      "Returns the five content-panel layout archetypes and their slot " +
      "contract. Public — no API key required.",
  })
  @ApiOkResponse({ description: "The layout-archetype catalog." })
  listArchetypes(): ListArchetypesResponse {
    return { archetypes: ARCHETYPES }
  }
}
