// AUTO-GENERATED by scripts/gen-structure.ts — do not edit.
// Regenerate with `pnpm gen:structure` (runs inside `pnpm gen:all`).
import type { GetStructureResponse } from "@workspace/shared/api"

export const APP_STRUCTURE: GetStructureResponse = {
  "modules": [
    {
      "key": "",
      "label": "Company",
      "route": "",
      "icon": "Goal",
      "pages": [
        {
          "group": null,
          "label": "Overview",
          "route": "",
          "icon": "Goal",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": null,
          "label": "Inbox",
          "route": "inbox",
          "icon": "Inbox",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": null,
          "label": "Tasks",
          "route": "tasks",
          "icon": "ListTodo",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Profile",
          "label": "Company card",
          "route": "profile",
          "icon": "Building2",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Profile",
          "label": "People",
          "route": "people",
          "icon": "Users",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Engagement",
          "label": "Services",
          "route": "services",
          "icon": "Blocks",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Engagement",
          "label": "Onboarding",
          "route": "onboarding",
          "icon": "GraduationCap",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        }
      ]
    },
    {
      "key": "accounting",
      "label": "Accounting",
      "route": "accounting",
      "icon": "Calculator",
      "pages": [
        {
          "group": null,
          "label": "Overview",
          "route": "accounting",
          "icon": "Calculator",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Books",
          "label": "Cash journal",
          "route": "accounting/cash-journal",
          "icon": "Banknote",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Books",
          "label": "Journal",
          "route": "accounting/journal",
          "icon": "BookOpen",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Books",
          "label": "General ledger",
          "route": "accounting/ledger",
          "icon": "BookOpenText",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Books",
          "label": "Saldokonto",
          "route": "accounting/saldokonto",
          "icon": "ArrowUpDown",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Books",
          "label": "Off-balance ledger",
          "route": "accounting/off-balance",
          "icon": "BookmarkIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Books",
          "label": "Analytical ledger",
          "route": "accounting/analytical",
          "icon": "ListIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Books",
          "label": "Trial balance",
          "route": "accounting/trial-balance",
          "icon": "BarChart3",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Structure",
          "label": "Chart of accounts",
          "route": "accounting/chart-of-accounts",
          "icon": "Shapes",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Structure",
          "label": "Categories",
          "route": "accounting/categories",
          "icon": "Box",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Structure",
          "label": "Posting rules",
          "route": "accounting/posting-rules",
          "icon": "Workflow",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Structure",
          "label": "Posting checks",
          "route": "accounting/posting-checks",
          "icon": "CheckCircle2",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Structure",
          "label": "Opening balances",
          "route": "accounting/opening-balances",
          "icon": "Pencil",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "VAT",
          "label": "VAT ledger",
          "route": "accounting/vat-ledger",
          "icon": "FileSpreadsheet",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Input VAT",
              "route": "accounting/vat-ledger/input",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Output VAT",
              "route": "accounting/vat-ledger/output",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Reverse charge",
              "route": "accounting/vat-ledger/reverse-charge",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Breakdown",
              "route": "accounting/vat-ledger/breakdown",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Supporting documents",
              "route": "accounting/vat-ledger/supporting-documents",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        }
      ]
    },
    {
      "key": "documents",
      "label": "Records",
      "route": "documents",
      "icon": "FolderBookmark",
      "pages": [
        {
          "group": null,
          "label": "Overview",
          "route": "documents",
          "icon": "FolderBookmark",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": null,
          "label": "Inbox",
          "route": "documents/inbox",
          "icon": "Inbox",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Invoices & vouchers",
          "label": "Invoices",
          "route": "documents/invoices",
          "icon": "FileText",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Received",
              "route": "documents/invoices/received",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Issued",
              "route": "documents/invoices/issued",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Invoices & vouchers",
          "label": "Advances",
          "route": "documents/advances",
          "icon": "FileSpreadsheet",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Received",
              "route": "documents/advances/received",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Issued",
              "route": "documents/advances/issued",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Invoices & vouchers",
          "label": "Credit & debit notes",
          "route": "documents/credit-notes",
          "icon": "RotateCcw",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Received",
              "route": "documents/credit-notes/received",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Issued",
              "route": "documents/credit-notes/issued",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Invoices & vouchers",
          "label": "Obligation documents",
          "route": "documents/obligation-vouchers",
          "icon": "ClipboardIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Payable",
              "route": "documents/obligation-vouchers/payable",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Receivable",
              "route": "documents/obligation-vouchers/receivable",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Other documents",
          "label": "Loan documents",
          "route": "documents/loan-documents",
          "icon": "PiggyBank",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Other documents",
          "label": "Internal documents",
          "route": "documents/internal-documents",
          "icon": "FileCogIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Internal",
              "route": "documents/internal-documents/internal",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Customs declaration",
              "route": "documents/internal-documents/customs",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": null,
          "label": "Recurring templates",
          "route": "documents/recurring-templates",
          "icon": "RefreshCw",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        }
      ]
    },
    {
      "key": "finance",
      "label": "Finance",
      "route": "finance",
      "icon": "ReceiptEuro",
      "pages": [
        {
          "group": null,
          "label": "Overview",
          "route": "finance",
          "icon": "ReceiptEuro",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": null,
          "label": "Accounts",
          "route": "finance/accounts",
          "icon": "CreditCard",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Treasury",
          "label": "Bank",
          "route": "finance/bank",
          "icon": "Building2",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Movements",
              "route": "finance/bank/movements",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Statements",
              "route": "finance/bank/statements",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Reconciliation",
              "route": "finance/bank/reconciliation",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Treasury",
          "label": "Cash in hand",
          "route": "finance/cash",
          "icon": "Banknote",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Treasury",
          "label": "Loans",
          "route": "finance/loans",
          "icon": "PiggyBank",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Movements",
              "route": "finance/loans/movements",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Statements",
              "route": "finance/loans/statements",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Receivables & payables",
          "label": "Receivables",
          "route": "finance/receivables",
          "icon": "ArrowDown",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Ageing",
              "route": "finance/receivables/aging",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Debtors",
              "route": "finance/receivables/debtors",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Receivables & payables",
          "label": "Payables",
          "route": "finance/payables",
          "icon": "ArrowUp",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Due",
              "route": "finance/payables/due",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Creditors",
              "route": "finance/payables/creditors",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Collections",
          "label": "Dunning",
          "route": "finance/dunning",
          "icon": "Mail",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Collections",
          "label": "Penalisation",
          "route": "finance/penalization",
          "icon": "AlertTriangle",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Payments",
          "label": "Payment orders",
          "route": "finance/payment-orders",
          "icon": "Send",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Payments",
          "label": "Settlements",
          "route": "finance/settlements",
          "icon": "ArrowUpDown",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Bilateral",
              "route": "finance/settlements/bilateral",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Multilateral",
              "route": "finance/settlements/multilateral",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Payments",
          "label": "Bulk reconciliation",
          "route": "finance/reconciliation",
          "icon": "RefreshCw",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Payments",
          "label": "Calculators",
          "route": "finance/calculators",
          "icon": "Calculator",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "FX",
              "route": "finance/calculators/fx",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Penalty",
              "route": "finance/calculators/penalty",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Cash denomination",
              "route": "finance/calculators/cash-denomination",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        }
      ]
    },
    {
      "key": "hr",
      "label": "HR",
      "route": "hr",
      "icon": "Users",
      "pages": [
        {
          "group": null,
          "label": "Overview",
          "route": "hr",
          "icon": "Users",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": null,
          "label": "Payroll approvals",
          "route": "hr/approvals",
          "icon": "ListChecksIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "People",
          "label": "Employees",
          "route": "hr/employees",
          "icon": "User",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "People",
          "label": "Agreements",
          "route": "hr/agreements",
          "icon": "FileText",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Task agreement",
              "route": "hr/agreements/dpp",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Activity agreement",
              "route": "hr/agreements/dpc",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Payroll",
          "label": "Payroll runs",
          "route": "hr/payroll-runs",
          "icon": "Banknote",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Payroll",
          "label": "Payroll posting",
          "route": "hr/payroll-posting",
          "icon": "Workflow",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Payroll",
          "label": "Attendance",
          "route": "hr/attendance",
          "icon": "CalendarIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Payroll",
          "label": "Sickness e-filing",
          "route": "hr/e-davky",
          "icon": "Activity",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Payroll",
          "label": "Payroll reports",
          "route": "hr/payroll-reports",
          "icon": "FileSpreadsheet",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Income-tax reconciliation",
              "route": "hr/payroll-reports/income-tax",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Withholding-tax reconciliation",
              "route": "hr/payroll-reports/withholding",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Health insurance",
              "route": "hr/payroll-reports/health",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Social insurance",
              "route": "hr/payroll-reports/social",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Tax statements",
              "route": "hr/payroll-reports/tax",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Sick-pay",
              "route": "hr/payroll-reports/sick-pay",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Payroll",
          "label": "Payroll sheets",
          "route": "hr/payroll-sheets",
          "icon": "ClipboardIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Payroll",
          "label": "Pension record",
          "route": "hr/eldp",
          "icon": "IdCard",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        }
      ]
    },
    {
      "key": "assets",
      "label": "Assets",
      "route": "assets",
      "icon": "BriefcaseBusiness",
      "pages": [
        {
          "group": null,
          "label": "Overview",
          "route": "assets",
          "icon": "BriefcaseBusiness",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": null,
          "label": "Asset approvals",
          "route": "assets/approvals",
          "icon": "ListChecksIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Register",
          "label": "Fixed assets",
          "route": "assets/fixed-assets",
          "icon": "Building2",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Intangible assets",
              "route": "assets/fixed-assets/intangible",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Tangible assets",
              "route": "assets/fixed-assets/tangible",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Land & artwork",
              "route": "assets/fixed-assets/land-art",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Register",
          "label": "Small assets",
          "route": "assets/small-assets",
          "icon": "Box",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Register",
          "label": "Acquisitions & disposals",
          "route": "assets/acquisitions",
          "icon": "PlusCircle",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Under construction",
              "route": "assets/acquisitions/wip",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Advances",
              "route": "assets/acquisitions/advances",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Disposals",
              "route": "assets/acquisitions/disposals",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Register",
          "label": "Leasing",
          "route": "assets/leasing",
          "icon": "CreditCard",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Contracts",
              "route": "assets/leasing/contracts",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Instalments",
              "route": "assets/leasing/instalments",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Operations",
          "label": "Depreciation run",
          "route": "assets/depreciation-run",
          "icon": "Workflow",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Operations",
          "label": "Inventory count",
          "route": "assets/inventory-count",
          "icon": "ClipboardIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Fleet",
          "label": "Vehicles",
          "route": "assets/vehicles",
          "icon": "Box",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Fleet",
          "label": "Trip log",
          "route": "assets/trip-log",
          "icon": "ListIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Fleet",
          "label": "Drivers",
          "route": "assets/drivers",
          "icon": "CircleUser",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        }
      ]
    },
    {
      "key": "closing",
      "label": "Closing",
      "route": "closing",
      "icon": "CalendarClock",
      "pages": [
        {
          "group": null,
          "label": "Overview",
          "route": "closing",
          "icon": "CalendarClock",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": null,
          "label": "Calendar",
          "route": "closing/calendar",
          "icon": "CalendarIcon",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Monthly close",
          "label": "Unclosed",
          "route": "closing/unclosed",
          "icon": "LockOpen",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Monthly close",
          "label": "Closed",
          "route": "closing/closed",
          "icon": "Lock",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Obligations",
          "label": "VAT",
          "route": "closing/vat",
          "icon": "ReceiptEuro",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "VAT return",
              "route": "closing/vat/dap",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Control statement",
              "route": "closing/vat/kh",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "EC Sales List",
              "route": "closing/vat/sh",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "OSS",
              "route": "closing/vat/oss",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "IOSS",
              "route": "closing/vat/ioss",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Obligations",
          "label": "Payroll",
          "route": "closing/payroll",
          "icon": "Users",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Monthly employer report",
              "route": "closing/payroll/jmhz",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Social insurance",
              "route": "closing/payroll/social",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Health insurance",
              "route": "closing/payroll/health",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Withholding tax",
              "route": "closing/payroll/withholding",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Obligations",
          "label": "Income tax",
          "route": "closing/income-tax",
          "icon": "Calculator",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Corporation tax",
              "route": "closing/income-tax/dppo",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Section 7 tax-record worksheet",
              "route": "closing/income-tax/dpfo",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Advances",
              "route": "closing/income-tax/advances",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Obligations",
          "label": "Intrastat",
          "route": "closing/intrastat",
          "icon": "Globe",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Dispatches",
              "route": "closing/intrastat/dispatches",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Arrivals",
              "route": "closing/intrastat/arrivals",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Obligations",
          "label": "Year-end",
          "route": "closing/year-end",
          "icon": "Archive",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Accruals",
              "route": "closing/year-end/accruals",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Provisions",
              "route": "closing/year-end/provisions",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Value adjustments",
              "route": "closing/year-end/value-adjustments",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Deferred tax",
              "route": "closing/year-end/deferred-tax",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Draft closing worksheet",
              "route": "closing/year-end/statements",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Publication",
              "route": "closing/year-end/publication",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Year close",
              "route": "closing/year-end/close",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": null,
          "label": "Archive",
          "route": "closing/archive",
          "icon": "FileArchive",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        }
      ]
    },
    {
      "key": "reports",
      "label": "Reports",
      "route": "reports",
      "icon": "ChartNoAxesCombined",
      "pages": [
        {
          "group": null,
          "label": "Overview",
          "route": "reports",
          "icon": "ChartNoAxesCombined",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Statements",
          "label": "Balance sheet",
          "route": "reports/balance-sheet",
          "icon": "FileSpreadsheet",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Statements",
          "label": "Income statement",
          "route": "reports/income-statement",
          "icon": "BarChart3",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Statutory",
              "route": "reports/income-statement/statutory",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Monthly P&L",
              "route": "reports/income-statement/monthly",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Statements",
          "label": "Notes",
          "route": "reports/notes",
          "icon": "FileText",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Statements",
          "label": "Cash flow",
          "route": "reports/cash-flow",
          "icon": "Activity",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Statements",
          "label": "Equity changes",
          "route": "reports/equity-changes",
          "icon": "RefreshCw",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Statements",
          "label": "Assets & liabilities list",
          "route": "reports/assets-liabilities",
          "icon": "ListChecksIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Statements",
          "label": "Income & expenditure list",
          "route": "reports/income-expenditure",
          "icon": "ListIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Analysis",
          "label": "Account analysis",
          "route": "reports/account-analysis",
          "icon": "Search",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Analysis",
          "label": "Trial balance",
          "route": "reports/trial-balance",
          "icon": "ListIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Analysis",
          "label": "Profitability",
          "route": "reports/profitability",
          "icon": "PiggyBank",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Summary",
              "route": "reports/profitability/summary",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Cost & revenue listing",
              "route": "reports/profitability/cost-revenue",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Analysis",
          "label": "Management reporting",
          "route": "reports/controlling",
          "icon": "Shapes",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "By cost centre",
              "route": "reports/controlling/cost-centers",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "By job",
              "route": "reports/controlling/jobs",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "By activity",
              "route": "reports/controlling/activities",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Job profitability",
              "route": "reports/controlling/job-evaluation",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Balances",
          "label": "Open items by partner",
          "route": "reports/saldo",
          "icon": "BookUser",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Balances",
          "label": "Account balances",
          "route": "reports/account-balances",
          "icon": "ListIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Balances",
          "label": "Account movements",
          "route": "reports/account-movements",
          "icon": "ArrowUpDown",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Balances",
          "label": "Account verification",
          "route": "reports/account-inventory",
          "icon": "ClipboardIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Balances",
          "label": "Receivables/payables at date",
          "route": "reports/balances-at-date",
          "icon": "CalendarIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Print exports",
          "label": "Document journal",
          "route": "reports/document-journal",
          "icon": "BookOpen",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Print exports",
          "label": "FX rate list",
          "route": "reports/fx-rate-list",
          "icon": "Globe",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Print exports",
          "label": "Statutory prints",
          "route": "reports/statutory-prints",
          "icon": "FileText",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Journal",
              "route": "reports/statutory-prints/journal",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "General ledger",
              "route": "reports/statutory-prints/ledger",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Print exports",
          "label": "XML statement export",
          "route": "reports/xml-export",
          "icon": "Download",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Print exports",
          "label": "Audit confirmation letters",
          "route": "reports/confirmation-letters",
          "icon": "Mail",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        }
      ]
    },
    {
      "key": "directory",
      "label": "Directory",
      "route": "directory",
      "icon": "BookUser",
      "pages": [
        {
          "group": null,
          "label": "Overview",
          "route": "directory",
          "icon": "BookUser",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Registers",
          "label": "Counterparties",
          "route": "directory/counterparties",
          "icon": "Building2",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Customers",
              "route": "directory/counterparties/customers",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Suppliers",
              "route": "directory/counterparties/suppliers",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Registers",
          "label": "Contacts",
          "route": "directory/contacts",
          "icon": "User",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Registers",
          "label": "Activities",
          "route": "directory/activities",
          "icon": "Activity",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Registers",
          "label": "Contracts",
          "route": "directory/contracts",
          "icon": "FileText",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Customer",
              "route": "directory/contracts/customer",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Supplier",
              "route": "directory/contracts/supplier",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Registers",
          "label": "Institutions",
          "route": "directory/institutions",
          "icon": "Globe",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Tax office",
              "route": "directory/institutions/financial-office",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Social security",
              "route": "directory/institutions/social-security",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Health insurers",
              "route": "directory/institutions/health-insurers",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Customs",
              "route": "directory/institutions/customs",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Commercial register",
              "route": "directory/institutions/justice",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Data box",
              "route": "directory/institutions/data-box",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Registers",
          "label": "Banks",
          "route": "directory/banks",
          "icon": "Banknote",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        }
      ]
    },
    {
      "key": "settings",
      "label": "Settings",
      "route": "settings",
      "icon": "Settings",
      "pages": [
        {
          "group": null,
          "label": "Overview",
          "route": "settings",
          "icon": "Settings",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Organisation",
          "label": "Identity",
          "route": "settings/identity",
          "icon": "IdCard",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Organisation",
          "label": "Periods & fiscal year",
          "route": "settings/periods",
          "icon": "CalendarClock",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Organisation",
          "label": "VAT status",
          "route": "settings/vat-status",
          "icon": "ReceiptEuro",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Organisation",
          "label": "Tax profile",
          "route": "settings/tax-profile",
          "icon": "Users",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Organisation",
          "label": "Business activities",
          "route": "settings/business-activities",
          "icon": "Briefcase",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Organisation",
          "label": "Branding",
          "route": "settings/branding",
          "icon": "Palette",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Reference",
          "label": "Number series",
          "route": "settings/number-series",
          "icon": "HashIcon",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Reference",
          "label": "FX rates",
          "route": "settings/fx-rates",
          "icon": "Globe",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Method",
              "route": "settings/fx-rates/method",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Central bank feed",
              "route": "settings/fx-rates/feed",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Reference",
          "label": "Dimensions",
          "route": "settings/dimensions",
          "icon": "Shapes",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Cost centres",
              "route": "settings/dimensions/cost-centers",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Jobs",
              "route": "settings/dimensions/jobs",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Activities",
              "route": "settings/dimensions/activities",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Reference",
          "label": "Codebooks",
          "route": "settings/codebooks",
          "icon": "BookOpen",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Document types",
              "route": "settings/codebooks/document-types",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Constant symbols",
              "route": "settings/codebooks/constant-symbols",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Payment methods",
              "route": "settings/codebooks/payment-methods",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Units",
              "route": "settings/codebooks/units",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Tags",
              "route": "settings/codebooks/tags",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Reference",
          "label": "Law tables",
          "route": "settings/law-tables",
          "icon": "Shield",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "VAT rates",
              "route": "settings/law-tables/vat-rates",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Depreciation groups",
              "route": "settings/law-tables/depreciation-groups",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "NACE codes",
              "route": "settings/law-tables/cz-nace",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Account groups",
              "route": "settings/law-tables/account-groups",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Directive chart",
              "route": "settings/law-tables/directive-chart",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Legal forms",
              "route": "settings/law-tables/legal-forms",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Regimes",
              "route": "settings/law-tables/regimes",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Size categories",
              "route": "settings/law-tables/sizes",
              "tba": true,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Countries & postcodes",
              "route": "settings/law-tables/countries",
              "tba": true,
              "archetype": null,
              "purpose": null
            }
          ]
        },
        {
          "group": "Access",
          "label": "Members",
          "route": "settings/members",
          "icon": "Users",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Integrations",
          "label": "Data box",
          "route": "settings/data-box",
          "icon": "Mail",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Integrations",
          "label": "Homebanking",
          "route": "settings/homebanking",
          "icon": "Building2",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Integrations",
          "label": "ISDOC / iDoklad",
          "route": "settings/isdoc",
          "icon": "FileCodeIcon",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "System",
          "label": "AI budget & cooldown",
          "route": "settings/ai-budget",
          "icon": "Sparkles",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "System",
          "label": "Reminders",
          "route": "settings/reminders",
          "icon": "Bell",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "System",
          "label": "Recurring tasks",
          "route": "settings/recurring-tasks",
          "icon": "RefreshCw",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "System",
          "label": "Background jobs",
          "route": "settings/jobs",
          "icon": "Workflow",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "System",
          "label": "Submission log",
          "route": "settings/submission-log",
          "icon": "Send",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "System",
          "label": "Recycle bin",
          "route": "settings/recycle-bin",
          "icon": "Trash2",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "System",
          "label": "Action history",
          "route": "settings/action-history",
          "icon": "History",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "System",
          "label": "Print templates",
          "route": "settings/print-templates",
          "icon": "Presentation",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "System",
          "label": "Import / Export",
          "route": "settings/import-export",
          "icon": "Download",
          "tba": true,
          "archetype": null,
          "purpose": null,
          "subpages": []
        },
        {
          "group": "Debug",
          "label": "Debug",
          "route": "settings/debug",
          "icon": "Bug",
          "tba": false,
          "archetype": null,
          "purpose": null,
          "subpages": [
            {
              "label": "Archetype Blank",
              "route": "settings/debug/archetype-blank",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Archetype Details",
              "route": "settings/debug/archetype-details",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Archetype Table",
              "route": "settings/debug/archetype-table",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Archetype Table (DB)",
              "route": "settings/debug/archetype-table-db",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Archetype Table (Pivot)",
              "route": "settings/debug/archetype-table-pivot",
              "tba": false,
              "archetype": null,
              "purpose": null
            },
            {
              "label": "Section Details Form",
              "route": "settings/debug/section-form",
              "tba": false,
              "archetype": null,
              "purpose": null
            }
          ]
        }
      ]
    }
  ]
}
