/**
 * gen-chart-template-seed.ts — generate the 0068 seed migration for the year-based
 * Účetní osnova overlay + the prebuilt house Účtový rozvrh template.
 *
 * Reads the vendored JSON in packages/db/seeds/ (derived from the Money S3 2026 export +
 * the advisor-verified directive_account catalogue) and emits
 * packages/db/migrations/0068_accounting_chart_directive_year_seed.sql:
 *   - directive_account_year (year 2026)  <- directive_account_year.2026.json
 *   - chart_template + chart_template_account (MONEY_2026) <- chart_template.2026.money.json
 *
 * Idempotent (ON CONFLICT DO NOTHING). The chart_template rows use a deterministic UUID
 * (uuidv5 over the (year, code) name) so re-running the seed is stable and the template
 * accounts can reference it without a round-trip.
 *
 * Vendored-data rule (memory vendored-data-prettier-gitleaks): both this generator AND the
 * committed JSON + SQL output are tracked; .prettierignore + .gitleaks.toml allowlist cover
 * the account-number-shaped strings.
 *
 * Run: pnpm --filter @workspace/db exec tsx scripts/gen-chart-template-seed.ts
 */
import { readFileSync, writeFileSync } from "node:fs"
import { createHash } from "node:crypto"
import { join } from "node:path"

const SEEDS = join(import.meta.dirname, "..", "seeds")
const OUT = join(
  import.meta.dirname,
  "..",
  "migrations",
  "0068_accounting_chart_directive_year_seed.sql",
)

type DayRow = {
  year: number
  code: string
  tracks_open_items: boolean
  tax_relevant: boolean | null
  deprecated: boolean
}
type TemplateAccount = {
  number: string
  name: string
  name_en: string | null
  nature: string
  normal_balance: string | null
  tracks_open_items: boolean
  tax_relevant: boolean | null
  is_allowance: boolean
  directive_code: string | null
}
type Template = {
  year: number
  code: string
  name: string
  is_default: boolean
  source: string
  accounts: TemplateAccount[]
}

const day = JSON.parse(
  readFileSync(join(SEEDS, "directive_account_year.2026.json"), "utf8"),
) as { year: number; accounts: DayRow[] }
const template = JSON.parse(
  readFileSync(join(SEEDS, "chart_template.2026.money.json"), "utf8"),
) as Template

const s = (v: string | null | undefined) =>
  v === null || v === undefined ? "NULL" : `'${v.replace(/'/g, "''")}'`
const b = (v: boolean) => (v ? "true" : "false")
const nb = (v: boolean | null | undefined) =>
  v === null || v === undefined ? "NULL" : v ? "true" : "false"

/** Deterministic uuidv5 (DNS-ish namespace) so the template id is stable across re-seeds. */
function uuidv5(name: string): string {
  const ns = Buffer.from("6ba7b8109dad11d180b400c04fd430c8", "hex")
  const h = createHash("sha1")
  h.update(ns)
  h.update(Buffer.from(name, "utf8"))
  const d = h.digest()
  d[6] = (d[6]! & 0x0f) | 0x50
  d[8] = (d[8]! & 0x3f) | 0x80
  const hex = d.subarray(0, 16).toString("hex")
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`
}

const templateId = uuidv5(`chart_template:${template.year}:${template.code}`)

const dayRows = day.accounts
  .sort((a, z) => a.code.localeCompare(z.code))
  .map(
    (r) =>
      `  (${r.year}, ${s(r.code)}, NULL, ${b(r.tracks_open_items)}, ${nb(r.tax_relevant)}, ${b(r.deprecated)})`,
  )

const tplAccountRows = template.accounts
  .slice()
  .sort((a, z) => a.number.localeCompare(z.number))
  .map(
    (a) =>
      `  ('${templateId}'::uuid, ${s(a.number)}, ${s(a.name)}, ${s(a.nature)}, ${s(a.normal_balance)}, ${b(a.tracks_open_items)}, ${nb(a.tax_relevant)}, ${b(a.is_allowance)}, NULL, ${s(a.directive_code)})`,
  )

const header = `-- 0068_accounting_chart_directive_year_seed.sql
--
-- GENERATED by packages/db/scripts/gen-chart-template-seed.ts from the vendored JSON in
-- packages/db/seeds/ (Money S3 2026 export + advisor-verified directive_account catalogue).
-- Do not hand-edit rows; re-run the generator. Idempotent (ON CONFLICT DO NOTHING).
--
--   directive_account_year (${day.accounts.length} rows, year ${day.year}) — the year-based Účetní osnova overlay.
--   chart_template MONEY_2026 + ${template.accounts.length} chart_template_account rows — the prebuilt house Účtový rozvrh.
--
-- tax_relevant (Daňový) is set for expense/revenue účty only (NULL for balance/closing); it is the
-- base for the daňové/nedaňové split (§24/§25 ZDP). tracks_open_items marks saldokonto účty (§16).

BEGIN;

-- The year-based Účetní osnova (account directive) for ${day.year}. Membership + saldo/tax defaults;
-- names/nature/statement mapping stay on the stable directive_account rows it references.
INSERT INTO directive_account_year (year, code, name_cs, tracks_open_items, tax_relevant, deprecated) VALUES
${dayRows.join(",\n")}
ON CONFLICT (year, code) DO NOTHING;

-- The prebuilt house Účtový rozvrh template for ${template.year} (${template.code}).
INSERT INTO chart_template (id, year, code, name, source, is_default) VALUES
  ('${templateId}'::uuid, ${template.year}, ${s(template.code)}, ${s(template.name)}, ${s(template.source)}, ${b(template.is_default)})
ON CONFLICT (year, code) DO NOTHING;

INSERT INTO chart_template_account
  (template_id, number, name, nature, normal_balance, tracks_open_items, tax_relevant, is_allowance, parent_number, specializes_directive_code) VALUES
${tplAccountRows.join(",\n")}
ON CONFLICT (template_id, number) DO NOTHING;

COMMIT;
`

writeFileSync(OUT, header)
console.log(`wrote ${OUT}`)

// ── reference account names → next-intl message catalogs ───────────────────────────────
// Account names are translations, so they live in the next-intl catalogs
// (packages/i18n/src/messages/{en,cs}.json) and resolve by key like every other string — never
// a bespoke catalog or a per-language DB column. GENERATED from the single upstream sources (the
// vendored template JSON + the frozen reference seed 0026), so the message entries never drift by
// hand. Two maps, because the same synthetic code can carry a different name in the legal osnova
// vs the Money template (e.g. 014):
//   accounting.chartOfAccounts.osnovaNames.<code>   — legal Účetní osnova (directive_account)
//   accounting.chartOfAccounts.templateNames.<code> — prebuilt Money Účtový rozvrh (this seed)
type NameMap = { en: Record<string, string>; cs: Record<string, string> }
const sortByKey = (m: Record<string, string>): Record<string, string> =>
  Object.fromEntries(Object.entries(m).sort(([a], [z]) => a.localeCompare(z)))

// Template names — from the vendored JSON (name = cs, name_en = en), deduped first-wins to mirror
// the seed's `ON CONFLICT (template_id, number)` (e.g. 211 Pokladna / CZK / EUR keep the first).
const missingNames = template.accounts.filter((a) => !a.name || !a.name_en)
if (missingNames.length > 0) {
  throw new Error(
    `gen-chart-template-seed: ${missingNames.length} template account(s) are missing name/name_en ` +
      `(first: ${missingNames[0]!.number}). Every template account needs both names for the catalog.`,
  )
}
const templateNames: NameMap = { en: {}, cs: {} }
for (const a of template.accounts) {
  if (a.number in templateNames.cs) continue // first-wins
  templateNames.en[a.number] = a.name_en!.trim() // vendored data carries stray trailing spaces
  templateNames.cs[a.number] = a.name.trim()
}

// Osnova names — parsed from the frozen reference seed 0026 (the single source of the legal
// directive_account names). An applied migration, never edited, so the line format is stable.
const DIRECTIVE_SEED = join(
  import.meta.dirname,
  "..",
  "migrations",
  "0026_accounting_reference_seed.sql",
)
const directiveRow =
  /^\s*\('([^']+)',\s*'(?:[^']|'')*',\s*'((?:[^']|'')*)',\s*'((?:[^']|'')*)'/
const unquote = (s: string) => s.replace(/''/g, "'")
const osnovaNames: NameMap = { en: {}, cs: {} }
let inDirective = false
for (const line of readFileSync(DIRECTIVE_SEED, "utf8").split("\n")) {
  if (/^INSERT INTO directive_account \(/.test(line)) {
    inDirective = true
    continue
  }
  if (!inDirective) continue
  // The VALUES block ends at ON CONFLICT / the statement terminator.
  if (/^\s*(ON CONFLICT|;)/i.test(line) || line.trim() === "") {
    inDirective = false
    continue
  }
  // A VALUES line that fails the row shape means 0026's format changed — fail loud rather than
  // silently dropping the rest of the directive rows.
  const m = directiveRow.exec(line)
  if (!m) {
    throw new Error(
      `gen-chart-template-seed: unparseable directive_account row (0026 format changed?): ${line.trim().slice(0, 70)}`,
    )
  }
  osnovaNames.cs[m[1]!] = unquote(m[2]!).trim()
  osnovaNames.en[m[1]!] = unquote(m[3]!).trim()
}

// Every framework year-code the osnova view lists must have a name.
const uncoveredOsnova = day.accounts
  .map((r) => r.code)
  .filter((code) => !(code in osnovaNames.cs))
if (uncoveredOsnova.length > 0) {
  throw new Error(
    `gen-chart-template-seed: ${uncoveredOsnova.length} directive_account_year code(s) missing a ` +
      `name in 0026 (first: ${uncoveredOsnova[0]}).`,
  )
}

// next-intl treats "." as a key-path separator, so an analytic code like "311.001" would nest
// instead of resolving. Today's reference accounts are synthetic (no dots) — guard the invariant.
const dottedCodes = [
  ...Object.keys(osnovaNames.cs),
  ...Object.keys(templateNames.cs),
].filter((code) => code.includes("."))
if (dottedCodes.length > 0) {
  throw new Error(
    `gen-chart-template-seed: account code(s) contain a dot, which breaks next-intl key nesting: ` +
      `${dottedCodes.slice(0, 5).join(", ")}. Use a non-dotted key scheme before adding analytics.`,
  )
}

// Write both maps into every live locale's message catalog (sorted, stable, minimal diff).
const MESSAGES_DIR = join(
  import.meta.dirname,
  "..",
  "..",
  "i18n",
  "src",
  "messages",
)
for (const locale of ["en", "cs"] as const) {
  const file = join(MESSAGES_DIR, `${locale}.json`)
  const messages = JSON.parse(readFileSync(file, "utf8"))
  const chart = ((messages.accounting ??= {}).chartOfAccounts ??= {})
  chart.osnovaNames = sortByKey(osnovaNames[locale])
  chart.templateNames = sortByKey(templateNames[locale])
  writeFileSync(file, JSON.stringify(messages, null, 2) + "\n")
  console.log(
    `wrote ${file} accounting.chartOfAccounts.{osnovaNames(${Object.keys(osnovaNames[locale]).length}),templateNames(${Object.keys(templateNames[locale]).length})}`,
  )
}

console.log(
  `directive_account_year rows: ${dayRows.length}, chart_template_account rows: ${tplAccountRows.length}, template id: ${templateId}`,
)
