/**
 * gen-bank-seed.ts — generate the 0081 financial-institution register seed migration.
 *
 * Reads the vendored `packages/db/data/bank.json` (the ČNB payment-system bank-code list:
 * bank_code + Czech name) and emits `packages/db/migrations/0081_financial_institution_seed.sql`:
 *   - INSERT INTO financial_institution (bank_code) — idempotent (ON CONFLICT DO NOTHING).
 *
 * Only bank_code is seeded into the DB. The display NAMES are NOT seeded here — they localize
 * via next-intl (`bankNames`, generated by gen-bank-names.ts from the same bank.json). Re-generate
 * with this script; do not hand-edit the seed rows.
 *
 * Vendored-data rule (memory vendored-data-prettier-gitleaks): both this generator AND its
 * committed output (+ bank.json) are tracked; add .prettierignore / .gitleaks.toml allowlist
 * entries if lefthook trips on the data shapes.
 *
 * Run: pnpm --filter @workspace/db exec tsx scripts/gen-bank-seed.ts
 */
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"

interface BankData {
  bankCode: string
  name: string
}

const here = dirname(fileURLToPath(import.meta.url))
const DATA = resolve(here, "..", "data", "bank.json")
const OUT = resolve(
  here,
  "..",
  "migrations",
  "0081_financial_institution_seed.sql",
)

const data = JSON.parse(readFileSync(DATA, "utf8")) as BankData[]

const rows = data
  .slice()
  .sort((a, b) => a.bankCode.localeCompare(b.bankCode))
  .map((r) => `  ('${r.bankCode}')`)

const header = `-- 0081_financial_institution_seed.sql
--
-- ČNB bank-code register seed (${rows.length} rows). GENERATED by
-- packages/db/scripts/gen-bank-seed.ts from packages/db/data/bank.json. Idempotent
-- (ON CONFLICT DO NOTHING). Re-generate with the script; do not hand-edit rows.
-- Display names are NOT seeded here — they localize via next-intl (bankNames).

BEGIN;

INSERT INTO financial_institution (bank_code) VALUES
${rows.join(",\n")}
ON CONFLICT (bank_code) DO NOTHING;

COMMIT;
`

writeFileSync(OUT, header)
console.log(`wrote ${OUT} (${rows.length} rows)`)
