/**
 * gen-country-seed.ts — generate the 0073 country-register seed migration.
 *
 * Reads the vendored `packages/db/data/country.json` (an objective extract of the provided
 * ČSÚ státy dataset: iso2 + Czech name + ISO-4217 currency where known) and emits
 * `packages/db/migrations/0073_country_seed.sql`:
 *   - INSERT INTO country (iso2, currency_code) — 258 rows, idempotent (ON CONFLICT DO NOTHING).
 *
 * Only iso2 + currency_code are seeded into the DB. The Czech/English display NAMES are NOT
 * seeded here — they localize via next-intl (`countryNames`, generated by
 * packages/i18n/scripts/gen-country-names.ts from the same country.json). Re-generate with
 * this script; do not hand-edit the seed rows.
 *
 * Vendored-data rule (memory vendored-data-prettier-gitleaks): both this generator AND its
 * committed output (+ country.json) are tracked; add .prettierignore / .gitleaks.toml
 * allowlist entries if lefthook trips on the data shapes.
 *
 * Run: pnpm --filter @workspace/db exec tsx scripts/gen-country-seed.ts
 */
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"

interface CountryData {
  iso2: string
  nameCs: string
  currencyCode: string | null
}

const here = dirname(fileURLToPath(import.meta.url))
const DATA = resolve(here, "..", "data", "country.json")
const OUT = resolve(here, "..", "migrations", "0073_country_seed.sql")

const data = JSON.parse(readFileSync(DATA, "utf8")) as CountryData[]

const rows = data
  .slice()
  .sort((a, b) => a.iso2.localeCompare(b.iso2))
  .map(
    (r) =>
      `  ('${r.iso2}', ${r.currencyCode ? `'${r.currencyCode}'` : "NULL"})`,
  )

const header = `-- 0073_country_seed.sql
--
-- ISO 3166-1 country register seed (${rows.length} rows). GENERATED by
-- packages/db/scripts/gen-country-seed.ts from packages/db/data/country.json
-- (an objective extract of the provided ČSÚ státy dataset). Idempotent
-- (ON CONFLICT DO NOTHING). Re-generate with the script; do not hand-edit rows.
-- Display names are NOT seeded here — they localize via next-intl (countryNames).

BEGIN;

INSERT INTO country (iso2, currency_code) VALUES
${rows.join(",\n")}
ON CONFLICT (iso2) DO NOTHING;

COMMIT;
`

writeFileSync(OUT, header)
console.log(`wrote ${OUT} (${rows.length} rows)`)
