/**
 * gen-payment-form-seed.ts — generate the 0085 payment-form register seed migration.
 *
 * Reads the vendored `packages/db/data/payment-form.json` (the Czech forma-úhrady list:
 * code + name + invoice phrase + per-surface offer flags) and emits
 * `packages/db/migrations/0085_payment_form_seed.sql`:
 *   - INSERT INTO payment_form (code, offer_on_invoice, offer_on_cash_desk, offer_on_pos)
 *     — idempotent (ON CONFLICT DO NOTHING).
 *
 * Only code + the offer flags are seeded into the DB. The display NAME and invoice PHRASE
 * are NOT seeded here — they localize via next-intl (`paymentFormNames` / `paymentFormPhrases`,
 * generated by gen-payment-form-names.ts from the same JSON). Re-generate with this script;
 * do not hand-edit the seed rows.
 *
 * Vendored-data rule (memory vendored-data-prettier-gitleaks): both this generator AND its
 * committed output (+ payment-form.json) are tracked; add .prettierignore / .gitleaks.toml
 * allowlist entries if lefthook trips on the data shapes.
 *
 * Run: pnpm --filter @workspace/db exec tsx scripts/gen-payment-form-seed.ts
 */
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"

interface PaymentFormData {
  code: string
  name: string
  phrase: string
  offerInvoice: boolean
  offerCashDesk: boolean
  offerPos: boolean
}

const here = dirname(fileURLToPath(import.meta.url))
const DATA = resolve(here, "..", "data", "payment-form.json")
const OUT = resolve(here, "..", "migrations", "0085_payment_form_seed.sql")

const data = JSON.parse(readFileSync(DATA, "utf8")) as PaymentFormData[]

const rows = data
  .slice()
  .sort((a, b) => a.code.localeCompare(b.code))
  .map(
    (r) =>
      `  ('${r.code}', ${r.offerInvoice}, ${r.offerCashDesk}, ${r.offerPos})`,
  )

const header = `-- 0085_payment_form_seed.sql
--
-- Forma úhrady register seed (${rows.length} rows). GENERATED by
-- packages/db/scripts/gen-payment-form-seed.ts from packages/db/data/payment-form.json.
-- Idempotent (ON CONFLICT DO NOTHING). Re-generate with the script; do not hand-edit
-- rows. Names + invoice phrases are NOT seeded here — they localize via next-intl
-- (paymentFormNames / paymentFormPhrases).

BEGIN;

INSERT INTO payment_form (code, offer_on_invoice, offer_on_cash_desk, offer_on_pos) VALUES
${rows.join(",\n")}
ON CONFLICT (code) DO NOTHING;

COMMIT;
`

writeFileSync(OUT, header)
console.log(`wrote ${OUT} (${rows.length} rows)`)
