/**
 * gen-constant-symbol-seed.ts — generate the 0083 constant-symbol register seed migration.
 *
 * Reads the vendored `packages/db/data/constant-symbol.json` (konstantní symbol code + Czech
 * name) and emits `packages/db/migrations/0083_constant_symbol_seed.sql`:
 *   - INSERT INTO constant_symbol (code) — idempotent (ON CONFLICT DO NOTHING).
 *
 * Only code is seeded into the DB. The display NAMES are NOT seeded here — they localize via
 * next-intl (`constantSymbolNames`, generated by gen-constant-symbol-names.ts from the same
 * JSON). Re-generate with this script; do not hand-edit the seed rows.
 *
 * Vendored-data rule (memory vendored-data-prettier-gitleaks): both this generator AND its
 * committed output (+ constant-symbol.json) are tracked; add .prettierignore / .gitleaks.toml
 * allowlist entries if lefthook trips on the data shapes.
 *
 * Run: pnpm --filter @workspace/db exec tsx scripts/gen-constant-symbol-seed.ts
 */
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"

interface ConstantSymbolData {
  code: string
  name: string
}

const here = dirname(fileURLToPath(import.meta.url))
const DATA = resolve(here, "..", "data", "constant-symbol.json")
const OUT = resolve(here, "..", "migrations", "0083_constant_symbol_seed.sql")

const data = JSON.parse(readFileSync(DATA, "utf8")) as ConstantSymbolData[]

const rows = data
  .slice()
  .sort((a, b) => a.code.localeCompare(b.code))
  .map((r) => `  ('${r.code}')`)

const header = `-- 0083_constant_symbol_seed.sql
--
-- Konstantní symbol register seed (${rows.length} rows). GENERATED by
-- packages/db/scripts/gen-constant-symbol-seed.ts from
-- packages/db/data/constant-symbol.json. Idempotent (ON CONFLICT DO NOTHING).
-- Re-generate with the script; do not hand-edit rows. Display names are NOT
-- seeded here — they localize via next-intl (constantSymbolNames).

BEGIN;

INSERT INTO constant_symbol (code) VALUES
${rows.join(",\n")}
ON CONFLICT (code) DO NOTHING;

COMMIT;
`

writeFileSync(OUT, header)
console.log(`wrote ${OUT} (${rows.length} rows)`)
