import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

/**
 * Generate one MCP tool registration file per OpenAPI operation.
 *
 * Reads the committed `apps/api/openapi/v1.json`, walks every
 * `paths[*][method]`, and emits `apps/mcp/src/tools/generated/<id>.ts` for
 * each `operationId`. The output uses the existing SDK client + render
 * helpers — no new transport, no new error envelope.
 *
 * The hand-curated `_curate.ts` lookup table layers per-operation
 * annotation tweaks (e.g. "this POST is destructive" or "this GET pages
 * with cursors"); the codegen merges those with method-derived defaults.
 *
 * The output dir is `linguist-generated=true` via `.gitattributes` — never
 * hand-edit. Drift between the spec and the committed tool files is gated
 * by `.github/workflows/mcp-coverage.yml`.
 */

interface Operation {
  operationId?: string
  summary?: string
  description?: string
  tags?: string[]
}

interface Spec {
  paths?: Record<string, Record<string, Operation>>
}

const ROOT = resolve(__dirname, "..", "..", "..")
const SPEC_PATH = resolve(ROOT, "apps/api/openapi/v1.json")
const OUT_DIR = resolve(ROOT, "apps/mcp/src/tools/generated")
const INDEX_PATH = resolve(OUT_DIR, "index.ts")
const HTTP_METHODS = ["get", "post", "put", "patch", "delete"] as const

function camelToSnake(camel: string): string {
  // Two-pass conversion so multi-character acronyms stay grouped:
  //   `getOrganization`   -> `get_organization`
  //   `listAPIKeys`       -> `list_api_keys`   (not `list_a_p_i_keys`)
  //   `parseEANCheckDigit`-> `parse_ean_check_digit`
  // First pass splits acronym-then-Capital boundaries; second pass splits
  // lower-then-Capital boundaries. Final lowercase emits the tool name.
  return camel
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .replace(/([a-z\d])([A-Z])/g, "$1_$2")
    .toLowerCase()
}

function escape(text: string): string {
  return text.replace(/[`\\]/g, "\\$&").replace(/\$\{/g, "\\${")
}

function clientCallFor(method: string, path: string): string {
  // The codegen targets the openapi-fetch `client.GET/POST(...)` surface
  // exported by `@afframe/sdk` (`createAfframeClient`). Emit the path as a
  // bare string literal — TS narrows it to its literal type and openapi-
  // fetch's `PathsWithMethod` accepts the match. No `as never` cast: that
  // would defeat the path typing the generated types exist to provide.
  const verb = method.toUpperCase()
  return `client.${verb}("${path}")`
}

function emitTool(
  operationId: string,
  method: string,
  path: string,
  op: Operation,
): string {
  const description =
    op.description ?? op.summary ?? `Wraps ${method.toUpperCase()} ${path}.`
  return `// AUTO-GENERATED by apps/mcp/scripts/gen-tools.ts — do not edit.
import type { AfframeClient } from "@afframe/sdk"
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js"
import { renderResult, toolError } from "../_render"
import { defaultAnnotationsForMethod, getAnnotations } from "../_curate"

export function register${capitalize(operationId)}(
  server: McpServer,
  client: AfframeClient,
): void {
  server.registerTool(
    "${camelToSnake(operationId)}",
    {
      title: ${JSON.stringify(op.summary ?? operationId)},
      description: \`${escape(description)}\`,
      annotations: {
        ...defaultAnnotationsForMethod("${method}"),
        ...getAnnotations("${operationId}"),
      },
    },
    async (): Promise<CallToolResult> => {
      try {
        const { data, error, response } = await ${clientCallFor(method, path)}
        if (error) throw error
        if (!response.ok) {
          throw new Error(\`Upstream HTTP \${response.status}\`)
        }
        return renderResult(data)
      } catch (err) {
        return toolError(err)
      }
    },
  )
}
`
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function main(): void {
  const spec: Spec = JSON.parse(readFileSync(SPEC_PATH, "utf8")) as Spec
  mkdirSync(OUT_DIR, { recursive: true })
  const registered: { operationId: string; toolName: string }[] = []

  for (const [path, pathItem] of Object.entries(spec.paths ?? {})) {
    for (const method of HTTP_METHODS) {
      const op = pathItem[method]
      if (!op?.operationId) continue
      // Skip non-GET methods for now. openapi-fetch requires `{ body }` as
      // the second argument for POST/PUT/PATCH; wiring the body schema +
      // MCP inputSchema is a separate feature (tracked in Linear). Until
      // then, only read-only operations become MCP tools — they are the
      // common case anyway (LLMs reading state, not writing it).
      if (method !== "get") continue
      const out = emitTool(op.operationId, method, path, op)
      writeFileSync(resolve(OUT_DIR, `${op.operationId}.ts`), out)
      registered.push({
        operationId: op.operationId,
        toolName: camelToSnake(op.operationId),
      })
    }
  }

  const indexLines = [
    "// AUTO-GENERATED by apps/mcp/scripts/gen-tools.ts — do not edit.",
    'import type { AfframeClient } from "@afframe/sdk"',
    'import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"',
    ...registered.map(
      (r) =>
        `import { register${capitalize(r.operationId)} } from "./${r.operationId}"`,
    ),
    "",
    "export function registerGeneratedTools(server: McpServer, client: AfframeClient): void {",
    ...registered.map(
      (r) => `  register${capitalize(r.operationId)}(server, client)`,
    ),
    "}",
    "",
    "export const GENERATED_TOOL_OPERATION_IDS = [",
    ...registered.map((r) => `  ${JSON.stringify(r.operationId)},`),
    "] as const",
    "",
  ]
  writeFileSync(INDEX_PATH, indexLines.join("\n"))

  process.stdout.write(
    `Generated ${registered.length} MCP tool(s) into apps/mcp/src/tools/generated/\n`,
  )
}

try {
  main()
} catch (err) {
  console.error(err)
  process.exit(1)
}
