/**
 * Domain DTOs for the accounting records system.
 *
 * Enum unions are derived from the Drizzle pgEnums (single source of truth, in
 * sync with the SQL). Money is represented as `Decimal` (a decimal string,
 * e.g. "121.00") — never a JS number. All money arithmetic happens in SQL; the
 * TS layer only transports decimal strings to/from numeric(19,4) columns. See
 * src/sql.ts for the rationale.
 */

import type {
  accountingRegime,
  ucetniObdobiTyp,
  ucetniDokladTyp,
  dilciDruh,
  ucetTyp,
  zapisStrana,
  penezniDenikMisto,
  penezniDenikSmer,
  kategorieTyp,
  ucetniZapisOpravaTyp,
  vystupTyp,
} from "@workspace/db/schema"

export type Regime = (typeof accountingRegime.enumValues)[number]
export type ObdobiTyp = (typeof ucetniObdobiTyp.enumValues)[number]
export type DokladTyp = (typeof ucetniDokladTyp.enumValues)[number]
export type DilciDruh = (typeof dilciDruh.enumValues)[number]
export type UcetTyp = (typeof ucetTyp.enumValues)[number]
export type Strana = (typeof zapisStrana.enumValues)[number]
export type Misto = (typeof penezniDenikMisto.enumValues)[number]
export type Smer = (typeof penezniDenikSmer.enumValues)[number]
export type KategorieTyp = (typeof kategorieTyp.enumValues)[number]
export type OpravaTyp = (typeof ucetniZapisOpravaTyp.enumValues)[number]
export type VystupTyp = (typeof vystupTyp.enumValues)[number]

/** Exact decimal amount as a string (e.g. "121.00"). Never a JS number (R13). */
export type Decimal = string

/** Organization + accounting-unit scope passed to domain operations. */
export interface UnitCtx {
  /** RLS anchor; must equal the app.organization_id GUC set by withOrganization. */
  organizationId: string
  /** The ucetni_jednotka this operation belongs to. */
  jednotkaId: string
}

// --- capture (UC-1 steps 1-3) ----------------------------------------------

export interface CaseInput {
  popis: string
  /** ISO date (YYYY-MM-DD) of when the economic event occurred (§11/1e). */
  datumUskutecneni: string
  protistranaId?: string | null
  typ?: string | null
}

export interface DilciInput {
  druh: DilciDruh
  castka: Decimal
  dphSazba?: Decimal | null
  dphCastka?: Decimal | null
}

export interface DocumentLineInput {
  /** The ucetni_pripad this line documents (§6/1). */
  pripadId: string
  popis?: string | null
  castka: Decimal
  /** Money decomposition (§33/5): base / VAT / rounding. */
  dilci: DilciInput[]
}

export interface DocumentInput {
  obdobiId: string
  typ: DokladTyp
  /** číselná řada — unique per (unit, period, type) (§11/1a). */
  oznaceni: string
  /** ISO timestamp; defaults to now() when omitted. */
  okamzikVyhotoveni?: string
  protistranaId?: string | null
  lines: DocumentLineInput[]
}

export interface CapturedLine {
  radekId: string
  dilciIds: string[]
}

export interface CapturedDocument {
  dokladId: string
  lines: CapturedLine[]
}

// --- posting (UC-1 step 4: Zaúčtování) -------------------------------------

export interface PostingBase {
  obdobiId: string
  dokladId: string
  pripadId: string
  /** ISO date of the posting. */
  datum: string
  /** Responsible person (app_user id) — R10. */
  odpovednaOsoba: string
  /** Correction linkage (ČÚS 001 §35) — both set together or both omitted. */
  opravujeZapisId?: string | null
  opravaTyp?: OpravaTyp | null
  /** Set when this posting is generated by a depreciation plan (UC-4). */
  odpisovyPlanId?: string | null
  /** Set when this posting is generated from an inventory difference (UC-4). */
  inventuraId?: string | null
}

export interface DoubleEntryLineInput {
  ucetId: string
  strana: Strana
  castka: Decimal
  /** Source dílčí (§6/2) — omitted for generated postings (701, depreciation, storno). */
  dilciId?: string | null
}

export interface DoubleEntryInput extends PostingBase {
  lines: DoubleEntryLineInput[]
}

export interface CashLineInput {
  misto: Misto
  smer: Smer
  danovy: boolean
  prubezny?: boolean
  kategorieId?: string | null
  zakladDane?: Decimal | null
  castka: Decimal
  dilciId?: string | null
}

export interface CashEntryInput extends PostingBase {
  regime: Extract<Regime, "JEDNODUCHE" | "DANOVA_EVIDENCE">
  lines: CashLineInput[]
}

export interface PostedEntry {
  zapisId: string
  lineIds: string[]
}
